In [2]:
# pacotes necessários

import pandas as pd

# configurações para exibir todas as linhas do DataFrame
pd.set_option('display.max_rows', None)

# pd.reset_option('display.max_rows')  # opcional: volta ao padrão

## **1 - Identificação dos datasets com problemas**

Alguns datasets vieram com erros, esse `notebook` vai corrigir esses erros.

### **1.1 - Bruto - Ministral-3-8B**

Primeiro vamos avaliar o dataset `geracao_bruto_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_pergunta_en_COMPLETO.csv`:

In [6]:
df_bruto_Ministral_3_8B = "resultados_brutos/geracao_bruto_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_pergunta_en_COMPLETO.csv"

# Deixar o pandas detectar automaticamente o delimitador
df_bruto_Ministral_3_8B = pd.read_csv(df_bruto_Ministral_3_8B)

df_bruto_Ministral_3_8B.columns

Index(['Idioma', 'Interferencia_Tutor', 'Capitulo', 'Num_Questao', 'Pergunta',
       'Modelo', 'Resposta_Gerada', 'Latencia_Total_s', 'TTFT_s', 'ITL_s',
       'Throughput_tps', 'Tokens_In', 'Tokens_Out', 'Tokens_Total'],
      dtype='object')

In [7]:
df_bruto_Ministral_3_8B[['Idioma', 'Modelo', 'Resposta_Gerada']]

,Idioma,Modelo,Resposta_Gerada
0,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Vamos analisar cada parte da questão separadam...
1,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,**Processo de resolução:**\n\n**a) Cálculo da ...
2,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Parte a) Valores das quatro primeiras amos...
3,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Parte a) Qual é a expressão analítica de \...
4,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### **Resolução do Problema**\n\n#### **Parte ...
5,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,**Processo de resolução:**\n\n1. **Sinal origi...
6,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### **a) Projeto de um quantizador escalar uni...
7,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### **1. Quantização de uma Senóide com Amplit...
8,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Para determinar a melhoria esperada na relação...
9,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### **a) Média e variância esperadas do erro d...
10,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Para responder à pergunta sobre se o sinal \( ...
11,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"Vamos analisar cada sinal um por um, calculand..."
12,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Para analisar a **energia total** e a **potênc...
13,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### **Parte a) Energia média em joules**\n\n**...
14,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Vamos analisar cada sinal um por um para deter...
15,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Vamos resolver cada parte do problema passo a ...
16,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"Para resolver este problema, vamos calcular as..."
17,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### **1. Verificando se a matriz A é unitária*...
18,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Para encontrar os coeficientes \(\alpha\) e \(...
19,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Para encontrar uma base ortonormal para o conj...
20,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Para uma **Transformada Discreta de Fourier (D...
21,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,**Processo de resolução:**\n\n1. **Inversão da...
22,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Para derivar as equações da série de Fourier u...
23,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Para determinar os coeficientes da série de Fo...
24,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Para responder à pergunta sobre a utilidade da...
25,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Para encontrar a transformada de Fourier das f...
26,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Para encontrar a transformada de Fourier das f...
27,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Vamos analisar cada parte do problema passo a ...
28,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Vamos analisar cada parte do problema passo a ...
29,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Para encontrar o inverso do Transformada em Te...
30,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Para provar que a Transformada em Tempo Discre...
31,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Vamos resolver cada parte do problema passo a ...
32,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Para encontrar a função temporal \( x(t) \) a ...
33,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Para encontrar a sequência \( x[n] \) a partir...
34,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,**Processo de resolução:**\n\nPara encontrar a...
35,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,**Processo de resolução:**\n\n1. **Transformad...
36,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"Para resolver este problema, vamos analisar as..."
37,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"Para resolver este problema, vamos analisar o ..."
38,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Para determinar se o sistema é Linear e Invari...
39,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"Para resolver este problema, vamos analisar as..."
40,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Vamos analisar cada um dos três sistemas um po...
41,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Para determinar um valor de \( n_0 \) que torn...
42,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"Para determinar as saídas \( y_1(t), y_2(t), y..."
43,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"Para encontrar as saídas \( y_1[n], y_2[n], y_..."
44,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Para encontrar a expressão exata de \( x(t) \)...
45,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"Para resolver este problema, vamos analisar o ..."
46,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Para encontrar a função de transferência \( H(...
47,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Para obter o filtro \( G(s) \) a partir de \( ...
48,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Para encontrar a transformada em z \( H(z) \) ...
49,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### **Resolução do Problema**\n\n#### **a) Enc...
50,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"As funções de transferência **Butterworth**, *..."
51,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Vamos resolver o problema passo a passo.\n\n--...
52,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,**Processo de resolução:**\n\nPara resolver es...
53,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,**Processo de resolução:**\n\n1. **Espectro MS...
54,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Vamos resolver cada parte do problema passo a ...
55,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Vamos analisar cada parte do problema passo a ...
56,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### **Parte a) Cálculo do PSD \( S(e^{j \omega...
57,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Vamos analisar o problema passo a passo.\n\n**...
58,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,**Processo de raciocínio:**\n\n1. **Densidade ...
59,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Um processo aleatório em tempo discreto \(\mat...
60,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze the problem step by step.\n\n###...
61,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's break down the problem step by step.\n\n...
62,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Part a: Sampling without Quantization\n\n*...
63,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Part a) Finding the Analytic Expression of...
64,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Part a) Two's Complement Quantization\n\n*...
65,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's break down the problem step-by-step to f...
66,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Part a) Design of a 3-bit Uniform Scalar Q...
67,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### **Problem Breakdown and Solution**\n\nWe a...
68,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To determine the improvement in the quantizati...
69,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### **Part a) Expected Mean and Variance of th...
70,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To determine whether the signal \( x[n] \) can...
71,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze each signal one by one to determ...
72,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To analyze the total energy and average power ...
73,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Part a) Average Energy in Joules\n\n**Unde...
74,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze each signal one by one to determ...
75,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze the problem step-by-step.\n\nWe ...
76,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"To find the projections and error vectors, we'..."
77,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"### Understanding the Problem\n\nFirst, I need..."
78,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the coefficients \(\alpha\) and \(\bet...
79,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"### Understanding the Problem\n\nFirst, I need..."
80,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The **3-point Discrete Fourier Transform (DFT)...
81,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Step-by-Step Solution:\n\n#### Part 1: Fin...
82,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To derive the pair of Fourier series equations...
83,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the Fourier series coefficients for th...
84,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the expression for the signal \( x(t) ...
85,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the Fourier transform of the given fun...
86,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the Fourier transform of the given fun...
87,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Part a) DTFT of \( x[n] = 0.9^n u[n] + 0.8...
88,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Part a) DTFT of \( x[n] = 0.9^n u[n] + 0.8...
89,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the inverse Discrete-Time Fourier Tran...
90,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To prove that the Discrete-Time Fourier Transf...
91,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze the problem step-by-step.\n\n---...
92,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the inverse Laplace transform \( x(t) ...
93,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the inverse Z-transform of the given s...
94,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Step 1: Understanding the Signal\nThe give...
95,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze the problem step-by-step.\n\n---...
96,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"To solve this problem, we need to understand t..."
97,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"To solve this problem, we need to determine th..."
98,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To determine if the system is Linear Time-Inva...
99,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To determine the output \( y_2(t) \) of the ti...
100,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze each of the three systems one by...
101,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To determine a value for \( n_0 \) that makes ...
102,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"To find the outputs \( y_1(t), y_2(t), y_3(t),..."
103,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"To find the outputs \( y_1[n], y_2[n], y_3[n],..."
104,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the exact expression of the original b...
105,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Understanding the Problem\n\nWe are given ...
106,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the system function \( H(z) \) of the ...
107,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To obtain the filter \( G(s) \) that is a freq...
108,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the discrete-time transfer function \(...
109,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Part a) Finding the Sampling Frequency \( ...
110,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"When comparing **Butterworth**, **Chebyshev**,..."
111,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze the problem step-by-step.\n\n---...
112,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze the problem step-by-step.\n\nWe ...
113,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Understanding the Problem\n\nWe are given ...
114,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's break down the problem step by step.\n\n...
115,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze each part of the question step-b...
116,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Part a) Power Spectral Density (PSD) of th...
117,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze the problem step-by-step.\n\n---...
118,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's break down the problem step-by-step to f...
119,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"### Understanding the Problem\n\nFirst, let's ..."

Aparentemente está tudo **certo** com o dataset `geracao_bruto_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_pergunta_en_COMPLETO.csv`.

### **1.2 - Bruto - gpt-5**

Vamos avaliar o dataset `geracao_bruto_gpt-5_pergunta_pt_pergunta_en_COMPLETO.csv`:

In [8]:
df_bruto_gpt_5 = "resultados_brutos/geracao_bruto_gpt-5_pergunta_pt_pergunta_en_COMPLETO.csv"

# Deixar o pandas detectar automaticamente o delimitador
df_bruto_gpt_5 = pd.read_csv(df_bruto_gpt_5)

df_bruto_gpt_5.columns

Index(['Idioma', 'Interferencia_Tutor', 'Capitulo', 'Num_Questao', 'Pergunta',
       'Modelo', 'Resposta_Gerada', 'Latencia_Total_s', 'TTFT_s', 'ITL_s',
       'Throughput_tps', 'Tokens_In', 'Tokens_Out', 'Tokens_Total'],
      dtype='object')

In [9]:
df_bruto_gpt_5[['Idioma', 'Modelo', 'Resposta_Gerada']]

    Idioma Modelo                                    Resposta_Gerada
0       PT  gpt-5  a)\n- x(1.5) = 3 (pois 1.5 ∈ [0,4])\n- x(3) = ...
1       PT  gpt-5  a) R = b·fs = 8 × 100×10^6 = 8×10^8 bit/s = 80...
2       PT  gpt-5  a) Fs = 100 Hz ⇒ Ts = 0,01 s. Amostras (sem qu...
3       PT  gpt-5  a) Pelo modelo de amostragem com trem de impul...
4       PT  gpt-5  Considere um quantizador uniforme de passo Δ =...
5       PT  gpt-5  Frequência: ω0 = π/3 ⇒ período N0 = 6 amostras...
6       PT  gpt-5  a) Projeto do quantizador escalar uniforme (3 ...
7       PT  gpt-5  Vamos assumir quantização uniforme, sem sobrec...
8       PT  gpt-5  A melhoria na SNR de quantização é de aproxima...
9       PT  gpt-5  Vamos adotar o modelo linear de quantização (e...
10      PT  gpt-5  Não. Um sinal ímpar (odd) satisfaz x[−n] = −x[...
11      PT  gpt-5  Definições\n- Energia: E∞ = ∫_{−∞}^{∞} |x(t)|²...
12      PT  gpt-5  - Para qualquer sinal periódico não nulo, a en...
13      PT  gpt-5  a) Energia média (assumindo carga de 1 Ω e dur...
14      PT  gpt-5  - a) x[n] = u[n] + u[-n-1] = 1 para todo n. Pe...
15      PT  gpt-5  - Normas:\n  - ||[4, 3]|| = sqrt(4^2 + 3^2) = ...
16      PT  gpt-5  Assumindo p_yx = proj de y sobre x e p_xy = pr...
17      PT  gpt-5  Não. Para ser unitária (no caso real, ortogona...
18      PT  gpt-5  Queremos α e β tais that [4, 1] = α[2, 1] + β[...
19      PT  gpt-5  Vamos aplicar Gram–Schmidt à lista na ordem da...
20      PT  gpt-5  Para a DFT ortonormal de 3 pontos (N=3):\n\n- ...
21      PT  gpt-5  - Inversão (DFT ortonormal, N=4): x[n] = (1/√N...
22      PT  gpt-5  Considere um sinal periódico x(t) de período T...
23      PT  gpt-5  Vamos tomar f0 = 50 Hz (ω0 = 2π·50), pois as f...
24      PT  gpt-5  Interpretando o enunciado como “qual é a expre...
25      PT  gpt-5  Usarei a CTFT em f (Hz): X(f) = ∫ x(t) e^{-j 2...
26      PT  gpt-5  Vou usar a convenção de transformada de Fourie...
27      PT  gpt-5  Vamos usar u[n] como o degrau unitário.\n\na) ...
28      PT  gpt-5  Vamos considerar x[n] = (0.9^n + 0.8^n) u[n].\...
29      PT  gpt-5  Vamos denotar a frequência discreta por ω (no ...
30      PT  gpt-5  Vamos provar que o DTFT de x[n] = e^{j ω0 n} é...
31      PT  gpt-5  a) X(2) = 5/(2^2 + 2·2 + 10) = 5/18.\n\nb) A F...
32      PT  gpt-5  Fatorando em frações parciais:\nX(s) = (3s+2)/...
33      PT  gpt-5  Como o ROC é |z| > 0.8, x[n] é à direita (caus...
34      PT  gpt-5  Interpretando -3^n como −(3^n):\n\n- Suporte: ...
35      PT  gpt-5  - Transformada-Z: X(z) = 4 + 5 z^{-11}\n  - RO...
36      PT  gpt-5  Como o sistema é linear e x2[n] = 3 x1[n], a s...
37      PT  gpt-5  Como o sistema é LTI, a resposta ao impulso é ...
38      PT  gpt-5  Não.\n\nSe o sistema fosse LTI, a resposta ao ...
39      PT  gpt-5  Como o sistema é invariante no tempo, a respos...
40      PT  gpt-5  Para cada sistema:\n\n1) y[n] = C (x[n])^2, co...
41      PT  gpt-5  n0 ≤ 2. \n\nJustificativa rápida: definindo m ...
42      PT  gpt-5  Como o sistema é LTI com H(s)=1/(s+10), expone...
43      PT  gpt-5  Ideia-chave: para um sistema LTI discreto, x[n...
44      PT  gpt-5  fs = 10 Hz ⇒ Ts = 0.1 s. Pela interpolação ide...
45      PT  gpt-5  Como |H(jω)|=1 para |ω|≤5 e fase H(jω)=e^{-j8ω...
46      PT  gpt-5  H(z) = 3 − 5 z^{-1} + 7 z^{-2} − 5 z^{-3} + 3 ...
47      PT  gpt-5  Como H(s) é um Butterworth de 3ª ordem com ωc ...
48      PT  gpt-5  Usando T = 1/fs = 1/50 = 0,02 s e a transforma...
49      PT  gpt-5  Ideia-chave: na transformação bilinear, a rela...
50      PT  gpt-5  A seguir está um estudo comparando as resposta...
51      PT  gpt-5  Ideia: com janela retangular w[n]=1, 0≤n≤N−1, ...
52      PT  gpt-5  Resposta assumindo as convenções usuais em Sin...
53      PT  gpt-5  Para x[n] = 3 cos(πn/4) (em volts):\n\n- Escol...
54      PT  gpt-5  Vamos usar a convenção DFT: X[k] = ∑_{n=0}^{N-...
55      PT  gpt-5  Dados X[k]=[8,8,8,8] com N=4:\n\n- (Auxiliar) ...
56      PT  gpt-5  a) Para x[n] = e^{j ω1 n} com ω1 = π/4, após j...
57      PT  gpt-5  - Δf = fs/N = 500/8 = 62.5 Hz\n- Ruído (PSD de...
58      PT  gpt-5  P = 7200 W\n\nJustification (curta):\n- PSD un...
59      PT  gpt-5  Sim. Em teoria, um processo aleatório discreto...
60      EN  gpt-5  a) Continuous-time pulse:\n- x(1.5) = 3\n- x(3...
61      EN  gpt-5  a) Bit rate Rb = b × fs = 8 × 100×10^6 = 8×10^...
62      EN  gpt-5  a) Sampling at fs = 100 Hz gives t_n = n/100 s...
63      EN  gpt-5  a) For uniform impulse sampling, xs(t) = Σk x(...
64      EN  gpt-5  Given Δ = 10 mV = 0.01 V.\n\nUse a mid‑tread u...
65      EN  gpt-5  - x[n] over one period (n = 0…5): [0, √3/2, √3...
66      EN  gpt-5  a) 3-bit uniform quantizer (L = 8 levels) matc...
67      EN  gpt-5  Assume a uniform b-bit quantizer whose full-sc...
68      EN  gpt-5  About 24 dB.\n\nReason: Each extra bit improve...
69      EN  gpt-5  a) For a uniform rounding quantizer, under the...
70      EN  gpt-5  No. For an odd signal, x[-n] = -x[n] for all n...
71      EN  gpt-5  Definitions\n- Energy: E∞ = ∫_{-∞}^{∞} |x(t)|^...
72      EN  gpt-5  - Total energy: Infinite for any nonzero perio...
73      EN  gpt-5  a) Average energy:\n- Mean-square of the level...
74      EN  gpt-5  a) x[n] = u[n] + u[-n-1]\n- Since u[n]=1 for n...
75      EN  gpt-5  - Norms:\n  - ||[4, 3]|| = sqrt(4^2 + 3^2) = 5...
76      EN  gpt-5  - Projection of y onto x: p_yx = ((y·x)/(x·x))...
77      EN  gpt-5  No. A is not unitary because its columns are n...
78      EN  gpt-5  We want α and β such that:\n[4, 1] = α[2, 1] +...
79      EN  gpt-5  Let the inner product be the usual dot product...
80      EN  gpt-5  Let ω = e^(−j 2π/3) = −1/2 − j√3/2 and ω^2 = e...
81      EN  gpt-5  - Inverse (time-domain) sequence:\n  Since the...
82      EN  gpt-5  Let x(t) be T-periodic with fundamental ω0 = 2...
83      EN  gpt-5  Fundamental frequency: f0 = 50 Hz, ω0 = 2πf0 =...
84      EN  gpt-5  x(t) = 3 + 4 cos(200π t − 4) + 10 cos(800π t)\...
85      EN  gpt-5  Assume the continuous-time Fourier transform X...
86      EN  gpt-5  Assume the Fourier transform X(f) = ∫ x(t) e^{...
87      EN  gpt-5  Let x[n] = 0.9^n u[n] + 0.8^n u[n], with u[n] ...
88      EN  gpt-5  Let u[n] be the unit-step sequence. Use linear...
89      EN  gpt-5  Let H(e^{jω}) be the ideal low-pass response o...
90      EN  gpt-5  Let ω denote the frequency variable (your dw)....
91      EN  gpt-5  Given X(s) = 5/(s^2 + 2s + 10), poles at s = -...
92      EN  gpt-5  Poles at s=1 and s=3. With ROC Re(s) < 1 (to t...
93      EN  gpt-5  Given ROC |z| > 0.8 (right-sided), do partial ...
94      EN  gpt-5  x[n] = -3^n u[-n-1] is nonzero for n ≤ -1.\n\n...
95      EN  gpt-5  - Z-transform:\n  X(z) = 4 + 5 z^{-11}\n  ROC:...
96      EN  gpt-5  Because the system is linear and x2[n] = 3 x1[...
97      EN  gpt-5  h[n] = y1[n] = 3δ[n] + 2δ[n−1] + δ[n−2].  \nFo...
98      EN  gpt-5  No. For an LTI system, the response to δ[n] is...
99      EN  gpt-5  y2(t) = y1(t − 3) = δ(t − 4) − δ(t − 7)\n\nRea...
100     EN  gpt-5  System 1: y[n] = C (x[n])^2, C = 2e^{jπ/2}\n- ...
101     EN  gpt-5  n0 ≤ 2. \n\nReason: Rewrite with k = n+2 → y[k...
102     EN  gpt-5  For the causal LTI system H(s) = 1/(s+10) with...
103     EN  gpt-5  Key fact: For a causal LTI system with H(z) = ...
104     EN  gpt-5  x(t) = 4 sinc(10 t) + 3 sinc(10 t − 1) − 2 sin...
105     EN  gpt-5  Passband is |ω| ≤ 5 rad/s with H(jω) = e^{-j8ω...
106     EN  gpt-5  H(z) is the Z-transform of h[n]:\nH(z) = 3 − 5...
107     EN  gpt-5  Frequency-scale H(s) by a = ω_old/ω_new = 5/3,...
108     EN  gpt-5  Use the bilinear transform s = (2/T) (1 − z⁻¹)...
109     EN  gpt-5  Given the bilinear mapping Ω = 2 Fs tan(ω/2):\...
110     EN  gpt-5  Here’s a concise, practical comparison of the ...
111     EN  gpt-5  Assume the N-point DFT definition X[k] = Σ_{n=...
112     EN  gpt-5  Answer assumes sinc(u) = sin(πu)/(πu) and Four...
113     EN  gpt-5  - Period N0 = 8 because ω0 = π/4 and N0 = 2π/ω...
114     EN  gpt-5  a) For a periodic signal, the MS (mean-square/...
115     EN  gpt-5  Given X = [8, 8, 8, 8] as the 4-point FFT (N=4...
116     EN  gpt-5  a) Let y[n] = x[n] w[n], with w[n] = 1 for n=0...
117     EN  gpt-5  Given N=8 and fs=500 Hz, the bin width is Δf =...
118     EN  gpt-5  P = g^2 × N0 × B = 3^2 × 4 W/Hz × 200 Hz = 720...
119     EN  gpt-5  Yes.\n\nHow “power” is defined\n- For a WSS di...

Aparentemente está tudo **certo** com o dataset `geracao_bruto_gpt-5_pergunta_pt_pergunta_en_COMPLETO.csv`.

### **1.3 - Bruto - deepseek V4 Pro**

Vamos avaliar o dataset `geracao_bruto_deepseek-v4-pro_pergunta_pt_pergunta_en_COMPLETO.csv`:

In [30]:
df_bruto_deepseek_v4_pro = "resultados_brutos/geracao_bruto_deepseek-v4-pro_pergunta_pt_pergunta_en_COMPLETO.csv"

# Deixar o pandas detectar automaticamente o delimitador
df_bruto_deepseek_v4_pro = pd.read_csv(df_bruto_deepseek_v4_pro)

df_bruto_deepseek_v4_pro.columns

Index(['Idioma', 'Interferencia_Tutor', 'Capitulo', 'Num_Questao', 'Pergunta',
       'Modelo', 'Resposta_Gerada', 'Latencia_Total_s', 'TTFT_s', 'ITL_s',
       'Throughput_tps', 'Tokens_In', 'Tokens_Out', 'Tokens_Total'],
      dtype='object')

In [31]:
df_bruto_deepseek_v4_pro[['Idioma', 'Modelo', 'Resposta_Gerada']]

    Idioma           Modelo                                    Resposta_Gerada
0       PT  deepseek-v4-pro  a) Para o sinal de tempo contínuo \( x(t) \):\...
1       PT  deepseek-v4-pro  a) A taxa de bits é dada pelo produto do númer...
2       PT  deepseek-v4-pro  **a) Valores das quatro primeiras amostras (ap...
3       PT  deepseek-v4-pro  **a) Expressão analítica de \(x(t)\)**  \nComo...
4       PT  deepseek-v4-pro  **a) ADC com complemento de dois (b=8 bits, Δ=...
5       PT  deepseek-v4-pro  **Período de 6 amostras (n = 0 a 5):**\n\n| n ...
6       PT  deepseek-v4-pro  **a) Projeto do quantizador escalar uniforme d...
7       PT  deepseek-v4-pro  Para quantização uniforme, assume-se que o err...
8       PT  deepseek-v4-pro  A adoção do CAG com 4 bits adicionais do ganho...
9       PT  deepseek-v4-pro  a) **Média e variância do erro de quantização*...
10      PT  deepseek-v4-pro  Não, $x[n]$ não pode ser um sinal ímpar (odd)....
11      PT  deepseek-v4-pro  a) **Sinal:** \(x(t) = 5 \cos(2 \pi \cdot 300 ...
12      PT  deepseek-v4-pro  Sobre a **energia total** e a **potência média...
13      PT  deepseek-v4-pro  **a)** Considerando que os valores de tensão s...
14      PT  deepseek-v4-pro  a) Periódico, \(N_0 = 1\)  \nb) Periódico, \(N...
15      PT  deepseek-v4-pro  **Vetores:**  \n\(\mathbf{u} = [4, 3]\)  \n\(\...
16      PT  deepseek-v4-pro  As projeções e os vetores de erro são:\n\n- **...
17      PT  deepseek-v4-pro  **Resposta:**\n\n1. **A matriz \(A\) não é uni...
18      PT  deepseek-v4-pro  Para encontrar os coeficientes \(\alpha\) e \(...
19      PT  deepseek-v4-pro  **Resposta:**\n\nO conjunto \( \mathcal{C} = \...
20      PT  deepseek-v4-pro  Para uma DFT ortonormal de 3 pontos, a matriz ...
21      PT  deepseek-v4-pro  **Inverso \(\mathbf{x}\):**\nA DFT ortonormal ...
22      PT  deepseek-v4-pro  Vamos derivar o par de equações da série de Fo...
23      PT  deepseek-v4-pro  Os coeficientes da série de Fourier (na forma ...
24      PT  deepseek-v4-pro  A expressão do sinal \(x(t)\) é dada pela séri...
25      PT  deepseek-v4-pro  A transformada de Fourier considerada aqui é d...
26      PT  deepseek-v4-pro                 ERRO: The read operation timed out
27      PT  deepseek-v4-pro  A DTFT de um sinal discreto \(x[n]\) é dada po...
28      PT  deepseek-v4-pro  Aqui estão as demonstrações para a DTFT e a Tr...
29      PT  deepseek-v4-pro  Para encontrar o sinal \(h[n]\) correspondente...
30      PT  deepseek-v4-pro                 ERRO: The read operation timed out
31      PT  deepseek-v4-pro  a) \( X(2) = \frac{5}{2^2 + 2\cdot 2 + 10} = \...
32      PT  deepseek-v4-pro  Para encontrar o sinal \( x(t) \), seguimos os...
33      PT  deepseek-v4-pro  Para encontrar o sinal \( x[n] \) a partir da ...
34      PT  deepseek-v4-pro  A transformada Z do sinal \( x[n] = -3^n u[-n-...
35      PT  deepseek-v4-pro  A transformada Z do sinal é:\n\[ X(z) = 4 + 5z...
36      PT  deepseek-v4-pro  A saída para a entrada \(x_2[n] = 3x_1[n]\) é ...
37      PT  deepseek-v4-pro  A saída \( y_2[n] \) é:\n\n\[\ny_2[n] = 15\del...
38      PT  deepseek-v4-pro  Não, esse sistema não pode ser linear e invari...
39      PT  deepseek-v4-pro  A saída do sistema para a entrada \(x_2(t) = \...
40      PT  deepseek-v4-pro  **Sistema 1:** \(y[n] = C (x[n])^2\), com \(C ...
41      PT  deepseek-v4-pro  Para que o sistema seja causal, a saída \(y[n]...
42      PT  deepseek-v4-pro  As entradas são exponenciais complexas e senoi...
43      PT  deepseek-v4-pro  As entradas são sinais exponenciais complexos ...
44      PT  deepseek-v4-pro  A expressão exata de \(x(t)\) pode ser obtida ...
45      PT  deepseek-v4-pro  A saída do filtro é a soma das componentes de ...
46      PT  deepseek-v4-pro  A função do sistema \( H(z) \) é a transformad...
47      PT  deepseek-v4-pro  Para obter o filtro \( G(s) \) escalado em fre...
48      PT  deepseek-v4-pro  Para encontrar \( H(z) \) a partir de \( H(s) ...
49      PT  deepseek-v4-pro  **a) Frequência de amostragem \(f_s\) sem pré-...
50      PT  deepseek-v4-pro  Vamos analisar as respostas em frequência e no...
51      PT  deepseek-v4-pro  Para o sinal janelado \(x_w[n] = A \cos(\omega...
52      PT  deepseek-v4-pro  a) A energia total do sinal é \(E = 24\) joule...
53      PT  deepseek-v4-pro  O sinal \(x[n] = 3 \cos((\pi/4) n)\) é periódi...
54      PT  deepseek-v4-pro  a) O espectro estimado MS (Mean Square), ou pe...
55      PT  deepseek-v4-pro  **a) DTFS (coeficientes da Série de Fourier de...
56      PT  deepseek-v4-pro  a) A densidade espectral de potência (PSD) do ...
57      PT  deepseek-v4-pro  a) A potência média senoidal é obtida subtrain...
58      PT  deepseek-v4-pro  A potência média do sinal de saída do filtro \...
59      PT  deepseek-v4-pro  Sim, um processo aleatório em tempo discreto p...
60      EN  deepseek-v4-pro  a) For the continuous-time signal \(x(t)\):\n-...
61      EN  deepseek-v4-pro  **a) Bit rate**  \nBit rate = bits per sample ...
62      EN  deepseek-v4-pro  **a) First four samples (without quantization)...
63      EN  deepseek-v4-pro  a) Since the sampling period is \(T_s = 2\) s ...
64      EN  deepseek-v4-pro  **Part (a): Two’s complement ADC (b = 8 bits, ...
65      EN  deepseek-v4-pro  The original sinusoid is \(x[n] = \sin\left(\f...
66      EN  deepseek-v4-pro  **a) 3-bit quantizer design**\n\nSince the inp...
67      EN  deepseek-v4-pro  **Quantization SNR for a Sinusoid**\n\nAssume ...
68      EN  deepseek-v4-pro  The addition of a 4-bit programmable gain AGC ...
69      EN  deepseek-v4-pro  a) Under the linear quantization model, the qu...
70      EN  deepseek-v4-pro  No, \( x[n] \) cannot be an odd signal. By def...
71      EN  deepseek-v4-pro  **a) \( x(t) = 5 \cos(2\pi \cdot 300\,t + \pi/...
72      EN  deepseek-v4-pro  For any non-zero periodic signal that extends ...
73      EN  deepseek-v4-pro  **a) Average energy**  \nThe set \(\mathcal{M}...
74      EN  deepseek-v4-pro  For each signal, periodicity in discrete time ...
75      EN  deepseek-v4-pro  The norms, inner product, and angle between th...
76      EN  deepseek-v4-pro  The projections and error vectors are computed...
77      EN  deepseek-v4-pro  **1. Is \(\bA\) unitary?**\nNo, \(\bA\) is not...
78      EN  deepseek-v4-pro  The coefficients are \(\alpha = 2\) and \(\bet...
79      EN  deepseek-v4-pro  **Step 1: Identify a linearly independent subs...
80      EN  deepseek-v4-pro  The forward and inverse matrices for a 3-point...
81      EN  deepseek-v4-pro  The inverse 4-point orthonormal DFT of \(\bX =...
82      EN  deepseek-v4-pro  To derive the Fourier series pair, we start wi...
83      EN  deepseek-v4-pro  The signal is \( x(t) = 2 + 3 \cos(2\pi 100 t)...
84      EN  deepseek-v4-pro  The signal \(x(t)\) can be reconstructed from ...
85      EN  deepseek-v4-pro  The Fourier transform is defined as:\n\[\nX(f)...
86      EN  deepseek-v4-pro  Assuming the normalized sinc function \(\opera...
87      EN  deepseek-v4-pro  **a) Discrete-Time Fourier Transform (DTFT)**\...
88      EN  deepseek-v4-pro  **a) Discrete-Time Fourier Transform (DTFT)**\...
89      EN  deepseek-v4-pro  The inverse DTFT of an ideal low-pass filter i...
90      EN  deepseek-v4-pro  The given \(X(e^{j\omega})\) is the Discrete-T...
91      EN  deepseek-v4-pro  **a)** Evaluate \(X(s)\) at \(s=2\):  \nSince ...
92      EN  deepseek-v4-pro  The signal \(x(t)\) is obtained by taking the ...
93      EN  deepseek-v4-pro  The inverse Z-transform of \( X(z) = \frac{5z^...
94      EN  deepseek-v4-pro  The Z-transform of the signal \(x[n] = -3^n u[...
95      EN  deepseek-v4-pro  The Z-transform of \(x[n] = 4\delta[n] + 5\del...
96      EN  deepseek-v4-pro  The system is linear, meaning it satisfies the...
97      EN  deepseek-v4-pro  The output of an LTI system is the convolution...
98      EN  deepseek-v4-pro  No, this system cannot be LTI. For a linear ti...
99      EN  deepseek-v4-pro  For a time-invariant system, a delay in the in...
100     EN  deepseek-v4-pro  Here is the classification of each system:\n\n...
101     EN  deepseek-v4-pro  A causal LTI system requires that the output \...
102     EN  deepseek-v4-pro  The outputs of the causal system \(H(s) = \fra...
103     EN  deepseek-v4-pro  The system is LTI with transfer function \(H(z...
104     EN  deepseek-v4-pro  The original band-limited signal \(x(t)\) can ...
105     EN  deepseek-v4-pro  The filter is an ideal lowpass filter that pas...
106     EN  deepseek-v4-pro  The system function \(H(z)\) is the Z-transfor...
107     EN  deepseek-v4-pro  To scale the filter in frequency and adjust th...
108     EN  deepseek-v4-pro  The bilinear transform maps the continuous-tim...
109     EN  deepseek-v4-pro  (a) The bilinear transform maps frequencies ac...
110     EN  deepseek-v4-pro  When designing filters—whether for audio proce...
111     EN  deepseek-v4-pro  **Part (a):** \(\omega_1 = 3\Delta\omega = 3\p...
112     EN  deepseek-v4-pro  a) Total signal energy: 24 Joules (or \(\text{...
113     EN  deepseek-v4-pro  The "MS spectrum" (mean-square spectrum) \(\ha...
114     EN  deepseek-v4-pro  a) The estimated mean-square (MS) spectrum for...
115     EN  deepseek-v4-pro  **a) DTFS (Discrete-Time Fourier Series) coeff...
116     EN  deepseek-v4-pro  a) The power spectral density (PSD) of the win...
117     EN  deepseek-v4-pro  a) The sinusoid average power is 500 W.  \nb) ...
118     EN  deepseek-v4-pro  The average power \( \mathcal{P} \) is 7200 W....
119     EN  deepseek-v4-pro  **Yes**, a discrete-time random process can ha...

Foi observada uma inconsistência na instância 31:

In [12]:
df_bruto_deepseek_v4_pro.iloc[30]

Idioma                                                                PT
Interferencia_Tutor                                                  NÃO
Capitulo                         2. Transforms and Signal Representation
Num_Questao                                                         21.0
Pergunta               Prove isso $X(e^{j \dw})=\sum_{k=-\infty}^{\in...
Modelo                                                   deepseek-v4-pro
Resposta_Gerada                       ERRO: The read operation timed out
Latencia_Total_s                                                     0.0
TTFT_s                                                               0.0
ITL_s                                                                0.0
Throughput_tps                                                       0.0
Tokens_In                                                              0
Tokens_Out                                                             0
Tokens_Total                                                           0
Name: 30, dtype: object

Teremos que corrigir mais a frente a instância 31 do dataset `geracao_bruto_deepseek-v4-pro_pergunta_pt_pergunta_en_COMPLETO.csv` pois houve erros de requisição da rede deeepseek:

In [32]:
df_bruto_deepseek_v4_pro.at[30, 'Resposta_Gerada']

'ERRO: The read operation timed out'

### **1.4 - Tutor - Ministral-3-8B**

Vamos avaliar o dataset `geracao_tutor_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_pergunta_en_COMPLETO.csv`:

In [14]:
df_tutor_Ministral_3_8B = "resultados_brutos/geracao_tutor_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_pergunta_en_COMPLETO.csv"

# Deixar o pandas detectar automaticamente o delimitador
df_tutor_Ministral_3_8B = pd.read_csv(df_tutor_Ministral_3_8B)

df_tutor_Ministral_3_8B.columns

Index(['Idioma', 'Interferencia_Tutor', 'Capitulo', 'Num_Questao', 'Pergunta',
       'Modelo', 'Resposta_Gerada', 'Latencia_Total_s', 'TTFT_s', 'ITL_s',
       'Throughput_tps', 'Tokens_In', 'Tokens_Out', 'Tokens_Total'],
      dtype='object')

In [15]:
df_tutor_Ministral_3_8B[['Idioma', 'Modelo', 'Resposta_Gerada']]

,Idioma,Modelo,Resposta_Gerada
0,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nVamos anali...
1,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\na) A taxa d...
2,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\n### a) Valo...
3,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\n**a) Expres...
4,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nO problema ...
5,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nVamos resol...
6,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara projet...
7,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
8,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nA melhoria ...
9,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\n---\n**a) M...
10,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"A resposta para sua pergunta é: Sim, o sinal $..."
11,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nVamos anali...
12,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara sinais...
13,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\na) A energi...
14,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nVamos anali...
15,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nDados os ve...
16,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
17,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara verifi...
18,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
19,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
20,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara uma **...
21,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
22,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara deriva...
23,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
24,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nA expressão...
25,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
26,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
27,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
28,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
29,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
30,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo prove th...
31,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nVamos resol...
32,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
33,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
34,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nA transform...
35,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
36,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
37,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
38,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"A resposta para sua pergunta é: **Sim**, o sis..."
39,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nDado que o ...
40,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nAnalisaremo...
41,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara que o ...
42,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
43,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
44,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nA expressão...
45,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo solve th...
46,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nA função do...
47,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara obter ...
48,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
49,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
50,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe compari...
51,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nVamos resol...
52,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
53,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
54,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
55,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
56,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
57,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
58,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
59,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"A resposta para sua pergunta é: Não, um proces..."
60,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n### Part (a...
61,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n**a) B...
62,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
63,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
64,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nBelow is a ...
65,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
66,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
67,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n### Quantiz...
68,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe expecte...
69,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
70,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"The answer to your question is: No, the signal..."
71,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
72,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nFor any per...
73,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n**a)...
74,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
75,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nGiven the v...
76,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
77,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo determin...
78,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
79,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nBelow is a ...
80,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe forward...
81,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nGiven the 4...
82,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo derive t...
83,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
84,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
85,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe Fourier...
86,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
87,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
88,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
89,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
90,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo prove th...
91,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
92,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
93,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
94,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
95,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
96,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo solve th...
97,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nGiven the i...
98,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is: To determine i...
99,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nGiven that ...
100,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nBelow is th...
101,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo determin...
102,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe problem...
103,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo determin...
104,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe sampled...
105,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo solve th...
106,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe system ...
107,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo obtain t...
108,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find $H(...
109,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
110,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe compari...
111,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo solve th...
112,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo solve th...
113,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
114,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
115,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nGiven the 4...
116,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n### Part (a...
117,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThis proble...
118,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
119,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nA discrete-...

Foram identificados problemas de linguagem nas instâncias 28, 29, 31, 46 e 51, essas respostas deveriam vir em português e vieram em inglês:

In [16]:
df_tutor_Ministral_3_8B.iloc[[27, 28, 30, 45, 50]][['Idioma', 'Modelo', 'Resposta_Gerada']]

,Idioma,Modelo,Resposta_Gerada
27,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
28,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
30,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo prove th...
45,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo solve th...
50,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe compari...

Essas instâncias terão de ser substituidas mais a frente.

### **1.5 - Tutor - gpt-5**

Vamos avaliar o dataset `geracao_tutor_gpt-5_pergunta_pt_pergunta_en_COMPLETO.csv`:

In [17]:
df_tutor_gpt_5 = "resultados_brutos/geracao_tutor_gpt-5_pergunta_pt_pergunta_en_COMPLETO.csv"

# Deixar o pandas detectar automaticamente o delimitador
df_tutor_gpt_5 = pd.read_csv(df_tutor_gpt_5)

df_tutor_gpt_5.columns

Index(['Idioma', 'Interferencia_Tutor', 'Capitulo', 'Num_Questao', 'Pergunta',
       'Modelo', 'Resposta_Gerada', 'Latencia_Total_s', 'TTFT_s', 'ITL_s',
       'Throughput_tps', 'Tokens_In', 'Tokens_Out', 'Tokens_Total'],
      dtype='object')

In [18]:
df_tutor_gpt_5[['Idioma', 'Modelo', 'Resposta_Gerada']]

    Idioma Modelo                                    Resposta_Gerada
0       PT  gpt-5  A resposta para sua pergunta é:\na) Para o sin...
1       PT  gpt-5  A resposta para sua pergunta é:\na) A taxa de ...
2       PT  gpt-5  A resposta para sua pergunta é:\na) Amostragem...
3       PT  gpt-5  A resposta para sua pergunta é:\na) Pelo model...
4       PT  gpt-5  A resposta para sua pergunta é:\nVamos assumir...
5       PT  gpt-5  A resposta para sua pergunta é:\n- Período fun...
6       PT  gpt-5  A resposta para sua pergunta é:\na) Projeto do...
7       PT  gpt-5  A resposta para sua pergunta é:\nUsando o mode...
8       PT  gpt-5  A resposta para sua pergunta é: aproximadament...
9       PT  gpt-5  A resposta para sua pergunta é:\na) Pelo model...
10      PT  gpt-5  ERRO: HTTPConnectionPool(host='127.0.0.1', por...
11      PT  gpt-5  A resposta para sua pergunta é:\n- a) Para $x(...
12      PT  gpt-5  A resposta para sua pergunta é: todo sinal per...
13      PT  gpt-5  A resposta para sua pergunta é:\na) Como todos...
14      PT  gpt-5  A resposta para sua pergunta é:\n- a) Não peri...
15      PT  gpt-5  A resposta para sua pergunta é:\n- Normas (L2)...
16      PT  gpt-5  A resposta para sua pergunta é:\n- Produto int...
17      PT  gpt-5  A resposta para sua pergunta é:\n- Como verifi...
18      PT  gpt-5  A resposta para sua pergunta é:\nComo a base é...
19      PT  gpt-5  A resposta para sua pergunta é:\nAplicando Gra...
20      PT  gpt-5  A resposta para sua pergunta é:\nPara a DFT or...
21      PT  gpt-5  A resposta para sua pergunta é:\n- Inverso da ...
22      PT  gpt-5  A resposta para sua pergunta é:\nDerivação usa...
23      PT  gpt-5  A resposta para sua pergunta é:\nComo o proble...
24      PT  gpt-5  A resposta para sua pergunta é:\nA expressão $...
25      PT  gpt-5  A resposta para sua pergunta é:\nComo método, ...
26      PT  gpt-5  A resposta para sua pergunta é:\nComo este é e...
27      PT  gpt-5  A resposta para sua pergunta é:\n\na) DTFT de ...
28      PT  gpt-5  A resposta para sua pergunta é:\na) DTFT de x[...
29      PT  gpt-5  A resposta para sua pergunta é:\nVamos determi...
30      PT  gpt-5  A resposta para sua pergunta é:\nProva usando ...
31      PT  gpt-5  A resposta para sua pergunta é:\n- a) Avaliand...
32      PT  gpt-5  A resposta para sua pergunta é:\nComo os polos...
33      PT  gpt-5  A resposta para sua pergunta é:\nComo a ROC é ...
34      PT  gpt-5  A resposta para sua pergunta é:\n- Transformad...
35      PT  gpt-5  A resposta para sua pergunta é:\n- Pela defini...
36      PT  gpt-5  A resposta para sua pergunta é:\nComo o sistem...
37      PT  gpt-5  A resposta para sua pergunta é:\nComo o sistem...
38      PT  gpt-5  A resposta para sua pergunta é: Não. Esse sist...
39      PT  gpt-5  A resposta para sua pergunta é:\nComo o sistem...
40      PT  gpt-5  A resposta para sua pergunta é:\nClassificação...
41      PT  gpt-5  A resposta para sua pergunta é: escolha, por e...
42      PT  gpt-5  A resposta para sua pergunta é:\nComo se trata...
43      PT  gpt-5  A resposta para sua pergunta é:\nComo cada um ...
44      PT  gpt-5  A resposta para sua pergunta é:\nComo $\fs=10$...
45      PT  gpt-5  A resposta para sua pergunta é:\nMétodo para o...
46      PT  gpt-5  A resposta para sua pergunta é:\nComo se trata...
47      PT  gpt-5  A resposta para sua pergunta é:\n- Para mudar ...
48      PT  gpt-5  A resposta para sua pergunta é:\nUsando a tran...
49      PT  gpt-5  A resposta para sua pergunta é:\n- a) Escolhen...
50      PT  gpt-5  A resposta para sua pergunta é:\n- Bessel\n  -...
51      PT  gpt-5  A resposta para sua pergunta é:\n- Usando o DT...
52      PT  gpt-5  A resposta para sua pergunta é:\nComo foco no ...
53      PT  gpt-5  A resposta para sua pergunta é:\n- Passo 1 (pe...
54      PT  gpt-5  A resposta para sua pergunta é:\n- a) Usando a...
55      PT  gpt-5  A resposta para sua pergunta é:\nComo você for...
56      PT  gpt-5  A resposta para sua pergunta é:\n\na) Após mul...
57      PT  gpt-5  A resposta para sua pergunta é:\nComo se trata...
58      PT  gpt-5  A resposta para sua pergunta é:\na) Como o ruí...
59      PT  gpt-5  A resposta para sua pergunta é:\n- Sim, um pro...
60      EN  gpt-5  The answer to your question is:\na) Continuous...
61      EN  gpt-5  The answer to your question is:\na) Bit rate: ...
62      EN  gpt-5  The answer to your question is:\na) Sampling o...
63      EN  gpt-5  The answer to your question is:\na) By definit...
64      EN  gpt-5  The answer to your question is:\na) Two’s comp...
65      EN  gpt-5  The answer to your question is:\n- One period ...
66      EN  gpt-5  ERRO: HTTPConnectionPool(host='127.0.0.1', por...
67      EN  gpt-5  The answer to your question is:\n- Under the u...
68      EN  gpt-5  The answer to your question is:\nUsing the rul...
69      EN  gpt-5  The answer to your question is:\nBecause this ...
70      EN  gpt-5  The answer to your question is:\nThink through...
71      EN  gpt-5  The answer to your question is:\na) x(t) = 5 c...
72      EN  gpt-5  The answer to your question is:\n- Any nonzero...
73      EN  gpt-5  The answer to your question is:\na) Average en...
74      EN  gpt-5  A resposta para sua pergunta é:\n- Ideia-chave...
75      EN  gpt-5  The answer to your question is:\n- Norms (L2):...
76      EN  gpt-5  The answer to your question is:\nBecause proje...
77      EN  gpt-5  The answer to your question is:\n- The matrix ...
78      EN  gpt-5  The answer to your question is:\nGiven $\overl...
79      EN  gpt-5  The answer to your question is:\nI did not fin...
80      EN  gpt-5  The answer to your question is:\nFor the 3-poi...
81      EN  gpt-5  The answer to your question is:\n- Inverse (un...
82      EN  gpt-5  A resposta para sua pergunta é:\nDerivação pel...
83      EN  gpt-5  The answer to your question is:\nSince the sig...
84      EN  gpt-5  The answer to your question is:\nBecause you a...
85      EN  gpt-5  The answer to your question is:\nBecause this ...
86      EN  gpt-5  The answer to your question is:\nSince this is...
87      EN  gpt-5  A resposta para sua pergunta é:\na) DTFT de x[...
88      EN  gpt-5  The answer to your question is:\na) DTFT of x[...
89      EN  gpt-5  The answer to your question is:\nWe denote the...
90      EN  gpt-5  The answer to your question is:\nWe use the DT...
91      EN  gpt-5  The answer to your question is:\n- Given a rig...
92      EN  gpt-5  The answer to your question is:\nGiven $X(s)=\...
93      EN  gpt-5  ERRO: HTTPConnectionPool(host='127.0.0.1', por...
94      EN  gpt-5  The answer to your question is:\n- Z transform...
95      EN  gpt-5  The answer to your question is:\n- Z-transform...
96      EN  gpt-5  The answer to your question is:\nBecause the s...
97      EN  gpt-5  The answer to your question is:\nGiven that th...
98      EN  gpt-5  The answer to your question is: No, this syste...
99      EN  gpt-5  The answer to your question is: \nUsing time-i...
100     EN  gpt-5  The answer to your question is:\n- System 1: $...
101     EN  gpt-5  The answer to your question is: any integer va...
102     EN  gpt-5  The answer to your question is:\nBecause compl...
103     EN  gpt-5  The answer to your question is:\nBecause discr...
104     EN  gpt-5  The answer to your question is:\nSince the sam...
105     EN  gpt-5  The answer to your question is:\nBecause the s...
106     EN  gpt-5  The answer to your question is:\nGiven the FIR...
107     EN  gpt-5  The answer to your question is:\nUsing frequen...
108     EN  gpt-5  The answer to your question is:\nUsing the bil...
109     EN  gpt-5  The answer to your question is:\na) Use the “s...
110     EN  gpt-5  A resposta para sua pergunta é:\n- Critérios p...
111     EN  gpt-5  The answer to your question is:\nUsing the DTF...
112     EN  gpt-5  The answer to your question is:\nBecause your ...
113     EN  gpt-5  The answer to your question is:\nMethod (do no...
114     EN  gpt-5  The answer to your question is:\n- Definitions...
115     EN  gpt-5  The answer to your question is:\n- Assumptions...
116     EN  gpt-5  The answer to your question is:\na) Method to ...
117     EN  gpt-5  The answer to your question is:\na) Sinusoid a...
118     EN  gpt-5  The answer to your question is:\na) The averag...
119     EN  gpt-5  The answer to your question is:\n- For the dis...

foram identificados inconsistências nas instâncias 11, 67 e 94 (erro de requisição) e instâncias 75, 83, 88 e 111 (linguagem):

In [19]:
# erros de requisição
df_tutor_gpt_5.iloc[[10, 66, 93]][['Idioma', 'Modelo', 'Resposta_Gerada']]

   Idioma Modelo                                    Resposta_Gerada
10     PT  gpt-5  ERRO: HTTPConnectionPool(host='127.0.0.1', por...
66     EN  gpt-5  ERRO: HTTPConnectionPool(host='127.0.0.1', por...
93     EN  gpt-5  ERRO: HTTPConnectionPool(host='127.0.0.1', por...

In [20]:
df_tutor_gpt_5.at[10, 'Resposta_Gerada']

"ERRO: HTTPConnectionPool(host='127.0.0.1', port=8000): Read timed out."

In [21]:
# erros de tradução
df_tutor_gpt_5.iloc[[74, 82, 87, 110]][['Idioma', 'Modelo', 'Resposta_Gerada']]

    Idioma Modelo                                    Resposta_Gerada
74      EN  gpt-5  A resposta para sua pergunta é:\n- Ideia-chave...
82      EN  gpt-5  A resposta para sua pergunta é:\nDerivação pel...
87      EN  gpt-5  A resposta para sua pergunta é:\na) DTFT de x[...
110     EN  gpt-5  A resposta para sua pergunta é:\n- Critérios p...

Essas instâncias terão de ser substituidas mais a frente.

### **1.6 - Tutor - deepseek V4 Pro**

Vamos avaliar o dataset `geracao_tutor_deepseek-v4-pro_pergunta_pt_pergunta_en_COMPLETO.csv`:

In [22]:
df_tutor_deepseek_v4_pro = "resultados_brutos/geracao_tutor_deepseek-v4-pro_pergunta_pt_pergunta_en_COMPLETO.csv"

# Deixar o pandas detectar automaticamente o delimitador
df_tutor_deepseek_v4_pro = pd.read_csv(df_tutor_deepseek_v4_pro)

df_tutor_deepseek_v4_pro.columns

Index(['Idioma', 'Interferencia_Tutor', 'Capitulo', 'Num_Questao', 'Pergunta',
       'Modelo', 'Resposta_Gerada', 'Latencia_Total_s', 'TTFT_s', 'ITL_s',
       'Throughput_tps', 'Tokens_In', 'Tokens_Out', 'Tokens_Total'],
      dtype='object')

In [23]:
df_tutor_deepseek_v4_pro[['Idioma', 'Modelo', 'Resposta_Gerada']]

    Idioma           Modelo                                    Resposta_Gerada
0       PT  deepseek-v4-pro  A resposta para sua pergunta é: \n\n**a) Sinal...
1       PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\na) A taxa d...
2       PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\n**a) Valore...
3       PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\n**a) Expres...
4       PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nA quantizaç...
5       PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nDada a sinu...
6       PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\na) Como o s...
7       PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara encont...
8       PT  deepseek-v4-pro  A resposta para sua pergunta é: a melhoria esp...
9       PT  deepseek-v4-pro                                                NaN
10      PT  deepseek-v4-pro  A resposta para sua pergunta é: Não, $x[n]$ nã...
11      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara os sin...
12      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nSinais peri...
13      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\n**a) Energi...
14      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\na) $x[n] = ...
15      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nDado os vet...
16      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nAs projeçõe...
17      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nA matriz $\...
18      PT  deepseek-v4-pro  A resposta para sua pergunta é: α = 2 e β = -1...
19      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara resolv...
20      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara obter ...
21      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\n1. **Cálcul...
22      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nA derivação...
23      PT  deepseek-v4-pro  A resposta para sua pergunta é: para obter os ...
24      PT  deepseek-v4-pro  A resposta para sua pergunta é: a expressão $x...
25      PT  deepseek-v4-pro  A resposta para sua pergunta é: para encontrar...
26      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara determ...
27      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\n**a) DTFT d...
28      PT  deepseek-v4-pro  A resposta para sua pergunta é: O contexto for...
29      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara encont...
30      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara provar...
31      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\n**a)** Para...
32      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\n$$\nx(t) = ...
33      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara encont...
34      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nA transform...
35      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara determ...
36      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nComo o sist...
37      PT  deepseek-v4-pro  A resposta para sua pergunta é:  \nPara encont...
38      PT  deepseek-v4-pro  A resposta para sua pergunta é: **Não, esse si...
39      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nA saída do ...
40      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nOs sistemas...
41      PT  deepseek-v4-pro  A resposta para sua pergunta é: um valor possí...
42      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara resolv...
43      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara determ...
44      PT  deepseek-v4-pro  A resposta para sua pergunta é:  \n$$\nx(t) = ...
45      PT  deepseek-v4-pro  A resposta para sua pergunta é:  \nO problema ...
46      PT  deepseek-v4-pro  A resposta para sua pergunta é:  \nA função do...
47      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara escala...
48      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara encont...
49      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\n### a) Enco...
50      PT  deepseek-v4-pro  A resposta para sua pergunta é:  \n\nAs aproxi...
51      PT  deepseek-v4-pro                                                NaN
52      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPrimeiramen...
53      PT  deepseek-v4-pro  A resposta para sua pergunta é:  \nO espectro ...
54      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\na) O espect...
55      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara resolv...
56      PT  deepseek-v4-pro  A resposta para sua pergunta é: este exercício...
57      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara resolv...
58      PT  deepseek-v4-pro  A resposta para sua pergunta é: $\calP = 7200$...
59      PT  deepseek-v4-pro  A resposta para sua pergunta é: Sim, um proces...
60      EN  deepseek-v4-pro  The answer to your question is: This is exerci...
61      EN  deepseek-v4-pro  The answer to your question is:\n\n**a) Bit ra...
62      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\n**a) Primei...
63      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\n**a)** Dado...
64      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nAbaixo é fo...
65      EN  deepseek-v4-pro                                                NaN
66      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\n### a) Proj...
67      EN  deepseek-v4-pro  The answer to your question is:\n\nFor a full-...
68      EN  deepseek-v4-pro  The answer to your question is: The adoption o...
69      EN  deepseek-v4-pro                                                NaN
70      EN  deepseek-v4-pro  A resposta para sua pergunta é: **Não, o sinal...
71      EN  deepseek-v4-pro  The answer to your question is:\n\nFor the con...
72      EN  deepseek-v4-pro  The answer to your question is: for any period...
73      EN  deepseek-v4-pro  The answer to your question is:\n\na) The set ...
74      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nVamos anali...
75      EN  deepseek-v4-pro  The answer to your question is:\n\nFirst, let ...
76      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara encont...
77      EN  deepseek-v4-pro  The answer to your question is:\n\n**No,** the...
78      EN  deepseek-v4-pro  A resposta para sua pergunta é: os coeficiente...
79      EN  deepseek-v4-pro  A resposta para sua pergunta é: o contexto rec...
80      EN  deepseek-v4-pro  The answer to your question is: For a 3-point ...
81      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nO sinal ori...
82      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nTo derive t...
83      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara obter ...
84      EN  deepseek-v4-pro  The answer to your question is: using the Four...
85      EN  deepseek-v4-pro  The answer to your question is:  \nTo find the...
86      EN  deepseek-v4-pro  A resposta para sua pergunta é: para determina...
87      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara o sina...
88      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\n**a) Transf...
89      EN  deepseek-v4-pro  The answer to your question is:\n\nThe inverse...
90      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara provar...
91      EN  deepseek-v4-pro  The answer to your question is:\n\nWe are give...
92      EN  deepseek-v4-pro  The answer to your question is:\n\nGiven \( X(...
93      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara encont...
94      EN  deepseek-v4-pro  The answer to your question is:\n\nThe Z‑trans...
95      EN  deepseek-v4-pro  The answer to your question is:\n\nThe Z trans...
96      EN  deepseek-v4-pro  The answer to your question is: $y_2[n] = 12\,...
97      EN  deepseek-v4-pro  The answer to your question is: the output $y_...
98      EN  deepseek-v4-pro  The answer to your question is: No, this syste...
99      EN  deepseek-v4-pro  A resposta para sua pergunta é:  \nO sistema é...
100     EN  deepseek-v4-pro  The answer to your question is:\n\n**System 1:...
101     EN  deepseek-v4-pro  The answer to your question is: **\(n_0 = 0\)*...
102     EN  deepseek-v4-pro  The answer to your question is:\n\nThe system ...
103     EN  deepseek-v4-pro  The answer to your question is:\n\nFor the cau...
104     EN  deepseek-v4-pro  The answer to your question is:\n\nGiven the s...
105     EN  deepseek-v4-pro  The answer to your question is: The filter has...
106     EN  deepseek-v4-pro  The answer to your question is:  \nThe system ...
107     EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nTo obtain \...
108     EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara obter ...
109     EN  deepseek-v4-pro  The answer to your question is:\n\n**a)** To d...
110     EN  deepseek-v4-pro  The answer to your question is:\n\nWhen design...
111     EN  deepseek-v4-pro                                                NaN
112     EN  deepseek-v4-pro  The answer to your question is:\n\nTo determin...
113     EN  deepseek-v4-pro  The answer to your question is: the MS spectru...
114     EN  deepseek-v4-pro  The answer to your question is:\n\na) The esti...
115     EN  deepseek-v4-pro  The answer to your question is:\n\nGiven $X[k]...
116     EN  deepseek-v4-pro  The answer to your question is provided as a s...
117     EN  deepseek-v4-pro  The answer to your question is:\n\na) **Sinuso...
118     EN  deepseek-v4-pro  A resposta para sua pergunta é: $\mathcal{P} =...
119     EN  deepseek-v4-pro  The answer to your question is: **Yes**, a dis...

foram identificados inconsistências nas instâncias 10, 52, 66, 70, 112 (erro de requisição) e instâncias 63, 64, 65, 71, 75, 77, 79, 80, 82, 83, 84, 87, 88, 89, 91, 94, 100, 108, 109, 119:

In [24]:
# erros de requisição
df_tutor_deepseek_v4_pro.iloc[[9, 51, 65, 69, 111]][['Idioma', 'Modelo', 'Resposta_Gerada']]

    Idioma           Modelo Resposta_Gerada
9       PT  deepseek-v4-pro             NaN
51      PT  deepseek-v4-pro             NaN
65      EN  deepseek-v4-pro             NaN
69      EN  deepseek-v4-pro             NaN
111     EN  deepseek-v4-pro             NaN

In [ ]:
# erros de linguagem
df_tutor_deepseek_v4_pro.iloc[[62, 63, 64, 66, 70, 74, 76, 78, 79, 81, 82, 83, 86, 87, 88, 90, 93, 99, 107, 108, 118]][['Idioma', 'Modelo', 'Resposta_Gerada']]

    Idioma           Modelo                                    Resposta_Gerada
62      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\n**a) Primei...
63      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\n**a)** Dado...
64      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nAbaixo é fo...
66      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\n### a) Proj...
70      EN  deepseek-v4-pro  A resposta para sua pergunta é: **Não, o sinal...
74      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nVamos anali...
76      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara encont...
78      EN  deepseek-v4-pro  A resposta para sua pergunta é: os coeficiente...
79      EN  deepseek-v4-pro  A resposta para sua pergunta é: o contexto rec...
81      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nO sinal ori...
82      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nTo derive t...
83      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara obter ...
86      EN  deepseek-v4-pro  A resposta para sua pergunta é: para determina...
87      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara o sina...
88      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\n**a) Transf...
90      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara provar...
93      EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara encont...
99      EN  deepseek-v4-pro  A resposta para sua pergunta é:  \nO sistema é...
107     EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nTo obtain \...
108     EN  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara obter ...
118     EN  deepseek-v4-pro  A resposta para sua pergunta é: $\mathcal{P} =...

## **2 - Correção dos Datasets**

1. **DeepSeek Bruto:** 1 erro (Timeout na linha 30).
2. **Ministral Tutor:** 5 erros (Linguagem nas linhas 27, 28, 30, 45, 50).
3. **GPT-5 Tutor:** 7 erros (Timeouts nas linhas 10, 66, 93 e Linguagem nas linhas 74, 82, 87, 110).
4. **DeepSeek Tutor:** 26 erros (Timeouts e Linguagem misturados).

In [33]:
import pandas as pd
import csv
import time
from gerador_respostas import BenchmarkRunner, TutorInteligenteRunner

def corrigir_cirurgico(caminho_csv, caminho_txt, indices, modelo, tipo_teste):
    # 1. Carregar os dados
    df_csv = pd.read_csv(caminho_csv)
    df_txt = pd.read_csv(caminho_txt, sep='\t', quotechar='|', quoting=csv.QUOTE_NONNUMERIC, encoding='utf-8')

    print(f"\n[INICIANDO CORREÇÃO] {tipo_teste.upper()} | Modelo: {modelo} | {len(indices)} linhas")

    # 2. Instanciar a classe correta do seu gerador_respostas.py
    if tipo_teste == "tutor":
        runner = TutorInteligenteRunner(model_name=modelo)
    else:
        runner = BenchmarkRunner(model_name=modelo)
        
    runner.run_warmup()

    # 3. Iterar nos índices problemáticos
    for idx in indices:
        idioma = df_csv.at[idx, 'Idioma']
        idx_txt = idx if idx < 60 else idx - 60 
        
        print(f" -> Re-inferindo índice {idx} ({idioma})...")
        
        # 4. Resgatar a pergunta base
        pergunta = df_txt.at[idx_txt, 'pergunta_pt'] if idioma == 'PT' else df_txt.at[idx_txt, 'pergunta_en']
        
        # 5. Blindagem de Idioma (Injetada APENAS no modo tutor)
        if tipo_teste == "tutor":
            if idioma == 'PT':
                pergunta = "[REGRA RESTRITA: Responda EXCLUSIVAMENTE em Português. Comece sua resposta com 'A resposta para sua pergunta é:']\n\n" + pergunta
            else:
                pergunta = "[STRICT RULE: Answer EXCLUSIVELY in English. Start your response with 'The answer to your question is:']\n\n" + pergunta
                
        # 6. Gerar nova resposta
        metrics = runner.generate_response(pergunta)
        
        # 7. Atualizar DataFrame
        df_csv.at[idx, 'Resposta_Gerada'] = metrics["Resposta_Gerada"]
        df_csv.at[idx, 'Latencia_Total_s'] = metrics["Latencia_Total_s"]
        df_csv.at[idx, 'TTFT_s'] = metrics["TTFT_s"]
        df_csv.at[idx, 'ITL_s'] = metrics["ITL_s"]
        df_csv.at[idx, 'Throughput_tps'] = metrics["Throughput_tps"]
        df_csv.at[idx, 'Tokens_In'] = metrics["Tokens_In"]
        df_csv.at[idx, 'Tokens_Out'] = metrics["Tokens_Out"]
        df_csv.at[idx, 'Tokens_Total'] = metrics["Tokens_Total"]
        
        time.sleep(1)
        
    # 8. Salvar arquivo
    caminho_salvar = caminho_csv.replace(".csv", "_CORRIGIDO.csv")
    df_csv.to_csv(caminho_salvar, index=False, encoding='utf-8')
    print(f"[CONCLUÍDO] Salvo em: {caminho_salvar}\n")

# Variável global do arquivo de perguntas
ARQUIVO_TXT = "dados_entrada/questions_PDS_final.txt"

Corrigir o DeepSeek (Modo Bruto):

In [ ]:
#corrigir_cirurgico(
#    caminho_csv="resultados_brutos/geracao_bruto_deepseek-v4-pro_pergunta_pt_pergunta_en_COMPLETO.csv",
#    caminho_txt=ARQUIVO_TXT,
#    indices=[30],
#    modelo="deepseek-v4-pro",
#    tipo_teste="bruto"
#)

[INICIANDO CORREÇÃO] BRUTO | Modelo: deepseek-v4-pro | 1 linhas

2026-05-22 21:47:44,077 - INFO - Aquecendo o modelo deepseek-v4-pro (Cold Start)...

[DEBUG] Enviando para API: seed=42, temp=0.0

2026-05-22 21:47:46,903 - INFO - HTTP Request: POST https://api.deepseek.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-22 21:47:48,049 - INFO - Aquecimento concluído. Prontos para as requisições.

 -> Re-inferindo índice 30 (PT)...
[DEBUG] Enviando para API: seed=42, temp=0.0

2026-05-22 21:47:48,547 - INFO - HTTP Request: POST https://api.deepseek.com/v1/chat/completions "HTTP/1.1 200 OK"

[CONCLUÍDO] Salvo em: resultados_brutos/geracao_bruto_deepseek-v4-pro_pergunta_pt_pergunta_en_COMPLETO_CORRIGIDO.csv

Avaliando:

In [3]:
df_bruto_deepseek_v4_pro_corrigido = "resultados_brutos/geracao_bruto_deepseek-v4-pro_pergunta_pt_pergunta_en_COMPLETO.csv"

# Deixar o pandas detectar automaticamente o delimitador
df_bruto_deepseek_v4_pro_corrigido = pd.read_csv(df_bruto_deepseek_v4_pro_corrigido)

df_bruto_deepseek_v4_pro_corrigido[['Idioma', 'Modelo', 'Resposta_Gerada']]

    Idioma           Modelo                                    Resposta_Gerada
0       PT  deepseek-v4-pro  a) Para o sinal de tempo contínuo \( x(t) \):\...
1       PT  deepseek-v4-pro  a) A taxa de bits é dada pelo produto do númer...
2       PT  deepseek-v4-pro  **a) Valores das quatro primeiras amostras (ap...
3       PT  deepseek-v4-pro  **a) Expressão analítica de \(x(t)\)**  \nComo...
4       PT  deepseek-v4-pro  **a) ADC com complemento de dois (b=8 bits, Δ=...
5       PT  deepseek-v4-pro  **Período de 6 amostras (n = 0 a 5):**\n\n| n ...
6       PT  deepseek-v4-pro  **a) Projeto do quantizador escalar uniforme d...
7       PT  deepseek-v4-pro  Para quantização uniforme, assume-se que o err...
8       PT  deepseek-v4-pro  A adoção do CAG com 4 bits adicionais do ganho...
9       PT  deepseek-v4-pro  a) **Média e variância do erro de quantização*...
10      PT  deepseek-v4-pro  Não, $x[n]$ não pode ser um sinal ímpar (odd)....
11      PT  deepseek-v4-pro  a) **Sinal:** \(x(t) = 5 \cos(2 \pi \cdot 300 ...
12      PT  deepseek-v4-pro  Sobre a **energia total** e a **potência média...
13      PT  deepseek-v4-pro  **a)** Considerando que os valores de tensão s...
14      PT  deepseek-v4-pro  a) Periódico, \(N_0 = 1\)  \nb) Periódico, \(N...
15      PT  deepseek-v4-pro  **Vetores:**  \n\(\mathbf{u} = [4, 3]\)  \n\(\...
16      PT  deepseek-v4-pro  As projeções e os vetores de erro são:\n\n- **...
17      PT  deepseek-v4-pro  **Resposta:**\n\n1. **A matriz \(A\) não é uni...
18      PT  deepseek-v4-pro  Para encontrar os coeficientes \(\alpha\) e \(...
19      PT  deepseek-v4-pro  **Resposta:**\n\nO conjunto \( \mathcal{C} = \...
20      PT  deepseek-v4-pro  Para uma DFT ortonormal de 3 pontos, a matriz ...
21      PT  deepseek-v4-pro  **Inverso \(\mathbf{x}\):**\nA DFT ortonormal ...
22      PT  deepseek-v4-pro  Vamos derivar o par de equações da série de Fo...
23      PT  deepseek-v4-pro  Os coeficientes da série de Fourier (na forma ...
24      PT  deepseek-v4-pro  A expressão do sinal \(x(t)\) é dada pela séri...
25      PT  deepseek-v4-pro  A transformada de Fourier considerada aqui é d...
26      PT  deepseek-v4-pro                 ERRO: The read operation timed out
27      PT  deepseek-v4-pro  A DTFT de um sinal discreto \(x[n]\) é dada po...
28      PT  deepseek-v4-pro  Aqui estão as demonstrações para a DTFT e a Tr...
29      PT  deepseek-v4-pro  Para encontrar o sinal \(h[n]\) correspondente...
30      PT  deepseek-v4-pro  Para provar que a Transformada de Fourier de T...
31      PT  deepseek-v4-pro  a) \( X(2) = \frac{5}{2^2 + 2\cdot 2 + 10} = \...
32      PT  deepseek-v4-pro  Para encontrar o sinal \( x(t) \), seguimos os...
33      PT  deepseek-v4-pro  Para encontrar o sinal \( x[n] \) a partir da ...
34      PT  deepseek-v4-pro  A transformada Z do sinal \( x[n] = -3^n u[-n-...
35      PT  deepseek-v4-pro  A transformada Z do sinal é:\n\[ X(z) = 4 + 5z...
36      PT  deepseek-v4-pro  A saída para a entrada \(x_2[n] = 3x_1[n]\) é ...
37      PT  deepseek-v4-pro  A saída \( y_2[n] \) é:\n\n\[\ny_2[n] = 15\del...
38      PT  deepseek-v4-pro  Não, esse sistema não pode ser linear e invari...
39      PT  deepseek-v4-pro  A saída do sistema para a entrada \(x_2(t) = \...
40      PT  deepseek-v4-pro  **Sistema 1:** \(y[n] = C (x[n])^2\), com \(C ...
41      PT  deepseek-v4-pro  Para que o sistema seja causal, a saída \(y[n]...
42      PT  deepseek-v4-pro  As entradas são exponenciais complexas e senoi...
43      PT  deepseek-v4-pro  As entradas são sinais exponenciais complexos ...
44      PT  deepseek-v4-pro  A expressão exata de \(x(t)\) pode ser obtida ...
45      PT  deepseek-v4-pro  A saída do filtro é a soma das componentes de ...
46      PT  deepseek-v4-pro  A função do sistema \( H(z) \) é a transformad...
47      PT  deepseek-v4-pro  Para obter o filtro \( G(s) \) escalado em fre...
48      PT  deepseek-v4-pro  Para encontrar \( H(z) \) a partir de \( H(s) ...
49      PT  deepseek-v4-pro  **a) Frequência de amostragem \(f_s\) sem pré-...
50      PT  deepseek-v4-pro  Vamos analisar as respostas em frequência e no...
51      PT  deepseek-v4-pro  Para o sinal janelado \(x_w[n] = A \cos(\omega...
52      PT  deepseek-v4-pro  a) A energia total do sinal é \(E = 24\) joule...
53      PT  deepseek-v4-pro  O sinal \(x[n] = 3 \cos((\pi/4) n)\) é periódi...
54      PT  deepseek-v4-pro  a) O espectro estimado MS (Mean Square), ou pe...
55      PT  deepseek-v4-pro  **a) DTFS (coeficientes da Série de Fourier de...
56      PT  deepseek-v4-pro  a) A densidade espectral de potência (PSD) do ...
57      PT  deepseek-v4-pro  a) A potência média senoidal é obtida subtrain...
58      PT  deepseek-v4-pro  A potência média do sinal de saída do filtro \...
59      PT  deepseek-v4-pro  Sim, um processo aleatório em tempo discreto p...
60      EN  deepseek-v4-pro  a) For the continuous-time signal \(x(t)\):\n-...
61      EN  deepseek-v4-pro  **a) Bit rate**  \nBit rate = bits per sample ...
62      EN  deepseek-v4-pro  **a) First four samples (without quantization)...
63      EN  deepseek-v4-pro  a) Since the sampling period is \(T_s = 2\) s ...
64      EN  deepseek-v4-pro  **Part (a): Two’s complement ADC (b = 8 bits, ...
65      EN  deepseek-v4-pro  The original sinusoid is \(x[n] = \sin\left(\f...
66      EN  deepseek-v4-pro  **a) 3-bit quantizer design**\n\nSince the inp...
67      EN  deepseek-v4-pro  **Quantization SNR for a Sinusoid**\n\nAssume ...
68      EN  deepseek-v4-pro  The addition of a 4-bit programmable gain AGC ...
69      EN  deepseek-v4-pro  a) Under the linear quantization model, the qu...
70      EN  deepseek-v4-pro  No, \( x[n] \) cannot be an odd signal. By def...
71      EN  deepseek-v4-pro  **a) \( x(t) = 5 \cos(2\pi \cdot 300\,t + \pi/...
72      EN  deepseek-v4-pro  For any non-zero periodic signal that extends ...
73      EN  deepseek-v4-pro  **a) Average energy**  \nThe set \(\mathcal{M}...
74      EN  deepseek-v4-pro  For each signal, periodicity in discrete time ...
75      EN  deepseek-v4-pro  The norms, inner product, and angle between th...
76      EN  deepseek-v4-pro  The projections and error vectors are computed...
77      EN  deepseek-v4-pro  **1. Is \(\bA\) unitary?**\nNo, \(\bA\) is not...
78      EN  deepseek-v4-pro  The coefficients are \(\alpha = 2\) and \(\bet...
79      EN  deepseek-v4-pro  **Step 1: Identify a linearly independent subs...
80      EN  deepseek-v4-pro  The forward and inverse matrices for a 3-point...
81      EN  deepseek-v4-pro  The inverse 4-point orthonormal DFT of \(\bX =...
82      EN  deepseek-v4-pro  To derive the Fourier series pair, we start wi...
83      EN  deepseek-v4-pro  The signal is \( x(t) = 2 + 3 \cos(2\pi 100 t)...
84      EN  deepseek-v4-pro  The signal \(x(t)\) can be reconstructed from ...
85      EN  deepseek-v4-pro  The Fourier transform is defined as:\n\[\nX(f)...
86      EN  deepseek-v4-pro  Assuming the normalized sinc function \(\opera...
87      EN  deepseek-v4-pro  **a) Discrete-Time Fourier Transform (DTFT)**\...
88      EN  deepseek-v4-pro  **a) Discrete-Time Fourier Transform (DTFT)**\...
89      EN  deepseek-v4-pro  The inverse DTFT of an ideal low-pass filter i...
90      EN  deepseek-v4-pro  The given \(X(e^{j\omega})\) is the Discrete-T...
91      EN  deepseek-v4-pro  **a)** Evaluate \(X(s)\) at \(s=2\):  \nSince ...
92      EN  deepseek-v4-pro  The signal \(x(t)\) is obtained by taking the ...
93      EN  deepseek-v4-pro  The inverse Z-transform of \( X(z) = \frac{5z^...
94      EN  deepseek-v4-pro  The Z-transform of the signal \(x[n] = -3^n u[...
95      EN  deepseek-v4-pro  The Z-transform of \(x[n] = 4\delta[n] + 5\del...
96      EN  deepseek-v4-pro  The system is linear, meaning it satisfies the...
97      EN  deepseek-v4-pro  The output of an LTI system is the convolution...
98      EN  deepseek-v4-pro  No, this system cannot be LTI. For a linear ti...
99      EN  deepseek-v4-pro  For a time-invariant system, a delay in the in...
100     EN  deepseek-v4-pro  Here is the classification of each system:\n\n...
101     EN  deepseek-v4-pro  A causal LTI system requires that the output \...
102     EN  deepseek-v4-pro  The outputs of the causal system \(H(s) = \fra...
103     EN  deepseek-v4-pro  The system is LTI with transfer function \(H(z...
104     EN  deepseek-v4-pro  The original band-limited signal \(x(t)\) can ...
105     EN  deepseek-v4-pro  The filter is an ideal lowpass filter that pas...
106     EN  deepseek-v4-pro  The system function \(H(z)\) is the Z-transfor...
107     EN  deepseek-v4-pro  To scale the filter in frequency and adjust th...
108     EN  deepseek-v4-pro  The bilinear transform maps the continuous-tim...
109     EN  deepseek-v4-pro  (a) The bilinear transform maps frequencies ac...
110     EN  deepseek-v4-pro  When designing filters—whether for audio proce...
111     EN  deepseek-v4-pro  **Part (a):** \(\omega_1 = 3\Delta\omega = 3\p...
112     EN  deepseek-v4-pro  a) Total signal energy: 24 Joules (or \(\text{...
113     EN  deepseek-v4-pro  The "MS spectrum" (mean-square spectrum) \(\ha...
114     EN  deepseek-v4-pro  a) The estimated mean-square (MS) spectrum for...
115     EN  deepseek-v4-pro  **a) DTFS (Discrete-Time Fourier Series) coeff...
116     EN  deepseek-v4-pro  a) The power spectral density (PSD) of the win...
117     EN  deepseek-v4-pro  a) The sinusoid average power is 500 W.  \nb) ...
118     EN  deepseek-v4-pro  The average power \( \mathcal{P} \) is 7200 W....
119     EN  deepseek-v4-pro  **Yes**, a discrete-time random process can ha...

In [4]:
df_bruto_deepseek_v4_pro_corrigido.iloc[30]

Idioma                                                                PT
Interferencia_Tutor                                                  NÃO
Capitulo                         2. Transforms and Signal Representation
Num_Questao                                                         21.0
Pergunta               Prove isso $X(e^{j \dw})=\sum_{k=-\infty}^{\in...
Modelo                                                   deepseek-v4-pro
Resposta_Gerada        Para provar que a Transformada de Fourier de T...
Latencia_Total_s                                                 35.6111
TTFT_s                                                         23.706534
ITL_s                                                          11.904593
Throughput_tps                                                    168.25
Tokens_In                                                             80
Tokens_Out                                                          2003
Tokens_Total                                                        2083
Name: 30, dtype: object

Corrigir o Ministral (Modo Tutor)

In [ ]:
#corrigir_cirurgico(
#    caminho_csv="resultados_brutos/geracao_tutor_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_pergunta_en_COMPLETO.csv",
#    caminho_txt=ARQUIVO_TXT,
#    indices=[27, 28, 30, 45, 50],
#    modelo="cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit",
#    tipo_teste="tutor"
#)

2026-05-22 22:18:48,016 - INFO - Aquecendo o Tutor Inteligente...

[INICIANDO CORREÇÃO] TUTOR | Modelo: cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit | 5 linhas

2026-05-22 22:19:27,985 - INFO - Aquecimento do Tutor concluído.

 -> Re-inferindo índice 27 (PT)...
 -> Re-inferindo índice 28 (PT)...
 -> Re-inferindo índice 30 (PT)...
 -> Re-inferindo índice 45 (PT)...
 -> Re-inferindo índice 50 (PT)...
[CONCLUÍDO] Salvo em: resultados_brutos/geracao_tutor_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_pergunta_en_COMPLETO_CORRIGIDO.csv

Avaliando:

In [ ]:
df_tutor_Ministral_3_8B_corrigido = "resultados_brutos/geracao_tutor_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_pergunta_en_COMPLETO.csv"

# Deixar o pandas detectar automaticamente o delimitador
df_tutor_Ministral_3_8B_corrigido = pd.read_csv(df_tutor_Ministral_3_8B_corrigido)

df_tutor_Ministral_3_8B_corrigido[['Idioma', 'Modelo', 'Resposta_Gerada']]

,Idioma,Modelo,Resposta_Gerada
0,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nVamos anali...
1,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\na) A taxa d...
2,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\n### a) Valo...
3,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\n**a) Expres...
4,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nO problema ...
5,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nVamos resol...
6,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara projet...
7,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
8,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nA melhoria ...
9,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\n---\n**a) M...
10,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"A resposta para sua pergunta é: Sim, o sinal $..."
11,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nVamos anali...
12,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara sinais...
13,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\na) A energi...
14,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nVamos anali...
15,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nDados os ve...
16,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
17,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara verifi...
18,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
19,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
20,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara uma **...
21,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
22,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara deriva...
23,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
24,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nA expressão...
25,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
26,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
27,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara provar...
28,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara provar...
29,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
30,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara provar...
31,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nVamos resol...
32,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
33,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
34,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nA transform...
35,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
36,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
37,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
38,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"A resposta para sua pergunta é: **Sim**, o sis..."
39,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nDado que o ...
40,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nAnalisaremo...
41,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara que o ...
42,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
43,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
44,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nA expressão...
45,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nA saída do ...
46,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nA função do...
47,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara obter ...
48,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
49,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
50,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nA comparaçã...
51,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nVamos resol...
52,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
53,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara encont...
54,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
55,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
56,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
57,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
58,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara resolv...
59,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"A resposta para sua pergunta é: Não, um proces..."
60,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n### Part (a...
61,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n**a) B...
62,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
63,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
64,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nBelow is a ...
65,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
66,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
67,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n### Quantiz...
68,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe expecte...
69,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
70,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"The answer to your question is: No, the signal..."
71,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
72,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nFor any per...
73,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n**a)...
74,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
75,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nGiven the v...
76,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
77,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo determin...
78,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
79,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nBelow is a ...
80,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe forward...
81,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nGiven the 4...
82,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo derive t...
83,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
84,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
85,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe Fourier...
86,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
87,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
88,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
89,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
90,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo prove th...
91,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
92,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
93,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
94,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
95,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
96,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo solve th...
97,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nGiven the i...
98,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is: To determine i...
99,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nGiven that ...
100,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nBelow is th...
101,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo determin...
102,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe problem...
103,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo determin...
104,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe sampled...
105,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo solve th...
106,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe system ...
107,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo obtain t...
108,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find $H(...
109,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
110,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe compari...
111,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo solve th...
112,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo solve th...
113,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
114,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...
115,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nGiven the 4...
116,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n### Part (a...
117,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThis proble...
118,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...
119,EN,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nA discrete-...

In [9]:
df_tutor_Ministral_3_8B_corrigido.iloc[[27, 28, 30, 45, 50]][['Idioma', 'Modelo', 'Resposta_Gerada']]

,Idioma,Modelo,Resposta_Gerada
27,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara provar...
28,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara provar...
30,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nPara provar...
45,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nA saída do ...
50,PT,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,A resposta para sua pergunta é:\n\nA comparaçã...

Corrigir o GPT-5 (Modo Tutor):

In [ ]:
#corrigir_cirurgico(
#    caminho_csv="resultados_brutos/geracao_tutor_gpt-5_pergunta_pt_pergunta_en_COMPLETO.csv",
#    caminho_txt=ARQUIVO_TXT,
#    indices=[10, 66, 74, 82, 87, 93, 110],
#    modelo="gpt-5",
#    tipo_teste="tutor"
#)

2026-05-22 22:27:58,869 - INFO - Aquecendo o Tutor Inteligente...

[INICIANDO CORREÇÃO] TUTOR | Modelo: gpt-5 | 7 linhas

2026-05-22 22:29:10,309 - INFO - Aquecimento do Tutor concluído.

 -> Re-inferindo índice 10 (PT)...
 -> Re-inferindo índice 66 (EN)...
 -> Re-inferindo índice 74 (EN)...
 -> Re-inferindo índice 82 (EN)...
 -> Re-inferindo índice 87 (EN)...
 -> Re-inferindo índice 93 (EN)...
 -> Re-inferindo índice 110 (EN)...
[CONCLUÍDO] Salvo em: resultados_brutos/geracao_tutor_gpt-5_pergunta_pt_pergunta_en_COMPLETO_CORRIGIDO.csv

Avaliando:

In [11]:
df_tutor_gpt_5_corrigido = "resultados_brutos/geracao_tutor_gpt-5_pergunta_pt_pergunta_en_COMPLETO_CORRIGIDO.csv"

# Deixar o pandas detectar automaticamente o delimitador
df_tutor_gpt_5_corrigido = pd.read_csv(df_tutor_gpt_5_corrigido)

df_tutor_gpt_5_corrigido[['Idioma', 'Modelo', 'Resposta_Gerada']]

    Idioma Modelo                                    Resposta_Gerada
0       PT  gpt-5  A resposta para sua pergunta é:\na) Para o sin...
1       PT  gpt-5  A resposta para sua pergunta é:\na) A taxa de ...
2       PT  gpt-5  A resposta para sua pergunta é:\na) Amostragem...
3       PT  gpt-5  A resposta para sua pergunta é:\na) Pelo model...
4       PT  gpt-5  A resposta para sua pergunta é:\nVamos assumir...
5       PT  gpt-5  A resposta para sua pergunta é:\n- Período fun...
6       PT  gpt-5  A resposta para sua pergunta é:\na) Projeto do...
7       PT  gpt-5  A resposta para sua pergunta é:\nUsando o mode...
8       PT  gpt-5  A resposta para sua pergunta é: aproximadament...
9       PT  gpt-5  A resposta para sua pergunta é:\na) Pelo model...
10      PT  gpt-5  A resposta para sua pergunta é: Não. Um sinal ...
11      PT  gpt-5  A resposta para sua pergunta é:\n- a) Para $x(...
12      PT  gpt-5  A resposta para sua pergunta é: todo sinal per...
13      PT  gpt-5  A resposta para sua pergunta é:\na) Como todos...
14      PT  gpt-5  A resposta para sua pergunta é:\n- a) Não peri...
15      PT  gpt-5  A resposta para sua pergunta é:\n- Normas (L2)...
16      PT  gpt-5  A resposta para sua pergunta é:\n- Produto int...
17      PT  gpt-5  A resposta para sua pergunta é:\n- Como verifi...
18      PT  gpt-5  A resposta para sua pergunta é:\nComo a base é...
19      PT  gpt-5  A resposta para sua pergunta é:\nAplicando Gra...
20      PT  gpt-5  A resposta para sua pergunta é:\nPara a DFT or...
21      PT  gpt-5  A resposta para sua pergunta é:\n- Inverso da ...
22      PT  gpt-5  A resposta para sua pergunta é:\nDerivação usa...
23      PT  gpt-5  A resposta para sua pergunta é:\nComo o proble...
24      PT  gpt-5  A resposta para sua pergunta é:\nA expressão $...
25      PT  gpt-5  A resposta para sua pergunta é:\nComo método, ...
26      PT  gpt-5  A resposta para sua pergunta é:\nComo este é e...
27      PT  gpt-5  A resposta para sua pergunta é:\n\na) DTFT de ...
28      PT  gpt-5  A resposta para sua pergunta é:\na) DTFT de x[...
29      PT  gpt-5  A resposta para sua pergunta é:\nVamos determi...
30      PT  gpt-5  A resposta para sua pergunta é:\nProva usando ...
31      PT  gpt-5  A resposta para sua pergunta é:\n- a) Avaliand...
32      PT  gpt-5  A resposta para sua pergunta é:\nComo os polos...
33      PT  gpt-5  A resposta para sua pergunta é:\nComo a ROC é ...
34      PT  gpt-5  A resposta para sua pergunta é:\n- Transformad...
35      PT  gpt-5  A resposta para sua pergunta é:\n- Pela defini...
36      PT  gpt-5  A resposta para sua pergunta é:\nComo o sistem...
37      PT  gpt-5  A resposta para sua pergunta é:\nComo o sistem...
38      PT  gpt-5  A resposta para sua pergunta é: Não. Esse sist...
39      PT  gpt-5  A resposta para sua pergunta é:\nComo o sistem...
40      PT  gpt-5  A resposta para sua pergunta é:\nClassificação...
41      PT  gpt-5  A resposta para sua pergunta é: escolha, por e...
42      PT  gpt-5  A resposta para sua pergunta é:\nComo se trata...
43      PT  gpt-5  A resposta para sua pergunta é:\nComo cada um ...
44      PT  gpt-5  A resposta para sua pergunta é:\nComo $\fs=10$...
45      PT  gpt-5  A resposta para sua pergunta é:\nMétodo para o...
46      PT  gpt-5  A resposta para sua pergunta é:\nComo se trata...
47      PT  gpt-5  A resposta para sua pergunta é:\n- Para mudar ...
48      PT  gpt-5  A resposta para sua pergunta é:\nUsando a tran...
49      PT  gpt-5  A resposta para sua pergunta é:\n- a) Escolhen...
50      PT  gpt-5  A resposta para sua pergunta é:\n- Bessel\n  -...
51      PT  gpt-5  A resposta para sua pergunta é:\n- Usando o DT...
52      PT  gpt-5  A resposta para sua pergunta é:\nComo foco no ...
53      PT  gpt-5  A resposta para sua pergunta é:\n- Passo 1 (pe...
54      PT  gpt-5  A resposta para sua pergunta é:\n- a) Usando a...
55      PT  gpt-5  A resposta para sua pergunta é:\nComo você for...
56      PT  gpt-5  A resposta para sua pergunta é:\n\na) Após mul...
57      PT  gpt-5  A resposta para sua pergunta é:\nComo se trata...
58      PT  gpt-5  A resposta para sua pergunta é:\na) Como o ruí...
59      PT  gpt-5  A resposta para sua pergunta é:\n- Sim, um pro...
60      EN  gpt-5  The answer to your question is:\na) Continuous...
61      EN  gpt-5  The answer to your question is:\na) Bit rate: ...
62      EN  gpt-5  The answer to your question is:\na) Sampling o...
63      EN  gpt-5  The answer to your question is:\na) By definit...
64      EN  gpt-5  The answer to your question is:\na) Two’s comp...
65      EN  gpt-5  The answer to your question is:\n- One period ...
66      EN  gpt-5  The answer to your question is:\na) 3-bit unif...
67      EN  gpt-5  The answer to your question is:\n- Under the u...
68      EN  gpt-5  The answer to your question is:\nUsing the rul...
69      EN  gpt-5  The answer to your question is:\nBecause this ...
70      EN  gpt-5  The answer to your question is:\nThink through...
71      EN  gpt-5  The answer to your question is:\na) x(t) = 5 c...
72      EN  gpt-5  The answer to your question is:\n- Any nonzero...
73      EN  gpt-5  The answer to your question is:\na) Average en...
74      EN  gpt-5  The answer to your question is:\n- a) x[n] = u...
75      EN  gpt-5  The answer to your question is:\n- Norms (L2):...
76      EN  gpt-5  The answer to your question is:\nBecause proje...
77      EN  gpt-5  The answer to your question is:\n- The matrix ...
78      EN  gpt-5  The answer to your question is:\nGiven $\overl...
79      EN  gpt-5  The answer to your question is:\nI did not fin...
80      EN  gpt-5  The answer to your question is:\nFor the 3-poi...
81      EN  gpt-5  The answer to your question is:\n- Inverse (un...
82      EN  gpt-5  The answer to your question is:\n- Setup and b...
83      EN  gpt-5  The answer to your question is:\nSince the sig...
84      EN  gpt-5  The answer to your question is:\nBecause you a...
85      EN  gpt-5  The answer to your question is:\nBecause this ...
86      EN  gpt-5  The answer to your question is:\nSince this is...
87      EN  gpt-5  The answer to your question is:\na) DTFT of x[...
88      EN  gpt-5  The answer to your question is:\na) DTFT of x[...
89      EN  gpt-5  The answer to your question is:\nWe denote the...
90      EN  gpt-5  The answer to your question is:\nWe use the DT...
91      EN  gpt-5  The answer to your question is:\n- Given a rig...
92      EN  gpt-5  The answer to your question is:\nGiven $X(s)=\...
93      EN  gpt-5  The answer to your question is:\nBecause the R...
94      EN  gpt-5  The answer to your question is:\n- Z transform...
95      EN  gpt-5  The answer to your question is:\n- Z-transform...
96      EN  gpt-5  The answer to your question is:\nBecause the s...
97      EN  gpt-5  The answer to your question is:\nGiven that th...
98      EN  gpt-5  The answer to your question is: No, this syste...
99      EN  gpt-5  The answer to your question is: \nUsing time-i...
100     EN  gpt-5  The answer to your question is:\n- System 1: $...
101     EN  gpt-5  The answer to your question is: any integer va...
102     EN  gpt-5  The answer to your question is:\nBecause compl...
103     EN  gpt-5  The answer to your question is:\nBecause discr...
104     EN  gpt-5  The answer to your question is:\nSince the sam...
105     EN  gpt-5  The answer to your question is:\nBecause the s...
106     EN  gpt-5  The answer to your question is:\nGiven the FIR...
107     EN  gpt-5  The answer to your question is:\nUsing frequen...
108     EN  gpt-5  The answer to your question is:\nUsing the bil...
109     EN  gpt-5  The answer to your question is:\na) Use the “s...
110     EN  gpt-5  The answer to your question is:\n- Bessel\n  -...
111     EN  gpt-5  The answer to your question is:\nUsing the DTF...
112     EN  gpt-5  The answer to your question is:\nBecause your ...
113     EN  gpt-5  The answer to your question is:\nMethod (do no...
114     EN  gpt-5  The answer to your question is:\n- Definitions...
115     EN  gpt-5  The answer to your question is:\n- Assumptions...
116     EN  gpt-5  The answer to your question is:\na) Method to ...
117     EN  gpt-5  The answer to your question is:\na) Sinusoid a...
118     EN  gpt-5  The answer to your question is:\na) The averag...
119     EN  gpt-5  The answer to your question is:\n- For the dis...

In [12]:
# erros de requisição
df_tutor_gpt_5_corrigido.iloc[[10, 66, 93]][['Idioma', 'Modelo', 'Resposta_Gerada']]

   Idioma Modelo                                    Resposta_Gerada
10     PT  gpt-5  A resposta para sua pergunta é: Não. Um sinal ...
66     EN  gpt-5  The answer to your question is:\na) 3-bit unif...
93     EN  gpt-5  The answer to your question is:\nBecause the R...

In [13]:
df_tutor_gpt_5_corrigido.at[10, 'Resposta_Gerada']

'A resposta para sua pergunta é: Não. Um sinal ímpar (odd) satisfaz a simetria $x[-n] = -x[n]$. O livro explicita essa propriedade para o componente ímpar $x_o[n]$, afirmando $x_o[n] = -x_o[-n]$. Tomando $n=0$, segue $x[0] = -x[0] \\Rightarrow x[0]=0$. Como foi dado $x[0]=3 \\ne 0$, $x[n]$ não pode ser um sinal ímpar.\n\nPara aprofundar seus conhecimentos consulte a seguinte referência:\nLivro: ak_dsp_book | Capítulo: Analog and Digital Signals | Seção: Signal Categorization | Página: 25–26'

In [14]:
# erros de tradução
df_tutor_gpt_5_corrigido.iloc[[74, 82, 87, 110]][['Idioma', 'Modelo', 'Resposta_Gerada']]

    Idioma Modelo                                    Resposta_Gerada
74      EN  gpt-5  The answer to your question is:\n- a) x[n] = u...
82      EN  gpt-5  The answer to your question is:\n- Setup and b...
87      EN  gpt-5  The answer to your question is:\na) DTFT of x[...
110     EN  gpt-5  The answer to your question is:\n- Bessel\n  -...

Corrigir o DeepSeek V4 Pro (Modo Tutor):

In [34]:
erros_deepseek = [9, 69]

corrigir_cirurgico(
    caminho_csv="resultados_brutos/geracao_tutor_deepseek-v4-pro_pergunta_pt_pergunta_en_COMPLETO.csv",
    caminho_txt=ARQUIVO_TXT,
    indices=erros_deepseek,
    modelo="deepseek-v4-pro",
    tipo_teste="tutor"
)

2026-05-23 00:35:48,913 - INFO - Aquecendo o Tutor Inteligente...

[INICIANDO CORREÇÃO] TUTOR | Modelo: deepseek-v4-pro | 2 linhas

2026-05-23 00:36:33,420 - INFO - Aquecimento do Tutor concluído.

 -> Re-inferindo índice 9 (PT)...
 -> Re-inferindo índice 69 (EN)...
[CONCLUÍDO] Salvo em: resultados_brutos/geracao_tutor_deepseek-v4-pro_pergunta_pt_pergunta_en_COMPLETO_CORRIGIDO.csv

In [ ]:
df_tutor_deepseek_v4_pro_corrigido = "resultados_brutos/geracao_tutor_deepseek-v4-pro_pergunta_pt_pergunta_en_COMPLETO_CORRIGIDO.csv"

# Deixar o pandas detectar automaticamente o delimitador
df_tutor_deepseek_v4_pro_corrigido = pd.read_csv(df_tutor_deepseek_v4_pro_corrigido)

df_tutor_deepseek_v4_pro_corrigido[['Idioma', 'Modelo', 'Resposta_Gerada']]

    Idioma           Modelo                                    Resposta_Gerada
0       PT  deepseek-v4-pro  A resposta para sua pergunta é: \n\n**a) Sinal...
1       PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\na) A taxa d...
2       PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\n**a) Valore...
3       PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\n**a) Expres...
4       PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nA quantizaç...
5       PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nDada a sinu...
6       PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\na) Como o s...
7       PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara encont...
8       PT  deepseek-v4-pro  A resposta para sua pergunta é: a melhoria esp...
9       PT  deepseek-v4-pro                                                NaN
10      PT  deepseek-v4-pro  A resposta para sua pergunta é: Não, $x[n]$ nã...
11      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara os sin...
12      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nSinais peri...
13      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\n**a) Energi...
14      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\na) $x[n] = ...
15      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nDado os vet...
16      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nAs projeçõe...
17      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nA matriz $\...
18      PT  deepseek-v4-pro  A resposta para sua pergunta é: α = 2 e β = -1...
19      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara resolv...
20      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara obter ...
21      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\n1. **Cálcul...
22      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nA derivação...
23      PT  deepseek-v4-pro  A resposta para sua pergunta é: para obter os ...
24      PT  deepseek-v4-pro  A resposta para sua pergunta é: a expressão $x...
25      PT  deepseek-v4-pro  A resposta para sua pergunta é: para encontrar...
26      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara determ...
27      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\n**a) DTFT d...
28      PT  deepseek-v4-pro  A resposta para sua pergunta é: O contexto for...
29      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara encont...
30      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara provar...
31      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\n**a)** Para...
32      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\n$$\nx(t) = ...
33      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara encont...
34      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nA transform...
35      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara determ...
36      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nComo o sist...
37      PT  deepseek-v4-pro  A resposta para sua pergunta é:  \nPara encont...
38      PT  deepseek-v4-pro  A resposta para sua pergunta é: **Não, esse si...
39      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nA saída do ...
40      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nOs sistemas...
41      PT  deepseek-v4-pro  A resposta para sua pergunta é: um valor possí...
42      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara resolv...
43      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara determ...
44      PT  deepseek-v4-pro  A resposta para sua pergunta é:  \n$$\nx(t) = ...
45      PT  deepseek-v4-pro  A resposta para sua pergunta é:  \nO problema ...
46      PT  deepseek-v4-pro  A resposta para sua pergunta é:  \nA função do...
47      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara escala...
48      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara encont...
49      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\n### a) Enco...
50      PT  deepseek-v4-pro  A resposta para sua pergunta é:  \n\nAs aproxi...
51      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nUsando a ex...
52      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPrimeiramen...
53      PT  deepseek-v4-pro  A resposta para sua pergunta é:  \nO espectro ...
54      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\na) O espect...
55      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara resolv...
56      PT  deepseek-v4-pro  A resposta para sua pergunta é: este exercício...
57      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nPara resolv...
58      PT  deepseek-v4-pro  A resposta para sua pergunta é: $\calP = 7200$...
59      PT  deepseek-v4-pro  A resposta para sua pergunta é: Sim, um proces...
60      EN  deepseek-v4-pro  The answer to your question is: This is exerci...
61      EN  deepseek-v4-pro  The answer to your question is:\n\n**a) Bit ra...
62      EN  deepseek-v4-pro  The answer to your question is:\n\n**a) First ...
63      EN  deepseek-v4-pro  The answer to your question is:\n\na) Given th...
64      EN  deepseek-v4-pro  The answer to your question is:\n\nThe exercis...
65      EN  deepseek-v4-pro  The answer to your question is:\n\nFor the dis...
66      EN  deepseek-v4-pro  The answer to your question is:\n\nTo design a...
67      EN  deepseek-v4-pro  The answer to your question is:\n\nFor a full-...
68      EN  deepseek-v4-pro  The answer to your question is: The adoption o...
69      EN  deepseek-v4-pro                                                NaN
70      EN  deepseek-v4-pro  The answer to your question is: I could not fi...
71      EN  deepseek-v4-pro  The answer to your question is:\n\nFor the con...
72      EN  deepseek-v4-pro  The answer to your question is: for any period...
73      EN  deepseek-v4-pro  The answer to your question is:\n\na) The set ...
74      EN  deepseek-v4-pro  The answer to your question is:\n\nLet's analy...
75      EN  deepseek-v4-pro  The answer to your question is:\n\nFirst, let ...
76      EN  deepseek-v4-pro  The answer to your question is:\n\nGiven the v...
77      EN  deepseek-v4-pro  The answer to your question is:\n\n**No,** the...
78      EN  deepseek-v4-pro  The answer to your question is:  \nFor the non...
79      EN  deepseek-v4-pro  The answer to your question is:\n\nThe Gram-Sc...
80      EN  deepseek-v4-pro  The answer to your question is: For a 3-point ...
81      EN  deepseek-v4-pro  The answer to your question is:\n\nGiven the o...
82      EN  deepseek-v4-pro  The answer to your question is:\n\nTo derive t...
83      EN  deepseek-v4-pro  The answer to your question is:\n\nThe signal ...
84      EN  deepseek-v4-pro  The answer to your question is: using the Four...
85      EN  deepseek-v4-pro  The answer to your question is:  \nTo find the...
86      EN  deepseek-v4-pro  The answer to your question is:\n\na) For \(x(...
87      EN  deepseek-v4-pro  The answer to your question is:  \nThe given s...
88      EN  deepseek-v4-pro  The answer to your question is:\n\nWe are give...
89      EN  deepseek-v4-pro  The answer to your question is:\n\nThe inverse...
90      EN  deepseek-v4-pro  The answer to your question is:\n\nThe discret...
91      EN  deepseek-v4-pro  The answer to your question is:\n\nWe are give...
92      EN  deepseek-v4-pro  The answer to your question is:\n\nGiven \( X(...
93      EN  deepseek-v4-pro  The answer to your question is:\n\nThe inverse...
94      EN  deepseek-v4-pro  The answer to your question is:\n\nThe Z‑trans...
95      EN  deepseek-v4-pro  The answer to your question is:\n\nThe Z trans...
96      EN  deepseek-v4-pro  The answer to your question is: $y_2[n] = 12\,...
97      EN  deepseek-v4-pro  The answer to your question is: the output $y_...
98      EN  deepseek-v4-pro  The answer to your question is: No, this syste...
99      EN  deepseek-v4-pro  The answer to your question is: $y_2(t) = \del...
100     EN  deepseek-v4-pro  The answer to your question is:\n\n**System 1:...
101     EN  deepseek-v4-pro  The answer to your question is: **\(n_0 = 0\)*...
102     EN  deepseek-v4-pro  The answer to your question is:\n\nThe system ...
103     EN  deepseek-v4-pro  The answer to your question is:\n\nFor the cau...
104     EN  deepseek-v4-pro  The answer to your question is:\n\nGiven the s...
105     EN  deepseek-v4-pro  The answer to your question is: The filter has...
106     EN  deepseek-v4-pro  The answer to your question is:  \nThe system ...
107     EN  deepseek-v4-pro  The answer to your question is:\n\nThe desired...
108     EN  deepseek-v4-pro  The answer to your question is:\n\nUsing the b...
109     EN  deepseek-v4-pro  The answer to your question is:\n\n**a)** To d...
110     EN  deepseek-v4-pro  The answer to your question is:\n\nWhen design...
111     EN  deepseek-v4-pro  The answer to your question is: The solution t...
112     EN  deepseek-v4-pro  The answer to your question is:\n\nTo determin...
113     EN  deepseek-v4-pro  The answer to your question is: the MS spectru...
114     EN  deepseek-v4-pro  The answer to your question is:\n\na) The esti...
115     EN  deepseek-v4-pro  The answer to your question is:\n\nGiven $X[k]...
116     EN  deepseek-v4-pro  The answer to your question is provided as a s...
117     EN  deepseek-v4-pro  The answer to your question is:\n\na) **Sinuso...
118     EN  deepseek-v4-pro  The answer to your question is:\n\nThe average...
119     EN  deepseek-v4-pro  The answer to your question is: **Yes**, a dis...

In [32]:
# erros de requisição
df_tutor_deepseek_v4_pro_corrigido.iloc[[9, 51, 65, 69, 111]][['Idioma', 'Modelo', 'Resposta_Gerada']]

    Idioma           Modelo                                    Resposta_Gerada
9       PT  deepseek-v4-pro                                                NaN
51      PT  deepseek-v4-pro  A resposta para sua pergunta é:\n\nUsando a ex...
65      EN  deepseek-v4-pro  The answer to your question is:\n\nFor the dis...
69      EN  deepseek-v4-pro                                                NaN
111     EN  deepseek-v4-pro  The answer to your question is: The solution t...

In [29]:
# erros de linguagem
df_tutor_deepseek_v4_pro_corrigido.iloc[[62, 63, 64, 66, 70, 74, 76, 78, 79, 81, 82, 83, 86, 87, 88, 90, 93, 99, 107, 108, 118]][['Idioma', 'Modelo', 'Resposta_Gerada']]

    Idioma           Modelo                                    Resposta_Gerada
62      EN  deepseek-v4-pro  The answer to your question is:\n\n**a) First ...
63      EN  deepseek-v4-pro  The answer to your question is:\n\na) Given th...
64      EN  deepseek-v4-pro  The answer to your question is:\n\nThe exercis...
66      EN  deepseek-v4-pro  The answer to your question is:\n\nTo design a...
70      EN  deepseek-v4-pro  The answer to your question is: I could not fi...
74      EN  deepseek-v4-pro  The answer to your question is:\n\nLet's analy...
76      EN  deepseek-v4-pro  The answer to your question is:\n\nGiven the v...
78      EN  deepseek-v4-pro  The answer to your question is:  \nFor the non...
79      EN  deepseek-v4-pro  The answer to your question is:\n\nThe Gram-Sc...
81      EN  deepseek-v4-pro  The answer to your question is:\n\nGiven the o...
82      EN  deepseek-v4-pro  The answer to your question is:\n\nTo derive t...
83      EN  deepseek-v4-pro  The answer to your question is:\n\nThe signal ...
86      EN  deepseek-v4-pro  The answer to your question is:\n\na) For \(x(...
87      EN  deepseek-v4-pro  The answer to your question is:  \nThe given s...
88      EN  deepseek-v4-pro  The answer to your question is:\n\nWe are give...
90      EN  deepseek-v4-pro  The answer to your question is:\n\nThe discret...
93      EN  deepseek-v4-pro  The answer to your question is:\n\nThe inverse...
99      EN  deepseek-v4-pro  The answer to your question is: $y_2(t) = \del...
107     EN  deepseek-v4-pro  The answer to your question is:\n\nThe desired...
108     EN  deepseek-v4-pro  The answer to your question is:\n\nUsing the b...
118     EN  deepseek-v4-pro  The answer to your question is:\n\nThe average...

In [41]:
import pandas as pd
import csv
from gerador_respostas import BenchmarkRunner

# 1. Carrega o CSV que estava dando problema de NaN
caminho_csv = "resultados_brutos/geracao_tutor_deepseek-v4-pro_pergunta_pt_pergunta_en_COMPLETO_CORRIGIDO.csv"
df_csv = pd.read_csv(caminho_csv)
df_csv['Resposta_Gerada'] = df_csv['Resposta_Gerada'].fillna("") # Limpa os NaNs

# 2. Carrega as perguntas originais
df_txt = pd.read_csv("dados_entrada/questions_PDS_final.txt", sep='\t', quotechar='|', quoting=csv.QUOTE_NONNUMERIC, encoding='utf-8')

print("\n[INICIANDO BYPASS RAG] Forçando resposta via Conhecimento Interno do DeepSeek...")

# 3. Usamos o BenchmarkRunner (ignorando o RAG) mas fingindo ser o Tutor
runner = BenchmarkRunner(model_name="deepseek-v4-pro")
runner.run_warmup()

indices_teimosos = [9, 69]

for idx in indices_teimosos:
    idioma = df_csv.at[idx, 'Idioma']
    idx_txt = idx if idx < 60 else idx - 60 
    
    pergunta_base = df_txt.at[idx_txt, 'pergunta_pt'] if idioma == 'PT' else df_txt.at[idx_txt, 'pergunta_en']
    
    # 4. Injeção direta da Persona do Tutor no prompt do usuário
    if idioma == 'PT':
        prompt_bypass = "[SYSTEM RULE: Você é um Tutor Acadêmico. Responda EXCLUSIVAMENTE em Português. Inicie com 'A resposta para sua pergunta é:']\n\n" + pergunta_base
    else:
        prompt_bypass = "[SYSTEM RULE: You are an Academic Tutor. Answer EXCLUSIVELY in English. Start with 'The answer to your question is:']\n\n" + pergunta_base
        
    print(f" -> Extraindo resposta do índice {idx} ({idioma})...")
    
    # 5. Gera a resposta e métricas diretamente da API (sem o Qdrant atrapalhar)
    metrics = runner.generate_response(prompt_bypass)
    
    # 6. Salva as métricas
    df_csv.at[idx, 'Resposta_Gerada'] = metrics["Resposta_Gerada"]
    df_csv.at[idx, 'Latencia_Total_s'] = metrics["Latencia_Total_s"]
    df_csv.at[idx, 'TTFT_s'] = metrics["TTFT_s"]
    df_csv.at[idx, 'ITL_s'] = metrics["ITL_s"]
    df_csv.at[idx, 'Throughput_tps'] = metrics["Throughput"]
    df_csv.at[idx, 'Tokens_In'] = metrics["Tokens_In"]
    df_csv.at[idx, 'Tokens_Out'] = metrics["Tokens_Out"]
    df_csv.at[idx, 'Tokens_Total'] = metrics["Tokens_Total"]
    
    if len(metrics["Resposta_Gerada"]) > 10:
        print("    [SUCESSO] DeepSeek finalmente respondeu!")

# 7. Salva o arquivo FINAL
caminho_final = caminho_csv.replace(".csv", "_FINALIZADO.csv")
df_csv.to_csv(caminho_final, index=False, encoding='utf-8')
print(f"\n[CONCLUÍDO] Arquivo perfeito salvo em: {caminho_final}")

[INICIANDO BYPASS RAG] Forçando resposta via Conhecimento Interno do DeepSeek...

OpenAIError: Missing credentials. Please pass an `api_key`, `workload_identity`, `admin_api_key`, or set the `OPENAI_API_KEY` or `OPENAI_ADMIN_KEY` environment variable.