# **1 - Gerador de Respostas Versão 1**

Vamos testar as funções do documento `gerador_respostas.py` de onde são utilizadas as funções de experimento:

In [24]:
from gerador_respostas import process_dataset

In [25]:
process_dataset(
                input_txt='dados_entrada/questions_PDS_final test.txt',
                model_name='cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit',
                provider='vllm')

2026-05-19 13:03:54,245 - INFO - Carregando o dataset de perguntas...
2026-05-19 13:03:54,298 - INFO - Aquecendo o modelo cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit (Cold Start)...
2026-05-19 13:03:54,336 - INFO - HTTP Request: POST http://10.10.80.238:8006/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-19 13:03:54,337 - INFO - Aquecimento concluído. O modelo está pronto.
2026-05-19 13:03:54,339 - INFO - === INICIANDO BLOCO 1: PORTUGUÊS (60 Perguntas) ===
2026-05-19 13:03:54,340 - INFO - [PT] Processando Q1/60 | Cap: 1. Analog and Digital
2026-05-19 13:03:54,344 - INFO - HTTP Request: POST http://10.10.80.238:8006/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-19 13:03:59,797 - INFO - [PT] Processando Q2/60 | Cap: 1. Analog and Digital
2026-05-19 13:03:59,802 - INFO - HTTP Request: POST http://10.10.80.238:8006/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-19 13:04:04,522 - INFO - [PT] Processando Q3/60 | Cap: 1. Analog and Digital
2026-05-19 13:04:04,528 - INFO - HTTP Request: POST http://10.10.80.238:8006/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-19 13:04:23,594 - INFO - [PT] Processando Q4/60 | Cap: 1. Analog and Digital
2026-05-19 13:04:23,600 - INFO - HTTP Request: POST http://10.10.80.238:8006/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-19 13:04:34,358 - INFO - === INICIANDO BLOCO 2: INGLÊS (60 Perguntas) ===
2026-05-19 13:04:34,359 - INFO - [EN] Processando Q1/60 | Cap: 1. Analog and Digital
2026-05-19 13:04:34,364 - INFO - HTTP Request: POST http://10.10.80.238:8006/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-19 13:04:41,864 - INFO - [EN] Processando Q2/60 | Cap: 1. Analog and Digital
2026-05-19 13:04:41,869 - INFO - HTTP Request: POST http://10.10.80.238:8006/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-19 13:04:46,353 - INFO - [EN] Processando Q3/60 | Cap: 1. Analog and Digital
2026-05-19 13:04:46,358 - INFO - HTTP Request: POST http://10.10.80.238:8006/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-19 13:05:03,332 - INFO - [EN] Processando Q4/60 | Cap: 1. Analog and Digital
2026-05-19 13:05:03,339 - INFO - HTTP Request: POST http://10.10.80.238:8006/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-19 13:05:12,797 - INFO - Benchmark concluído com sucesso! Salvo em: resultados_brutos/geracao_cyankiwi_Ministral-3-3B-Instruct-2512-AWQ-8bit.csv

Vamos importar os datasets para comparar as respostas para identifar se a reprodutibilidade, via semente aleatória está sendo respeitada:

In [26]:
import pandas as pd

caminho_dataset1 = "resultados_brutos/geracao_cyankiwi_Ministral-3-3B-Instruct-2512-AWQ-8bit.csv"
caminho_dataset2 = "resultados_prontos/geracao_cyankiwi_Ministral-3-3B-Instruct-2512-AWQ-8bit.csv"

# Deixar o pandas detectar automaticamente o delimitador
df1 = pd.read_csv(caminho_dataset1)
df2 = pd.read_csv(caminho_dataset2)

In [4]:
df1

,Idioma,Capitulo,Num_Questao,Pergunta,Modelo,Resposta_Gerada,Latencia_Total_s,TTFT_s,ITL_s,Throughput_tps,Tokens_In,Tokens_Out,Tokens_Total
0,PT,1. Analog and Digital,1.0,Ambos em tempo contínuo $x(t)$ e o tempo discr...,cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit,Vamos resolver a questão passo a passo.\n\n###...,4.9746,0.0470,0.0073,136.98,132,676,808
1,PT,1. Analog and Digital,2.0,Um ADC usa $b=8$ bits por amostra e frequência...,cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit,Vamos resolver cada parte da questão passo a p...,4.2271,0.0246,0.0073,136.82,100,576,676
2,PT,1. Analog and Digital,5.0,O sinal analógico $x(t)=2t$ ~V é digitalizado ...,cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit,Vamos resolver a questão passo a passo.\n\n###...,18.5737,0.0322,0.0075,133.00,165,2467,2632
3,PT,1. Analog and Digital,13.0,Um sinal analógico $x(t)$ foi amostrado period...,cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit,Vamos resolver a questão passo a passo.\n\n###...,10.2713,0.0307,0.0074,134.86,165,1382,1547
4,PT,1. Analog and Digital,15.0,Um $b=8$ -bits ADC usa complemento de dois par...,cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit,Vamos resolver a parte (a) do problema passo a...,30.5337,0.0327,0.0077,129.96,189,3965,4154
5,PT,1. Analog and Digital,16.0,Uma sinusóide $x[n]=\sin((\pi/3)n)$ foi quanti...,cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit,Vamos resolver o problema passo a passo.\n\n##...,25.5619,0.0328,0.0077,130.63,184,3336,3520
6,EN,1. Analog and Digital,1.0,Both continuous-time $x(t)$ and the discrete-t...,cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit,Let's analyze the problem step-by-step.\n\n###...,7.0488,0.0255,0.0074,135.12,118,950,1068
7,EN,1. Analog and Digital,2.0,An ADC uses $b=8$ bits per sample and sampling...,cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit,Let's analyze the problem step-by-step.\n\n**G...,4.0090,0.0239,0.0074,135.76,80,542,622
8,EN,1. Analog and Digital,5.0,The analog signal $x(t)=2t$~V is digitized usi...,cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit,Let's break down the problem step by step.\n\n...,16.5482,0.0312,0.0075,132.53,144,2190,2334
9,EN,1. Analog and Digital,13.0,An analog signal $x(t)$ was periodically sampl...,cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit,### Part a) Finding the analytic expression of...,8.9851,0.0303,0.0074,134.23,144,1203,1347
10,EN,1. Analog and Digital,15.0,An $b=8$-bits ADC uses two's complement to out...,cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit,### Understanding the Problem\n\nWe have an 8-...,21.7364,0.0310,0.0076,131.21,165,2849,3014
11,EN,1. Analog and Digital,16.0,A sinusoid $x[n]=\sin((\pi/3)n)$ was quantized...,cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit,Let's break down the problem step by step to f...,34.1019,0.0307,0.0078,128.91,164,4393,4557

In [15]:
df1

,Idioma,Capitulo,Num_Questao,Pergunta,Modelo,Resposta_Gerada,Latencia_Total_s,TTFT_s,ITL_s,Throughput_tps,Tokens_In,Tokens_Out,Tokens_Total
0,PT,1. Analog and Digital,1.0,Ambos em tempo contínuo $x(t)$ e o tempo discr...,cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit,Vamos resolver a questão passo a passo.\n\n###...,4.9642,0.0310,0.0073,136.83,132,676,808
1,PT,1. Analog and Digital,2.0,Um ADC usa $b=8$ bits por amostra e frequência...,cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit,Vamos resolver cada parte da questão passo a p...,4.2301,0.0239,0.0073,136.70,100,576,676
2,PT,1. Analog and Digital,5.0,O sinal analógico $x(t)=2t$ ~V é digitalizado ...,cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit,Vamos resolver a questão passo a passo.\n\n###...,18.5685,0.0307,0.0075,133.03,165,2467,2632
3,PT,1. Analog and Digital,13.0,Um sinal analógico $x(t)$ foi amostrado period...,cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit,Vamos resolver a questão passo a passo.\n\n###...,10.2729,0.0305,0.0074,134.83,165,1382,1547
4,EN,1. Analog and Digital,1.0,Both continuous-time $x(t)$ and the discrete-t...,cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit,Let's analyze the problem step-by-step.\n\n###...,7.0093,0.0262,0.0074,135.90,118,950,1068
5,EN,1. Analog and Digital,2.0,An ADC uses $b=8$ bits per sample and sampling...,cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit,Let's analyze the problem step-by-step.\n\n**G...,3.9892,0.0229,0.0073,136.40,80,542,622
6,EN,1. Analog and Digital,5.0,The analog signal $x(t)=2t$~V is digitized usi...,cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit,Let's break down the problem step by step.\n\n...,16.4916,0.0290,0.0075,132.97,144,2190,2334
7,EN,1. Analog and Digital,13.0,An analog signal $x(t)$ was periodically sampl...,cyankiwi/Ministral-3-3B-Instruct-2512-AWQ-8bit,### Part a) Finding the analytic expression of...,8.9607,0.0291,0.0074,134.58,144,1203,1347

In [9]:
# Exibir o conteúdo completo da coluna "Resposta Gerada" para as 2 primeiras linhas
for i in range(4, 5):
    print(f"=== LINHA {i} (COMPLETA) ===")
    print(df1.iloc[i, 5])  # 5 = índice da coluna "Resposta Gerada"
    print("\n" + "-"*80 + "\n")

=== LINHA 4 (COMPLETA) ===
Vamos resolver a parte (a) do problema passo a passo.

### Dados:
- ADC com 8 bits usando complemento de dois.
- Intervalo de saída: \([-128, 127]\).
- Tamanho de passo \(\Delta = 10 \, \text{mV}\).
- Valores de entrada: \(x[n] = [0, 1, -1.28, 1.28, 2]\).

### Passo 1: Entender a codificação em complemento de dois
Um ADC de 8 bits com complemento de dois pode representar números inteiros no intervalo \([-128, 127]\). A representação binária \(x_b[n]\) é obtida a partir do valor decimal \(x_d[n]\) usando a seguinte fórmula:
\[
x_b[n] = \text{binário de } x_d[n] \text{ em complemento de dois}
\]
O valor decimal \(x_d[n]\) é obtido a partir do valor de entrada \(x[n]\) usando o tamanho de passo \(\Delta\):
\[
x_d[n] = \frac{x[n]}{\Delta} \times 2^{b-1}
\]
No entanto, como o ADC é uniforme e o tamanho de passo é \(\Delta = 10 \, \text{mV}\), o valor de entrada deve ser convertido para volts e então para um valor discreto. Supondo que os valores de entrada \(x[n]\) estão em volts (por exemplo, \(x[n] = 0 \, \text{V}, 1 \, \text{V}, -1.28 \, \text{V}, 1.28 \, \text{V}, 2 \, \text{V}\)), procedemos da seguinte forma:

### Passo 2: Conversão de entrada para valor discreto \(x_d[n]\)
O valor discreto \(x_d[n]\) é calculado como:
\[
x_d[n] = \text{arredondar}\left(\frac{x[n]}{\Delta}\right)
\]
Como \(\Delta = 10 \, \text{mV}\), então:
\[
x_d[n] = \text{arredondar}\left(\frac{x[n]}{0.01}\right)
\]

Calculamos para cada \(x[n]\):
1. \(x[0] = 0 \, \text{V}\):
   \[
   x_d[0] = \text{arredondar}\left(\frac{0}{0.01}\right) = 0
   \]

2. \(x[1] = 1 \, \text{V}\):
   \[
   x_d[1] = \text{arredondar}\left(\frac{1}{0.01}\right) = 100
   \]

3. \(x[-1.28] = -1.28 \, \text{V}\):
   \[
   x_d[2] = \text{arredondar}\left(\frac{-1.28}{0.01}\right) = \text{arredondar}(-128) = -128
   \]

4. \(x[1.28] = 1.28 \, \text{V}\):
   \[
   x_d[3] = \text{arredondar}\left(\frac{1.28}{0.01}\right) = \text{arredondar}(128) = 128
   \]
   No entanto, o intervalo máximo é \(127\), então \(x_d[3] = 127\) (o valor mais próximo dentro do intervalo).

5. \(x[2] = 2 \, \text{V}\):
   \[
   x_d[4] = \text{arredondar}\left(\frac{2}{0.01}\right) = \text{arredondar}(200)
   \]
   Como \(200\) está fora do intervalo \([-128, 127]\), o valor discreto mais próximo dentro do intervalo é \(127\).

### Passo 3: Saída binária \(x_b[n]\) em complemento de dois
Convertemos cada \(x_d[n]\) para binário em complemento de dois:

1. \(x_d[0] = 0\):
   \[
   x_b[0] = 00000000
   \]

2. \(x_d[1] = 100\):
   \[
   100_{10} = 01100100_{2}
   \]

3. \(x_d[2] = -128\):
   \[
   -128_{10} = 10000000_{2} \quad (\text{complemento de dois})
   \]

4. \(x_d[3] = 127\):
   \[
   127_{10} = 01111111_{2}
   \]

5. \(x_d[4] = 127\):
   \[
   x_b[4] = 01111111_{2}
   \]

### Passo 4: Saída decodificada \(x_q[n]\)
A saída decodificada é simplesmente o valor discreto \(x_d[n]\):
\[
x_q[n] = x_d[n] = [0, 100, -128, 127, 127]
\]

### Passo 5: Erro de quantização \(e[n]\)
O erro de quantização é calculado como:
\[
e[n] = x[n] - x_q[n] \times \Delta
\]
Convertemos \(x_q[n]\) para volts:
\[
x_q[n] \times \Delta = x_q[n] \times 0.01 \, \text{V}
\]

Calculamos para cada \(x[n]\):
1. \(x[0] = 0 \, \text{V}\):
   \[
   e[0] = 0 - 0 \times 0.01 = 0 \, \text{V}
   \]

2. \(x[1] = 1 \, \text{V}\):
   \[
   e[1] = 1 - 100 \times 0.01 = 1 - 1 = 0 \, \text{V}
   \]

3. \(x[-1.28] = -1.28 \, \text{V}\):
   \[
   e[2] = -1.28 - (-128) \times 0.01 = -1.28 + 1.28 = 0 \, \text{V}
   \]

4. \(x[1.28] = 1.28 \, \text{V}\):
   \[
   e[3] = 1.28 - 127 \times 0.01 = 1.28 - 1.27 = 0.01 \, \text{V}
   \]

5. \(x[2] = 2 \, \text{V}\):
   \[
   e[4] = 2 - 127 \times 0.01 = 2 - 1.27 = 0.73 \, \text{V}
   \]

### Resposta para a parte (a):
| \(x[n]\)       | \(x_b[n]\) (binário) | \(x_d[n]\) (inteiro) | \(x_q[n]\) (saída decodificada) | Erro de quantização \(e[n]\) (V) |
|----------------|----------------------|----------------------|--------------------------------|----------------------------------|
| 0              | 00000000             | 0                    | 0                              | 0                                |
| 1              | 01100100             | 100                  | 100                            | 0                                |
| -1.28          | 10000000             | -128                 | -128                           | 0                                |
| 1.28           | 01111111             | 127                  | 127                            | 0.01                             |
| 2              | 01111111             | 127                  | 127                            | 0.73                             |

---

### Resposta para a parte (b) usando numeração com deslocamento \(2^{b-1} = 128\):
Neste esquema, o valor binário é deslocado para a direita por 1 bit, ou seja, cada bit representa \(2^{b-1} = 128\) unidades. O valor discreto \(x_d[n]\) é calculado como:
\[
x_d[n] = \text{arredondar}\left(\frac{x[n]}{\Delta}\right) \times 128
\]

Recalculamos para cada \(x[n]\):

1. \(x[0] = 0 \, \text{V}\):
   \[
   x_d[0] = 0 \times 128 = 0
   \]

2. \(x[1] = 1 \, \text{V}\):
   \[
   x_d[1] = 100 \times 128 = 12800
   \]
   Como \(12800\) está fora do intervalo \([-128, 127]\), o valor mais próximo dentro do intervalo é \(127\) (ou ajustamos para o valor mais próximo dentro do intervalo de representação).

   No entanto, o intervalo de representação para um deslocamento é \([-128, 127]\) com 8 bits, então o valor discreto é ajustado para o mais próximo dentro do intervalo:
   \[
   x_d[1] = 12800 \mod 256 = 12800 - 50 \times 256 = 12800 - 12800 = 0
   \]
   Isso não é correto. Ajustemos da seguinte forma: o valor discreto é calculado como:
   \[
   x_d[n] = \text{arredondar}\left(\frac{x[n]}{\Delta}\right) \times 128
   \]
   e então ajustado para o intervalo \([-128, 127]\):
   Para \(x[1] = 1 \, \text{V}\):
   \[
   x_d[1] = 100 \times 128 = 12800
   \]
   Como \(12800\) está fora do intervalo, o valor mais próximo dentro do intervalo é \(127\) (ou ajustamos para o valor mais próximo dentro do intervalo de representação, que é \([-128, 127]\)).

   Isso não é aplicável diretamente. A numeração com deslocamento implica que o valor binário é deslocado para a direita por 1 bit, então o valor discreto é calculado como:
   \[
   x_d[n] = \text{arredondar}\left(\frac{x[n]}{\Delta}\right) \times 128
   \]
   e então o valor binário é obtido deslocando para a direita por 1 bit.

   A saída binária \(x_b[n]\) é então:
   \[
   x_b[n] = \text{deslocar para a direita por 1 bit} \left( \text{binário de } \text{arredondar}\left(\frac{x[n]}{\Delta}\right) \right)
   \]

   Recalculamos:
   - \(x_d[0] = 0 \times 128 = 0\):
     \[
     x_b[0] = 00000000 \rightarrow \text{deslocar para a direita por 1 bit} = 0000000
     \]

   - \(x_d[1] = 100 \times 128 = 12800\):
     \[
     \text{arredondar}(12800 / 256) = 50 \quad (\text{como } 256 \times 50 = 12800)
     \]
     \[
     50_{10} = 00110010_{2}
     \]
     Deslocar para a direita por 1 bit:
     \[
     x_b[1] = 0000110010
     \]

   - \(x[-1.28] = -128\):
     \[
     x_d[2] = -128 \times 128 = -16384
     \]
     \[
     \text{arredondar}(-16384 / 256) = -64 \quad (\text{como } 256 \times -64 = -16384)
     \]
     \[
     -64_{10} = 10000000_{2} \quad (\text{complemento de dois})
     \]
     Deslocar para a direita por 1 bit:
     \[
     x_b[2] = 10000000
     \]

   - \(x[1.28] = 127\):
     \[
     x_d[3] = 127 \times 128 = 16256
     \]
     \[
     \text{arredondar}(16256 / 256) = 63 \quad (\text{como } 256 \times 63 = 16248)
     \]
     \[
     63_{10} = 00111111_{2}
     \]
     Deslocar para a direita por 1 bit:
     \[
     x_b[3] = 0000111111
     \]

   - \(x[2] = 200\):
     \[
     x_d[4] = 200 \times 128 = 25600
     \]
     \[
     \text{arredondar}(25600 / 256) = 100 \quad (\text{como } 256 \times 100 = 25600)
     \]
     \[
     100_{10} = 01100100_{2}
     \]
     Deslocar para a direita por 1 bit:
     \[
     x_b[4] = 0001100100
     \]

### Saída decodificada \(x_q[n]\):
A saída decodificada é o valor discreto ajustado:
\[
x_q[n] = \text{arredondar}\left(\frac{x[n]}{\Delta}\right) \times 128 \mod 256
\]

### Erro de quantização \(e[n]\):
\[
e[n] = x[n] - x_q[n] \times \Delta
\]

### Resposta para a parte (b):
| \(x[n]\)       | \(x_b[n]\) (binário) | \(x_d[n]\) (inteiro) | \(x_q[n]\) (saída decodificada) | Erro de quantização \(e[n]\) (V) |
|----------------|----------------------|----------------------|--------------------------------|----------------------------------|
| 0              | 0000000              | 0                    | 0                              | 0                                |
| 1              | 0000110010           | 12800 / 256 = 50     | 50 * 128 = 6400 mod 256 = 128    | \(1 - 128 \times 0.01 = 0\)       |
| -1.28          | 10000000             | -16384 / 256 = -64   | -64 * 128 = -8192 mod 256 = 128  | \(-1.28 - 128 \times 0.01 = -1.28 + 1.28 = 0\) |
| 1.28           | 0000111111           | 16256 / 256 = 63     | 63 * 128 = 8144 mod 256 = 128    | \(1.28 - 128 \times 0.01 = 0.08\)  |
| 2              | 0001100100           | 25600 / 256 = 100    | 100 * 128 = 12800 mod 256 = 0    | \(2 - 0 \times 0.01 = 2\)         |

Ajustando corretamente o cálculo para o esquema de deslocamento, os valores precisos de \(x_q[n]\) e \(e[n]\) devem ser recalculados de forma mais precisa, mas a ideia é que o valor discreto é ajustado dentro do intervalo de representação de 8 bits com deslocamento.

--------------------------------------------------------------------------------

In [10]:
# Exibir o conteúdo completo da coluna "Resposta Gerada" para as 2 primeiras linhas
for i in range(4, 5):
    print(f"=== LINHA {i} (COMPLETA) ===")
    print(df2.iloc[i, 5])  # 5 = índice da coluna "Resposta Gerada"
    print("\n" + "-"*80 + "\n")

=== LINHA 4 (COMPLETA) ===
Vamos resolver a parte (a) do problema passo a passo.

### Dados:
- ADC com 8 bits usando complemento de dois.
- Intervalo de saída: \([-128, 127]\).
- Tamanho de passo \(\Delta = 10 \, \text{mV}\).
- Valores de entrada: \(x[n] = [0, 1, -1.28, 1.28, 2]\).

### Passo 1: Entender a codificação em complemento de dois
Um ADC de 8 bits com complemento de dois representa números inteiros no intervalo \([-128, 127]\). A saída binária \(x_b[n]\) é obtida através da seguinte fórmula:
\[
x_b[n] = \text{binário em complemento de dois de } x_d[n]
\]
onde \(x_d[n]\) é o valor decodificado (inteiro correspondente ao sinal de entrada quantizado).

### Passo 2: Quantização do sinal de entrada
O sinal de entrada \(x[n]\) é quantizado em um valor discreto \(x_q[n]\) usando o tamanho de passo \(\Delta = 10 \, \text{mV}\). A quantização é feita arredondando o valor para o valor discreto mais próximo. Se o valor estiver exatamente no meio entre dois valores discretos, arredonda para o valor mais próximo (convenção de arredondamento para valores iguais a 0.5).

#### Valores de entrada e quantização:
1. \(x[0] = 0 \, \text{mV}\)
   - \(x_q[0] = 0 \, \text{mV}\) (exato).
   - \(x_d[0] = 0\) (valor inteiro correspondente).

2. \(x[1] = 1 \, \text{mV}\)
   - \(x_q[1] = 1 \, \text{mV}\) (exato).
   - \(x_d[1] = 1\) (valor inteiro correspondente).

3. \(x[2] = -1.28 \, \text{mV}\)
   - O valor discreto mais próximo é \(-1 \, \text{mV}\) (pois \(-1.28\) está mais próximo de \(-1\) do que de \(0\)).
   - \(x_q[2] = -1 \, \text{mV}\).
   - \(x_d[2] = -1\) (valor inteiro correspondente).

4. \(x[3] = 1.28 \, \text{mV}\)
   - O valor discreto mais próximo é \(1 \, \text{mV}\) (pois \(1.28\) está mais próximo de \(1\) do que de \(2\)).
   - \(x_q[3] = 1 \, \text{mV}\).
   - \(x_d[3] = 1\) (valor inteiro correspondente).

5. \(x[4] = 2 \, \text{mV}\)
   - O valor discreto mais próximo é \(2 \, \text{mV}\) (exato).
   - \(x_q[4] = 2 \, \text{mV}\).
   - \(x_d[4] = 2\) (valor inteiro correspondente).

### Passo 3: Conversão para complemento de dois
Agora, convertemos \(x_d[n]\) para binário em complemento de dois.

#### Conversão para complemento de dois:
- Para valores positivos, o binário é simples.
- Para valores negativos, calculamos o complemento de dois como \(2^b - x_d[n]\), onde \(b = 8\).

1. \(x_d[0] = 0\)
   - Binário: \(00000000\).

2. \(x_d[1] = 1\)
   - Binário: \(00000001\).

3. \(x_d[2] = -1\)
   - Complemento de dois: \(2^8 - 1 = 128 - 1 = 127\).
   - Binário: \(11111111\) (pois \(127\) em binário é \(01111111\), e o complemento de dois é \(10000001\), mas como \(x_d[n]\) é \(-1\), o binário é \(11111111\) para representar \(-1\) em complemento de dois).

   *Correção*: O complemento de dois de \(-1\) é calculado como \(128 - 1 = 127\), e o binário de \(127\) é \(01111111\). No entanto, para representar \(-1\) em complemento de dois, o binário é \(11111111\) (inversão dos bits de \(00000001\) e mais um). Portanto, \(x_b[2] = 11111111\).

4. \(x_d[3] = 1\)
   - Binário: \(00000001\).

5. \(x_d[4] = 2\)
   - Binário: \(00000010\).

### Passo 4: Saída decodificada e erro de quantização
- \(x_q[n]\) é o valor quantizado em mV, já calculado.
- O erro de quantização \(e[n]\) é dado por:
  \[
  e[n] = x[n] - x_q[n]
  \]

1. \(e[0] = 0 - 0 = 0\).
2. \(e[1] = 1 - 1 = 0\).
3. \(e[2] = -1.28 - (-1) = -0.28\).
4. \(e[3] = 1.28 - 1 = 0.28\).
5. \(e[4] = 2 - 2 = 0\).

### Resposta para a parte (a):
| \(x[n]\) | \(x_q[n]\) (mV) | \(x_d[n]\) | \(x_b[n]\) (binário) | \(e[n]\) (mV) |
|----------|----------------|------------|----------------------|---------------|
| 0        | 0              | 0          | 00000000             | 0             |
| 1        | 1              | 1          | 00000001             | 0             |
| -1.28    | -1             | -1         | 11111111             | -0.28         |
| 1.28     | 1              | 1          | 00000001             | 0.28          |
| 2        | 2              | 2          | 00000010             | 0             |

---

### Parte (b): Esquema de numeração com deslocamento \(2^{b-1} = 128\)
Neste caso, o ADC usa um esquema de numeração com deslocamento, onde os valores são representados como:
\[
x_b[n] = \text{binário de } x_d[n] \text{ deslocado para a direita por } 1 \text{ bit}
\]
Isso significa que o valor \(x_d[n]\) é representado como:
\[
x_d[n] = \text{binário de } x_b[n] \text{ deslocado para a esquerda por } 1 \text{ bit}
\]

#### Conversão:
1. \(x_d[0] = 0\)
   - Binário deslocado: \(00000000\) deslocado para a direita por 1 bit é \(00000000\) (sem alteração, pois \(0\) deslocado é \(0\)).

2. \(x_d[1] = 1\)
   - Binário deslocado: \(00000001\) deslocado para a direita por 1 bit é \(00000000\) (o bit mais significativo é perdido).

   *Correção*: O deslocamento para a direita por 1 bit significa que o valor é dividido por 2. Portanto, \(x_d[n]\) é o binário original deslocado para a esquerda por 1 bit, ou seja, \(x_d[n] = 2 \cdot x_b[n]\). Mas como \(x_b[n]\) é a saída binária, o valor decodificado \(x_d[n]\) é obtido deslocando para a esquerda por 1 bit.

   Para este esquema, os valores são representados como:
   \[
   x_d[n] = \text{binário de } x_b[n] \text{ deslocado para a esquerda por } 1 \text{ bit}
   \]
   Mas como \(x_b[n]\) é a saída binária, o valor decodificado é:
   \[
   x_d[n] = \text{binário de } x_b[n] \text{ deslocado para a direita por } 1 \text{ bit}
   \]
   Ou seja, \(x_d[n] = \lfloor x_b[n] / 2 \rfloor\).

   Por outro lado, o valor quantizado \(x_q[n]\) é obtido quantizando \(x[n]\) e então deslocando para a esquerda por 1 bit.

   Vamos redefinir:
   - Quantizamos \(x[n]\) como antes, obtendo \(x_q[n]\).
   - Em seguida, convertemos \(x_q[n]\) para binário e deslocamos para a esquerda por 1 bit para obter \(x_d[n]\).

#### Conversão para deslocamento:
1. \(x_d[0] = 0\)
   - \(x_q[0] = 0\).
   - Binário: \(00000000\).
   - Deslocado para a esquerda por 1 bit: \(00000000\) (valor \(0\)).

2. \(x_d[1] = 1\)
   - \(x_q[1] = 1\).
   - Binário: \(00000001\).
   - Deslocado para a esquerda por 1 bit: \(00000000\) (valor \(0\)).

   *Correção*: O deslocamento para a esquerda por 1 bit significa que o valor é multiplicado por 2. Portanto, \(x_d[n] = 2 \cdot x_q[n]\).

   Mas como \(x_q[n]\) é o valor quantizado em mV, e o ADC usa um deslocamento de 128, o valor decodificado é:
   \[
   x_d[n] = \text{binário de } x_b[n] \text{ deslocado para a esquerda por } 1 \text{ bit}
   \]
   Ou seja, \(x_b[n]\) é a saída binária de \(x_d[n] / 2\).

   Para representar \(x_d[n]\) em binário com deslocamento, o valor é:
   \[
   x_b[n] = \text{binário de } x_d[n] \text{ deslocado para a direita por } 1 \text{ bit}
   \]
   Ou seja, \(x_b[n] = \lfloor x_d[n] / 2 \rfloor\).

   Mas como \(x_d[n]\) é o valor decodificado, e \(x_q[n]\) é o valor quantizado em mV, temos:
   \[
   x_d[n] = 2 \cdot x_q[n]
   \]
   Porque o deslocamento de 128 significa que o valor é representando como \(x_d[n] = 2 \cdot x_q[n]\).

   Por exemplo:
   - \(x_q[0] = 0\), então \(x_d[0] = 0\).
   - \(x_q[1] = 1\), então \(x_d[1] = 2\).
   - \(x_q[2] = -1\), então \(x_d[2] = -2\).
   - \(x_q[3] = 1\), então \(x_d[3] = 2\).
   - \(x_q[4] = 2\), então \(x_d[4] = 4\).

   Agora, convertemos \(x_d[n]\) para binário com deslocamento:
   - \(x_d[n]\) é o valor decodificado, e \(x_b[n]\) é o binário de \(x_d[n]\) deslocado para a direita por 1 bit.

   Por exemplo:
   - \(x_d[0] = 0\), binário: \(00000000\), deslocado para a direita por 1 bit: \(00000000\).
   - \(x_d[1] = 2\), binário: \(00000010\), deslocado para a direita por 1 bit: \(00000001\).
   - \(x_d[2] = -2\), binário em complemento de dois: \(11111110\) (pois \(-2\) é \(128 - 2 = 126\), e \(126\) é \(01111110\), complemento de dois é \(10000001\), mas como \(-2\) é \(11111110\)).
   - \(x_d[3] = 2\), binário: \(00000010\), deslocado para a direita por 1 bit: \(00000001\).
   - \(x_d[4] = 4\), binário: \(00000100\), deslocado para a direita por 1 bit: \(00000010\).

#### Resposta para a parte (b):
| \(x[n]\) | \(x_q[n]\) (mV) | \(x_d[n]\) | \(x_b[n]\) (binário) | \(e[n]\) (mV) |
|----------|----------------|------------|----------------------|---------------|
| 0        | 0              | 0          | 00000000             | 0             |
| 1        | 1              | 2          | 00000001             | \(1 - 0.5 = 0.5\) (correção: \(x_d[n] = 2 \cdot x_q[n]\), então \(e[n] = x[n] - x_q[n] = 1 - 1 = 0\), mas \(x_d[n]\) é \(2 \cdot x_q[n]\), não há erro no valor decodificado, mas o erro de quantização é \(x[n] - x_q[n] = 0\)).
   *Correção*: O erro de quantização é sempre \(x[n] - x_q[n]\), independentemente do esquema de numeração. O esquema de numeração afeta apenas a representação binária \(x_b[n]\).

   Recalculando:
   - \(x_q[n]\) é o valor quantizado em mV.
   - \(x_d[n] = 2 \cdot x_q[n]\).
   - \(x_b[n]\) é o binário de \(x_d[n]\) deslocado para a direita por 1 bit.

   Por exemplo:
   - \(x_q[0] = 0\), \(x_d[0] = 0\), \(x_b[0] = 00000000\).
   - \(x_q[1] = 1\), \(x_d[1] = 2\), \(x_b[1] = 00000001\).
   - \(x_q[2] = -1\), \(x_d[2] = -2\), \(x_b[2] = 11111110\) (complemento de dois de \(-2\) é \(11111110\)).
   - \(x_q[3] = 1\), \(x_d[3] = 2\), \(x_b[3] = 00000001\).
   - \(x_q[4] = 2\), \(x_d[4] = 4\), \(x_b[4] = 00000010\).

   Erro de quantização \(e[n] = x[n] - x_q[n]\):
   - \(e[0] = 0\).
   - \(e[1] = 0\).
   - \(e[2] = -0.28\).
   - \(e[3] = 0.28\).
   - \(e[4] = 0\).

### Resposta final para a parte (b):
| \(x[n]\) | \(x_q[n]\) (mV) | \(x_d[n]\) | \(x_b[n]\) (binário) | \(e[n]\) (mV) |
|----------|----------------|------------|----------------------|---------------|
| 0        | 0              | 0          | 00000000             | 0             |
| 1        | 1              | 2          | 00000001             | 0             |
| -1.28    | -1             | -2         | 11111110             | -0.28         |
| 1.28     | 1              | 2          | 00000001             | 0.28          |
| 2        | 2              | 4          | 00000010             | 0             |

--------------------------------------------------------------------------------

### **Random Seed 456 (1° vez)**

In [27]:
df1.iloc[[0, 1, 2, 3], 5] == df2.iloc[[0 ,1, 2, 3], 5]

0    True
1    True
2    True
3    True
Name: Resposta_Gerada, dtype: bool

In [50]:
sum(df1.iloc[[0,1, 2, 3], 5] == df2.iloc[[0,1, 2, 3], 5])/len(df1.iloc[[0,1, 2, 3], 5])

1.0

### **Random Seed 456 (2° vez)**

In [54]:
df1.iloc[[0, 1, 2, 3], 5] == df2.iloc[[0 ,1, 2, 3], 5]

0     True
1    False
2    False
3    False
Name: Resposta_Gerada, dtype: bool

In [55]:
sum(df1.iloc[[0,1, 2, 3], 5] == df2.iloc[[0,1, 2, 3], 5])/len(df1.iloc[[0,1, 2, 3], 5])

0.25

### **Random Seed 42 (1° vez)**

In [58]:
df1.iloc[[0,1, 2, 3], 5] == df2.iloc[[0,1, 2, 3], 5]

0    True
1    True
2    True
3    True
Name: Resposta_Gerada, dtype: bool

In [59]:
sum(df1.iloc[[0,1, 2, 3], 5] == df2.iloc[[0,1, 2, 3], 5])/len(df1.iloc[[0,1, 2, 3], 5])

1.0

### **Random Seed 42 (2° vez)**

In [62]:
df1.iloc[[0,1, 2, 3], 5] == df2.iloc[[0,1, 2, 3], 5]

0     True
1    False
2    False
3    False
Name: Resposta_Gerada, dtype: bool

In [63]:
sum(df1.iloc[[0,1, 2, 3], 5] == df2.iloc[[0,1, 2, 3], 5])/len(df1.iloc[[0,1, 2, 3], 5])

0.25

# **Gerador de respostas Versão 2**

In [ ]:
# No notebook, use isso em vez de !pip
# import sys
# !{sys.executable} -m pip install pandas openai python-dotenv requests matplotlib seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 KB 1.7 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /home/canavieira/Tutor_Inteligente/env_vllm/lib/python3.10/site-packages (from seaborn) (3.10.9)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /home/canavieira/Tutor_Inteligente/env_vllm/lib/python3.10/site-packages (from seaborn) (2.2.6)
Requirement already satisfied: pandas>=1.2 in /home/canavieira/Tutor_Inteligente/env_vllm/lib/python3.10/site-packages (from seaborn) (2.3.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /home/canavieira/Tutor_Inteligente/env_vllm/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/canavieira/Tutor_Inteligente/env_vllm/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.2)
Requirement already satisfied: fonttools>=4.22.0 in /home/canavieira/Tutor_Inteligente/env_vllm/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: packaging>=20.0 in /home/canavieira/Tutor_Inteligente/env_vllm/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.2)
Requirement already satisfied: cycler>=0.10 in /home/canavieira/Tutor_Inteligente/env_vllm/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: pyparsing>=3 in /home/canavieira/Tutor_Inteligente/env_vllm/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /home/canavieira/Tutor_Inteligente/env_vllm/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pillow>=8 in /home/canavieira/Tutor_Inteligente/env_vllm/lib/python3.10/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.2.0)
Requirement already satisfied: tzdata>=2022.7 in /home/canavieira/Tutor_Inteligente/env_vllm/lib/python3.10/site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: pytz>=2020.1 in /home/canavieira/Tutor_Inteligente/env_vllm/lib/python3.10/site-packages (from pandas>=1.2->seaborn) (2026.2)
Requirement already satisfied: six>=1.5 in /home/canavieira/Tutor_Inteligente/env_vllm/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2

In [12]:
# Célula 1: Setup e imports
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import glob
from IPython.display import display, HTML

In [16]:
# Importar o módulo
import gerador_respostas_2
from gerador_respostas_2 import process_dataset

# Ver a seed definida na classe BenchmarkRunner
import inspect

## **1.1 - Modelo Bruto Local**

In [40]:
# Célula 2: Configuração interativa
# Permite escolher configurações diretamente no notebook

# 1. Tipo de teste: "bruto" ou "tutor"
TIPO_TESTE_CHOICE = "bruto"

# 2. Modelo a ser usado
MODELO_CHOICE = "cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit"

# 3. Configuração das colunas a processar (NOVO!)
# Escolha UMA das opções abaixo:

# Opção A: Apenas Português
COLUNAS_CHOICE = [("PT", "pergunta_pt")]

# Opção B: Apenas Inglês
# COLUNAS_CHOICE = [("EN", "pergunta_en")]

# Opção C: Ambos (Português e Inglês)
# COLUNAS_CHOICE = [("PT", "pergunta_pt"), ("EN", "pergunta_en")]

# Opção D: Coluna customizada (altere conforme necessidade)
# COLUNAS_CHOICE = [("ES", "pergunta_es")]  # Exemplo para espanhol

In [41]:
# Sobrescrever as configurações do módulo
gerador_respostas_2.TIPO_TESTE = TIPO_TESTE_CHOICE
gerador_respostas_2.MODELO_ATIVO = MODELO_CHOICE
gerador_respostas_2.COLUNAS_PROCESSAR = COLUNAS_CHOICE

print(f"✅ Configuração definida:")
print(f"   - Tipo de teste: {TIPO_TESTE_CHOICE}")
print(f"   - Modelo: {MODELO_CHOICE}")
print(f"   - Colunas a processar: {COLUNAS_CHOICE}")

# Opcional: Verificar colunas disponíveis no dataset
print("\n📋 Verificando colunas disponíveis no dataset...")
try:
    gerador_respostas_2.listar_colunas_disponiveis()
except:
    print("   Não foi possível listar colunas (arquivo pode não existir ainda)")

✅ Configuração definida:
   - Tipo de teste: bruto
   - Modelo: cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit
   - Colunas a processar: [('PT', 'pergunta_pt')]

📋 Verificando colunas disponíveis no dataset...
Colunas disponíveis no dataset:
  - material
  - capitulo
  - paginas
  - numero_questao
  - pergunta_en
  - qtd_caracteres_en
  - pergunta_pt
  - qtd_caracteres_pt

### **1.1.1 - Com Hit Cache**

Nesse experimento ligamos o `vLLM` no terminal com o Hit Cache, que é um parâmetro *default* dele:

```{c}
python3 -m vllm.entrypoints.openai.api_server \
    --model cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit \
    --host 0.0.0.0 \
    --port 8006 \
    --max-model-len 16384 \
    --gpu-memory-utilization 0.85
```

In [30]:
# Célula 3: Executar o benchmark (cuidado: pode demorar!)
print("\n🚀 Iniciando benchmark...")
print("⚠️  Isso pode levar vários minutos/horas dependendo da quantidade de perguntas...")
process_dataset()  # Descomente para executar

2026-05-20 14:31:17,900 - INFO - TESTE: BRUTO | MODELO: cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit
2026-05-20 14:31:17,900 - INFO - COLUNAS A PROCESSAR: [('PT', 'pergunta_pt')]
2026-05-20 14:31:17,953 - INFO - Aquecendo o modelo cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit (Cold Start)...
2026-05-20 14:31:18,013 - INFO - HTTP Request: POST http://10.10.80.238:8006/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-20 14:31:18,014 - INFO - Aquecimento concluído. Prontos para as requisições.
2026-05-20 14:31:18,016 - INFO - === INICIANDO BLOCO: PT (Coluna: pergunta_pt) ===
2026-05-20 14:31:18,017 - INFO - [PT] Processando Q1/4 | Cap: 1. Analog and Digital
2026-05-20 14:31:18,021 - INFO - HTTP Request: POST http://10.10.80.238:8006/v1/chat/completions "HTTP/1.1 200 OK"

🚀 Iniciando benchmark...
⚠️  Isso pode levar vários minutos/horas dependendo da quantidade de perguntas...

2026-05-20 14:31:37,197 - INFO - [PT] Processando Q2/4 | Cap: 1. Analog and Digital
2026-05-20 14:31:37,202 - INFO - HTTP Request: POST http://10.10.80.238:8006/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-20 14:31:45,589 - INFO - [PT] Processando Q3/4 | Cap: 1. Analog and Digital
2026-05-20 14:31:45,595 - INFO - HTTP Request: POST http://10.10.80.238:8006/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-20 14:32:13,629 - INFO - [PT] Processando Q4/4 | Cap: 1. Analog and Digital
2026-05-20 14:32:13,634 - INFO - HTTP Request: POST http://10.10.80.238:8006/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-20 14:32:48,702 - INFO - Benchmark concluído com sucesso! Salvo em: resultados_brutos/geracao_bruto_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt.csv

In [33]:
import pandas as pd

caminho_dataset1 = "resultados_brutos/geracao_bruto_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_V1_Cache.csv"
caminho_dataset2 = "resultados_brutos/geracao_bruto_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_V2_Cache.csv"
caminho_dataset3 = "resultados_brutos/geracao_bruto_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_V3_Cache.csv"

# Deixar o pandas detectar automaticamente o delimitador
df_1_bruto_local_cache = pd.read_csv(caminho_dataset1)
df_2_bruto_local_cache = pd.read_csv(caminho_dataset2)
df_3_bruto_local_cache = pd.read_csv(caminho_dataset3)

In [34]:
df_1_bruto_local_cache.head()

,Idioma,Interferencia_Tutor,Capitulo,Num_Questao,Pergunta,Modelo,Resposta_Gerada,Latencia_Total_s,TTFT_s,ITL_s,Throughput_tps,Tokens_In,Tokens_Out,Tokens_Total
0,PT,NÃO,1. Analog and Digital,1.0,Ambos em tempo contínuo $x(t)$ e o tempo discr...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Vamos analisar cada parte da questão separadam...,18.8836,0.2151,0.0146,68.56,132,1281,1413
1,PT,NÃO,1. Analog and Digital,2.0,Um ADC usa $b=8$ bits por amostra e frequência...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,**Processo de resolução:**\n\n**a) Cálculo da ...,9.1639,0.0430,0.0145,68.85,100,629,729
2,PT,NÃO,1. Analog and Digital,5.0,O sinal analógico $x(t)=2t$ ~V é digitalizado ...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Parte a) Valores das quatro primeiras amos...,25.2603,0.0566,0.0147,68.05,165,1716,1881
3,PT,NÃO,1. Analog and Digital,13.0,Um sinal analógico $x(t)$ foi amostrado period...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Parte a) Qual é a expressão analítica de \...,24.3643,0.0595,0.0147,67.89,165,1651,1816

In [35]:
df_1_bruto_local_cache.iloc[[0, 1, 2, 3], 6] == df_2_bruto_local_cache.iloc[[0, 1, 2, 3], 6]

0     True
1    False
2    False
3    False
Name: Resposta_Gerada, dtype: bool

In [36]:
df_2_bruto_local_cache.iloc[[0, 1, 2, 3], 6] == df_3_bruto_local_cache.iloc[[0, 1, 2, 3], 6]

0    True
1    True
2    True
3    True
Name: Resposta_Gerada, dtype: bool

### **1.1.2 - Sem Hit Cache**

Nesse experimento ligamos o `vLLM` no terminal sem o Hit Cache, para isso temos que definir o comando `--no-enable-prefix-caching` ao ativar o `vLLM`:

```{c}
python3 -m vllm.entrypoints.openai.api_server \
    --model cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit \
    --host 0.0.0.0 \
    --port 8006 \
    --max-model-len 16384 \
    --gpu-memory-utilization 0.85 \
    --no-enable-prefix-caching
```

In [42]:
# Célula 3: Executar o benchmark (cuidado: pode demorar!)
print("\n🚀 Iniciando benchmark...")
print("⚠️  Isso pode levar vários minutos/horas dependendo da quantidade de perguntas...")
process_dataset()  # Descomente para executar

2026-05-20 14:47:49,836 - INFO - TESTE: BRUTO | MODELO: cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit
2026-05-20 14:47:49,836 - INFO - COLUNAS A PROCESSAR: [('PT', 'pergunta_pt')]
2026-05-20 14:47:49,891 - INFO - Aquecendo o modelo cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit (Cold Start)...
2026-05-20 14:47:49,950 - INFO - HTTP Request: POST http://10.10.80.238:8006/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-20 14:47:49,951 - INFO - Aquecimento concluído. Prontos para as requisições.
2026-05-20 14:47:49,954 - INFO - === INICIANDO BLOCO: PT (Coluna: pergunta_pt) ===
2026-05-20 14:47:49,954 - INFO - [PT] Processando Q1/4 | Cap: 1. Analog and Digital
2026-05-20 14:47:49,959 - INFO - HTTP Request: POST http://10.10.80.238:8006/v1/chat/completions "HTTP/1.1 200 OK"

🚀 Iniciando benchmark...
⚠️  Isso pode levar vários minutos/horas dependendo da quantidade de perguntas...

2026-05-20 14:48:09,198 - INFO - [PT] Processando Q2/4 | Cap: 1. Analog and Digital
2026-05-20 14:48:09,204 - INFO - HTTP Request: POST http://10.10.80.238:8006/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-20 14:48:18,865 - INFO - [PT] Processando Q3/4 | Cap: 1. Analog and Digital
2026-05-20 14:48:18,871 - INFO - HTTP Request: POST http://10.10.80.238:8006/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-20 14:48:44,632 - INFO - [PT] Processando Q4/4 | Cap: 1. Analog and Digital
2026-05-20 14:48:44,637 - INFO - HTTP Request: POST http://10.10.80.238:8006/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-20 14:49:09,498 - INFO - Benchmark concluído com sucesso! Salvo em: resultados_brutos/geracao_bruto_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt.csv

In [43]:
import pandas as pd

caminho_dataset1 = "resultados_brutos/geracao_bruto_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_V1_NoCache.csv"
caminho_dataset2 = "resultados_brutos/geracao_bruto_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_V2_NoCache.csv"
caminho_dataset3 = "resultados_brutos/geracao_bruto_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_V3_NoCache.csv"

# Deixar o pandas detectar automaticamente o delimitador
df_1_bruto_local_no_cache = pd.read_csv(caminho_dataset1)
df_2_bruto_local_no_cache = pd.read_csv(caminho_dataset2)
df_3_bruto_local_no_cache = pd.read_csv(caminho_dataset3)

In [67]:
df_1_bruto_local_no_cache.head()

,Idioma,Interferencia_Tutor,Capitulo,Num_Questao,Pergunta,Modelo,Resposta_Gerada,Latencia_Total_s,TTFT_s,ITL_s,Throughput_tps,Tokens_In,Tokens_Out,Tokens_Total
0,PT,NÃO,1. Analog and Digital,1.0,Ambos em tempo contínuo $x(t)$ e o tempo discr...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Vamos analisar cada parte da questão separadam...,18.7155,0.0575,0.0146,68.60,132,1281,1413
1,PT,NÃO,1. Analog and Digital,2.0,Um ADC usa $b=8$ bits por amostra e frequência...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,**Processo de resolução:**\n\n**a) Cálculo da ...,9.1515,0.0406,0.0145,68.93,100,629,729
2,PT,NÃO,1. Analog and Digital,5.0,O sinal analógico $x(t)=2t$ ~V é digitalizado ...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Parte a) Valores das quatro primeiras amos...,25.2319,0.0553,0.0147,68.12,165,1716,1881
3,PT,NÃO,1. Analog and Digital,13.0,Um sinal analógico $x(t)$ foi amostrado period...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Parte a) Qual é a expressão analítica de \...,24.3522,0.0561,0.0147,67.91,165,1651,1816

Usei `seed = 1334`em ambos:

In [45]:
df_1_bruto_local_no_cache.iloc[[0, 1, 2, 3], 6] == df_2_bruto_local_no_cache.iloc[[0, 1, 2, 3], 6]

0    True
1    True
2    True
3    True
Name: Resposta_Gerada, dtype: bool

Usei `seed = 1334` no segundo e `seed = 42` no terceiro, ainda assim tiveram o mesmo *output*, o que indica que o `seed`não está impactando:

In [46]:
df_2_bruto_local_no_cache.iloc[[0, 1, 2, 3], 6] == df_3_bruto_local_no_cache.iloc[[0, 1, 2, 3], 6]

0    True
1    True
2    True
3    True
Name: Resposta_Gerada, dtype: bool

## **1.2 - Modelo Tutor Local**

In [92]:
# Célula 2: Configuração interativa
# Permite escolher configurações diretamente no notebook

# 1. Tipo de teste: "bruto" ou "tutor"
TIPO_TESTE_CHOICE = "tutor"

# 2. Modelo a ser usado
MODELO_CHOICE = "cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit"

# 3. Configuração das colunas a processar (NOVO!)
# Escolha UMA das opções abaixo:

# Opção A: Apenas Português
COLUNAS_CHOICE = [("PT", "pergunta_pt")]

# Opção B: Apenas Inglês
# COLUNAS_CHOICE = [("EN", "pergunta_en")]

# Opção C: Ambos (Português e Inglês)
# COLUNAS_CHOICE = [("PT", "pergunta_pt"), ("EN", "pergunta_en")]

# Opção D: Coluna customizada (altere conforme necessidade)
# COLUNAS_CHOICE = [("ES", "pergunta_es")]  # Exemplo para espanhol

In [93]:
# Sobrescrever as configurações do módulo
gerador_respostas_2.TIPO_TESTE = TIPO_TESTE_CHOICE
gerador_respostas_2.MODELO_ATIVO = MODELO_CHOICE
gerador_respostas_2.COLUNAS_PROCESSAR = COLUNAS_CHOICE

print(f"✅ Configuração definida:")
print(f"   - Tipo de teste: {TIPO_TESTE_CHOICE}")
print(f"   - Modelo: {MODELO_CHOICE}")
print(f"   - Colunas a processar: {COLUNAS_CHOICE}")

# Opcional: Verificar colunas disponíveis no dataset
print("\n📋 Verificando colunas disponíveis no dataset...")
try:
    gerador_respostas_2.listar_colunas_disponiveis()

    # Método 1: Ver o código fonte do método _build_streaming_kwargs
    source = inspect.getsource(gerador_respostas_2.BenchmarkRunner._build_streaming_kwargs)
    print("\nCódigo do método _build_streaming_kwargs:")
    print(source)

except:
    print("   Não foi possível listar colunas (arquivo pode não existir ainda)")

✅ Configuração definida:
   - Tipo de teste: tutor
   - Modelo: cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit
   - Colunas a processar: [('PT', 'pergunta_pt')]

📋 Verificando colunas disponíveis no dataset...
Colunas disponíveis no dataset:
  - material
  - capitulo
  - paginas
  - numero_questao
  - pergunta_en
  - qtd_caracteres_en
  - pergunta_pt
  - qtd_caracteres_pt

Código do método _build_streaming_kwargs:
    def _build_streaming_kwargs(self, prompt: str) -> Dict[str, Any]:
        kwargs = {
            "model": self.model_name,
            "messages": [{"role": "user", "content": prompt}],
            "seed": 42,
            "stream": True,
            "stream_options": {"include_usage": True}
        }
        model_lower = self.model_name.lower()
        if "o1" not in model_lower and "o3" not in model_lower and "gpt-5" not in model_lower:
            kwargs["temperature"] = 0.2
        return kwargs

### **1.2.1 - Com Hit Cache**

Nesse experimento ligamos o `vLLM` no terminal com o Hit Cache, que é um parâmetro *default* dele:

```{c}
python3 -m vllm.entrypoints.openai.api_server \
    --model cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit \
    --host 0.0.0.0 \
    --port 8006 \
    --max-model-len 16384 \
    --gpu-memory-utilization 0.85
```

### **1.2.2 - Sem Hit Cache**

Nesse experimento ligamos o `vLLM` no terminal sem o Hit Cache, para isso temos que definir o comando `--no-enable-prefix-caching` ao ativar o `vLLM`:

```{c}
python3 -m vllm.entrypoints.openai.api_server \
    --model cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit \
    --host 0.0.0.0 \
    --port 8006 \
    --max-model-len 16384 \
    --gpu-memory-utilization 0.85 \
    --no-enable-prefix-caching
```

In [95]:
# Célula 3: Executar o benchmark (cuidado: pode demorar!)
print("\n🚀 Iniciando benchmark...")
print("⚠️  Isso pode levar vários minutos/horas dependendo da quantidade de perguntas...")
process_dataset()  # Descomente para executar

2026-05-20 16:02:07,487 - INFO - TESTE: TUTOR | MODELO: cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit
2026-05-20 16:02:07,488 - INFO - COLUNAS A PROCESSAR: [('PT', 'pergunta_pt')]
2026-05-20 16:02:07,490 - INFO - Aquecendo o Tutor Inteligente...

🚀 Iniciando benchmark...
⚠️  Isso pode levar vários minutos/horas dependendo da quantidade de perguntas...

2026-05-20 16:02:25,308 - INFO - Aquecimento do Tutor concluído.
2026-05-20 16:02:25,310 - INFO - === INICIANDO BLOCO: PT (Coluna: pergunta_pt) ===
2026-05-20 16:02:25,311 - INFO - [PT] Processando Q1/4 | Cap: 1. Analog and Digital
2026-05-20 16:02:42,473 - INFO - [PT] Processando Q2/4 | Cap: 1. Analog and Digital
2026-05-20 16:02:54,059 - INFO - [PT] Processando Q3/4 | Cap: 1. Analog and Digital
2026-05-20 16:03:24,236 - INFO - [PT] Processando Q4/4 | Cap: 1. Analog and Digital
2026-05-20 16:03:43,167 - INFO - Benchmark concluído com sucesso! Salvo em: resultados_brutos/geracao_tutor_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt.csv

In [96]:
import pandas as pd

caminho_dataset1 = "resultados_brutos/geracao_tutor_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_V1_NoCache.csv"
caminho_dataset2 = "resultados_brutos/geracao_tutor_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_V2_NoCache.csv"
#caminho_dataset3 = "resultados_brutos/geracao_tutor_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_V3_NoCache.csv"

# Deixar o pandas detectar automaticamente o delimitador
df_1_tutor_local_no_cache = pd.read_csv(caminho_dataset1)
df_2_tutor_local_no_cache = pd.read_csv(caminho_dataset2)
#df_3_tutor_local_no_cache = pd.read_csv(caminho_dataset3)

In [99]:
df_1_tutor_local_no_cache.head()

,Idioma,Interferencia_Tutor,Capitulo,Num_Questao,Pergunta,Modelo,Resposta_Gerada,Latencia_Total_s,TTFT_s,ITL_s,Throughput_tps,Tokens_In,Tokens_Out,Tokens_Total
0,PT,SIM,1. Analog and Digital,1.0,Ambos em tempo contínuo $x(t)$ e o tempo discr...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"Para responder à sua pergunta, precisamos ente...",16.5393,5.1576,0.0221,45.34,89,517,606
1,PT,SIM,1. Analog and Digital,2.0,Um ADC usa $b=8$ bits por amostra e frequência...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Resposta:\n\n#### a) Taxa de bits em bits ...,10.9533,3.2229,0.0223,44.76,80,347,427
2,PT,SIM,1. Analog and Digital,5.0,O sinal analógico $x(t)=2t$ ~V é digitalizado ...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"Para resolver o problema, seguiremos os passos...",29.7815,5.3036,0.0265,37.79,120,926,1046
3,PT,SIM,1. Analog and Digital,13.0,Um sinal analógico $x(t)$ foi amostrado period...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Resposta:\n\n#### a) Expressão analítica d...,18.4236,5.4030,0.0203,49.15,114,641,755

Usei `seed = 1334`em ambos:

In [98]:
df_1_tutor_local_no_cache.iloc[[0, 1, 2, 3], 6] == df_2_tutor_local_no_cache.iloc[[0, 1, 2, 3], 6]

0    True
1    True
2    True
3    True
Name: Resposta_Gerada, dtype: bool

## **1.3 - Modelo Bruto Comercial (GPT-5)**

In [2]:
# Célula 2: Configuração interativa
# Permite escolher configurações diretamente no notebook

# 1. Tipo de teste: "bruto" ou "tutor"
TIPO_TESTE_CHOICE = "bruto"

# 2. Modelo a ser usado
MODELO_CHOICE = "gpt-5"

# 3. Configuração das colunas a processar (NOVO!)
# Escolha UMA das opções abaixo:

# Opção A: Apenas Português
COLUNAS_CHOICE = [("PT", "pergunta_pt")]

# Opção B: Apenas Inglês
# COLUNAS_CHOICE = [("EN", "pergunta_en")]

# Opção C: Ambos (Português e Inglês)
# COLUNAS_CHOICE = [("PT", "pergunta_pt"), ("EN", "pergunta_en")]

# Opção D: Coluna customizada (altere conforme necessidade)
# COLUNAS_CHOICE = [("ES", "pergunta_es")]  # Exemplo para espanhol

In [3]:
# Sobrescrever as configurações do módulo
gerador_respostas_2.TIPO_TESTE = TIPO_TESTE_CHOICE
gerador_respostas_2.MODELO_ATIVO = MODELO_CHOICE
gerador_respostas_2.COLUNAS_PROCESSAR = COLUNAS_CHOICE

print(f"✅ Configuração definida:")
print(f"   - Tipo de teste: {TIPO_TESTE_CHOICE}")
print(f"   - Modelo: {MODELO_CHOICE}")
print(f"   - Colunas a processar: {COLUNAS_CHOICE}")

# Opcional: Verificar colunas disponíveis no dataset
print("\n📋 Verificando colunas disponíveis no dataset...")
try:
    gerador_respostas_2.listar_colunas_disponiveis()

    # Método 1: Ver o código fonte do método _build_streaming_kwargs
    source = inspect.getsource(gerador_respostas_2.BenchmarkRunner._build_streaming_kwargs)
    print("\nCódigo do método _build_streaming_kwargs:")
    print(source)

except:
    print("   Não foi possível listar colunas (arquivo pode não existir ainda)")

✅ Configuração definida:
   - Tipo de teste: bruto
   - Modelo: gpt-5
   - Colunas a processar: [('PT', 'pergunta_pt')]

📋 Verificando colunas disponíveis no dataset...
Colunas disponíveis no dataset:
  - material
  - capitulo
  - paginas
  - numero_questao
  - pergunta_en
  - qtd_caracteres_en
  - pergunta_pt
  - qtd_caracteres_pt

Código do método _build_streaming_kwargs:
    def _build_streaming_kwargs(self, prompt: str) -> Dict[str, Any]:
        kwargs = {
            "model": self.model_name,
            "messages": [{"role": "user", "content": prompt}],
            "seed": 42,
            "stream": True,
            "stream_options": {"include_usage": True}
        }
        model_lower = self.model_name.lower()

        # Lista de modelos que NÃO suportam temperature
        modelos_sem_temperature = ["o1", "o3", "gpt-5"]

        if not any(modelo in model_lower for modelo in modelos_sem_temperature):
            kwargs["temperature"] = 0.0
            print(f"[DEBUG] Enviando para API: seed={kwargs.get('seed')}, temp={kwargs.get('temperature')}")
        else:
            print(f"[DEBUG] Enviando para API: seed={kwargs.get('seed')}, temp=NÃO ENVIADO (modelo não suporta)")

        return kwargs

In [5]:
# Célula 3: Executar o benchmark (cuidado: pode demorar!)
print("\n🚀 Iniciando benchmark...")
print("⚠️  Isso pode levar vários minutos/horas dependendo da quantidade de perguntas...")
process_dataset()  # Descomente para executar

2026-05-20 21:51:25,914 - INFO - TESTE: BRUTO | MODELO: gpt-5
2026-05-20 21:51:25,914 - INFO - COLUNAS A PROCESSAR: [('PT', 'pergunta_pt')]
2026-05-20 21:51:25,960 - INFO - Aquecendo o modelo gpt-5 (Cold Start)...

🚀 Iniciando benchmark...
⚠️  Isso pode levar vários minutos/horas dependendo da quantidade de perguntas...
[DEBUG] Enviando para API: seed=42, temp=NÃO ENVIADO (modelo não suporta)

2026-05-20 21:51:31,694 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-20 21:51:31,696 - INFO - Aquecimento concluído. Prontos para as requisições.
2026-05-20 21:51:31,698 - INFO - === INICIANDO BLOCO: PT (Coluna: pergunta_pt) ===
2026-05-20 21:51:31,698 - INFO - [PT] Processando Q1/4 | Cap: 1. Analog and Digital

[DEBUG] Enviando para API: seed=42, temp=NÃO ENVIADO (modelo não suporta)

2026-05-20 21:51:42,893 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-20 21:51:43,996 - INFO - [PT] Processando Q2/4 | Cap: 1. Analog and Digital

[DEBUG] Enviando para API: seed=42, temp=NÃO ENVIADO (modelo não suporta)

2026-05-20 21:52:02,104 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-20 21:52:04,299 - INFO - [PT] Processando Q3/4 | Cap: 1. Analog and Digital

[DEBUG] Enviando para API: seed=42, temp=NÃO ENVIADO (modelo não suporta)

2026-05-20 21:52:30,608 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-20 21:52:33,703 - INFO - [PT] Processando Q4/4 | Cap: 1. Analog and Digital

[DEBUG] Enviando para API: seed=42, temp=NÃO ENVIADO (modelo não suporta)

2026-05-20 21:53:44,729 - INFO - HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-20 21:53:49,786 - INFO - Benchmark concluído com sucesso! Salvo em: resultados_brutos/geracao_bruto_gpt-5_pergunta_pt.csv

In [6]:
import pandas as pd

caminho_dataset1 = "resultados_brutos/geracao_bruto_gpt-5_pergunta_pt_V1.csv"
caminho_dataset2 = "resultados_brutos/geracao_bruto_gpt-5_pergunta_pt_V2.csv"
#caminho_dataset3 = "resultados_brutos/geracao_tutor_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_V3_NoCache.csv"

# Deixar o pandas detectar automaticamente o delimitador
df_1_bruto_comercial = pd.read_csv(caminho_dataset1)
df_2_bruto_comercial = pd.read_csv(caminho_dataset2)
#df_3_tutor_local_no_cache = pd.read_csv(caminho_dataset3)

In [7]:
df_1_bruto_comercial.head()

,Idioma,Interferencia_Tutor,Capitulo,Num_Questao,Pergunta,Modelo,Resposta_Gerada,Latencia_Total_s,TTFT_s,ITL_s,Throughput_tps,Tokens_In,Tokens_Out,Tokens_Total
0,PT,NÃO,1. Analog and Digital,1.0,Ambos em tempo contínuo $x(t)$ e o tempo discr...,gpt-5,a) Sinal contínuo x(t):\n- x(1.5) = 3 (pois 0 ...,7.8047,6.8424,0.0014,739.83,134,713,847
1,PT,NÃO,1. Analog and Digital,2.0,Um ADC usa $b=8$ bits por amostra e frequência...,gpt-5,a) Taxa de bits: R = b·fs = 8 bits/amostra × 1...,17.4419,16.2916,0.0010,1038.83,95,1196,1291
2,PT,NÃO,1. Analog and Digital,5.0,O sinal analógico $x(t)=2t$ ~V é digitalizado ...,gpt-5,"a) Amostragem (Ts = 1/fs = 0,01 s):\n- x[0] = ...",26.2941,23.5182,0.0016,626.83,163,1741,1904
3,PT,NÃO,1. Analog and Digital,13.0,Um sinal analógico $x(t)$ foi amostrado period...,gpt-5,"a) Pelo modelo de amostragem impulsiva,\nxs(t)...",57.8908,53.4213,0.0011,870.78,168,3893,4061

In [8]:
df_1_bruto_comercial.iloc[[0, 1, 2, 3], 6] == df_2_bruto_comercial.iloc[[0, 1, 2, 3], 6]

0    False
1    False
2    False
3    False
Name: Resposta_Gerada, dtype: bool

## **1.4 - Modelo Tutor Comercial (GPT-5)**

In [9]:
# Célula 2: Configuração interativa
# Permite escolher configurações diretamente no notebook

# 1. Tipo de teste: "bruto" ou "tutor"
TIPO_TESTE_CHOICE = "tutor"

# 2. Modelo a ser usado
MODELO_CHOICE = "gpt-5"

# 3. Configuração das colunas a processar (NOVO!)
# Escolha UMA das opções abaixo:

# Opção A: Apenas Português
COLUNAS_CHOICE = [("PT", "pergunta_pt")]

# Opção B: Apenas Inglês
# COLUNAS_CHOICE = [("EN", "pergunta_en")]

# Opção C: Ambos (Português e Inglês)
# COLUNAS_CHOICE = [("PT", "pergunta_pt"), ("EN", "pergunta_en")]

# Opção D: Coluna customizada (altere conforme necessidade)
# COLUNAS_CHOICE = [("ES", "pergunta_es")]  # Exemplo para espanhol

In [10]:
# Sobrescrever as configurações do módulo
gerador_respostas_2.TIPO_TESTE = TIPO_TESTE_CHOICE
gerador_respostas_2.MODELO_ATIVO = MODELO_CHOICE
gerador_respostas_2.COLUNAS_PROCESSAR = COLUNAS_CHOICE

print(f"✅ Configuração definida:")
print(f"   - Tipo de teste: {TIPO_TESTE_CHOICE}")
print(f"   - Modelo: {MODELO_CHOICE}")
print(f"   - Colunas a processar: {COLUNAS_CHOICE}")

# Opcional: Verificar colunas disponíveis no dataset
print("\n📋 Verificando colunas disponíveis no dataset...")
try:
    gerador_respostas_2.listar_colunas_disponiveis()

    # Método 1: Ver o código fonte do método _build_streaming_kwargs
    source = inspect.getsource(gerador_respostas_2.BenchmarkRunner._build_streaming_kwargs)
    print("\nCódigo do método _build_streaming_kwargs:")
    print(source)

except:
    print("   Não foi possível listar colunas (arquivo pode não existir ainda)")

✅ Configuração definida:
   - Tipo de teste: tutor
   - Modelo: gpt-5
   - Colunas a processar: [('PT', 'pergunta_pt')]

📋 Verificando colunas disponíveis no dataset...
Colunas disponíveis no dataset:
  - material
  - capitulo
  - paginas
  - numero_questao
  - pergunta_en
  - qtd_caracteres_en
  - pergunta_pt
  - qtd_caracteres_pt

Código do método _build_streaming_kwargs:
    def _build_streaming_kwargs(self, prompt: str) -> Dict[str, Any]:
        kwargs = {
            "model": self.model_name,
            "messages": [{"role": "user", "content": prompt}],
            "seed": 42,
            "stream": True,
            "stream_options": {"include_usage": True}
        }
        model_lower = self.model_name.lower()

        # Lista de modelos que NÃO suportam temperature
        modelos_sem_temperature = ["o1", "o3", "gpt-5"]

        if not any(modelo in model_lower for modelo in modelos_sem_temperature):
            kwargs["temperature"] = 0.0
            print(f"[DEBUG] Enviando para API: seed={kwargs.get('seed')}, temp={kwargs.get('temperature')}")
        else:
            print(f"[DEBUG] Enviando para API: seed={kwargs.get('seed')}, temp=NÃO ENVIADO (modelo não suporta)")

        return kwargs

In [11]:
# Célula 3: Executar o benchmark (cuidado: pode demorar!)
print("\n🚀 Iniciando benchmark...")
print("⚠️  Isso pode levar vários minutos/horas dependendo da quantidade de perguntas...")
process_dataset()  # Descomente para executar

2026-05-20 22:01:26,883 - INFO - TESTE: TUTOR | MODELO: gpt-5
2026-05-20 22:01:26,883 - INFO - COLUNAS A PROCESSAR: [('PT', 'pergunta_pt')]
2026-05-20 22:01:26,885 - INFO - Aquecendo o Tutor Inteligente...

🚀 Iniciando benchmark...
⚠️  Isso pode levar vários minutos/horas dependendo da quantidade de perguntas...

2026-05-20 22:02:27,004 - WARNING - Aviso no warmup do Tutor (API está no ar?): HTTPConnectionPool(host='127.0.0.1', port=8000): Read timed out.
2026-05-20 22:02:27,020 - INFO - === INICIANDO BLOCO: PT (Coluna: pergunta_pt) ===
2026-05-20 22:02:27,021 - INFO - [PT] Processando Q1/4 | Cap: 1. Analog and Digital
2026-05-20 22:03:41,340 - INFO - [PT] Processando Q2/4 | Cap: 1. Analog and Digital
2026-05-20 22:05:03,293 - INFO - [PT] Processando Q3/4 | Cap: 1. Analog and Digital
2026-05-20 22:06:35,794 - INFO - [PT] Processando Q4/4 | Cap: 1. Analog and Digital
2026-05-20 22:08:34,652 - INFO - Benchmark concluído com sucesso! Salvo em: resultados_brutos/geracao_tutor_gpt-5_pergunta_pt.csv

In [13]:
import pandas as pd

caminho_dataset1 = "resultados_brutos/geracao_tutor_gpt-5_pergunta_pt_V1.csv"
#caminho_dataset2 = "resultados_brutos/geracao_tutor_gpt-5_pergunta_pt_V2.csv"
#caminho_dataset3 = "resultados_brutos/geracao_tutor_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_V3_NoCache.csv"

# Deixar o pandas detectar automaticamente o delimitador
df_1_tutor_comercial = pd.read_csv(caminho_dataset1)
#df_2_tutor_comercial = pd.read_csv(caminho_dataset2)
#df_3_tutor_local_no_cache = pd.read_csv(caminho_dataset3)

In [14]:
df_1_tutor_comercial.head()

,Idioma,Interferencia_Tutor,Capitulo,Num_Questao,Pergunta,Modelo,Resposta_Gerada,Latencia_Total_s,TTFT_s,ITL_s,Throughput_tps,Tokens_In,Tokens_Out,Tokens_Total
0,PT,SIM,1. Analog and Digital,1.0,Ambos em tempo contínuo $x(t)$ e o tempo discr...,gpt-5,"Ideia-chave\n- Em tempo contínuo, $x(t)$ está ...",73.8159,67.5590,0.0158,63.45,89,398,487
1,PT,SIM,1. Analog and Digital,2.0,Um ADC usa $b=8$ bits por amostra e frequência...,gpt-5,a) Taxa de bits\n\nA taxa de bits é o número d...,81.4496,67.9986,0.0534,18.73,80,253,333
2,PT,SIM,1. Analog and Digital,5.0,O sinal analógico $x(t)=2t$ ~V é digitalizado ...,gpt-5,NaN,91.9974,0.0000,0.0000,0.00,120,1,121
3,PT,SIM,1. Analog and Digital,13.0,Um sinal analógico $x(t)$ foi amostrado period...,gpt-5,NaN,118.3552,0.0000,0.0000,0.00,114,1,115

In [ ]:
# df_1_tutor_comercial.iloc[[0, 1, 2, 3], 6] == df_2_tutor_comercial.iloc[[0, 1, 2, 3], 6]

## **1.5 - Modelo Bruto Comercial (DeepSeek)**

In [4]:
# Célula 2: Configuração interativa
# Permite escolher configurações diretamente no notebook

# 1. Tipo de teste: "bruto" ou "tutor"
TIPO_TESTE_CHOICE = "bruto"

# 2. Modelo a ser usado
MODELO_CHOICE = "deepseek-reasoner"

# 3. Configuração das colunas a processar (NOVO!)
# Escolha UMA das opções abaixo:

# Opção A: Apenas Português
COLUNAS_CHOICE = [("PT", "pergunta_pt")]

# Opção B: Apenas Inglês
# COLUNAS_CHOICE = [("EN", "pergunta_en")]

# Opção C: Ambos (Português e Inglês)
# COLUNAS_CHOICE = [("PT", "pergunta_pt"), ("EN", "pergunta_en")]

# Opção D: Coluna customizada (altere conforme necessidade)
# COLUNAS_CHOICE = [("ES", "pergunta_es")]  # Exemplo para espanhol

In [5]:
# Sobrescrever as configurações do módulo
gerador_respostas_2.TIPO_TESTE = TIPO_TESTE_CHOICE
gerador_respostas_2.MODELO_ATIVO = MODELO_CHOICE
gerador_respostas_2.COLUNAS_PROCESSAR = COLUNAS_CHOICE

print(f"✅ Configuração definida:")
print(f"   - Tipo de teste: {TIPO_TESTE_CHOICE}")
print(f"   - Modelo: {MODELO_CHOICE}")
print(f"   - Colunas a processar: {COLUNAS_CHOICE}")

# Opcional: Verificar colunas disponíveis no dataset
print("\n📋 Verificando colunas disponíveis no dataset...")
try:
    gerador_respostas_2.listar_colunas_disponiveis()

    # Método 1: Ver o código fonte do método _build_streaming_kwargs
    source = inspect.getsource(gerador_respostas_2.BenchmarkRunner._build_streaming_kwargs)
    print("\nCódigo do método _build_streaming_kwargs:")
    print(source)

except:
    print("   Não foi possível listar colunas (arquivo pode não existir ainda)")

✅ Configuração definida:
   - Tipo de teste: bruto
   - Modelo: deepseek-reasoner
   - Colunas a processar: [('PT', 'pergunta_pt')]

📋 Verificando colunas disponíveis no dataset...
Colunas disponíveis no dataset:
  - material
  - capitulo
  - paginas
  - numero_questao
  - pergunta_en
  - qtd_caracteres_en
  - pergunta_pt
  - qtd_caracteres_pt

Código do método _build_streaming_kwargs:
    def _build_streaming_kwargs(self, prompt: str) -> Dict[str, Any]:
        kwargs = {
            "model": self.model_name,
            "messages": [{"role": "user", "content": prompt}],
            "seed": 42,
            "stream": True,
            "stream_options": {"include_usage": True}
        }
        model_lower = self.model_name.lower()

        # Lista de modelos que NÃO suportam temperature
        modelos_sem_temperature = ["o1", "o3", "gpt-5"]

        if not any(modelo in model_lower for modelo in modelos_sem_temperature):
            kwargs["temperature"] = 0.0
            print(f"[DEBUG] Enviando para API: seed={kwargs.get('seed')}, temp={kwargs.get('temperature')}")
        else:
            print(f"[DEBUG] Enviando para API: seed={kwargs.get('seed')}, temp=NÃO ENVIADO (modelo não suporta)")

        return kwargs

In [7]:
# Célula 3: Executar o benchmark (cuidado: pode demorar!)
print("\n🚀 Iniciando benchmark...")
print("⚠️  Isso pode levar vários minutos/horas dependendo da quantidade de perguntas...")
process_dataset()  # Descomente para executar

2026-05-20 23:23:16,585 - INFO - TESTE: BRUTO | MODELO: deepseek-reasoner
2026-05-20 23:23:16,586 - INFO - COLUNAS A PROCESSAR: [('PT', 'pergunta_pt')]
2026-05-20 23:23:16,631 - INFO - Aquecendo o modelo deepseek-reasoner (Cold Start)...

🚀 Iniciando benchmark...
⚠️  Isso pode levar vários minutos/horas dependendo da quantidade de perguntas...
[DEBUG] Enviando para API: seed=42, temp=0.0

2026-05-20 23:23:17,257 - INFO - HTTP Request: POST https://api.deepseek.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-20 23:23:17,807 - INFO - Aquecimento concluído. Prontos para as requisições.
2026-05-20 23:23:17,810 - INFO - === INICIANDO BLOCO: PT (Coluna: pergunta_pt) ===
2026-05-20 23:23:17,810 - INFO - [PT] Processando Q1/4 | Cap: 1. Analog and Digital

[DEBUG] Enviando para API: seed=42, temp=0.0

2026-05-20 23:23:18,367 - INFO - HTTP Request: POST https://api.deepseek.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-20 23:23:36,068 - INFO - [PT] Processando Q2/4 | Cap: 1. Analog and Digital

[DEBUG] Enviando para API: seed=42, temp=0.0

2026-05-20 23:23:36,642 - INFO - HTTP Request: POST https://api.deepseek.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-20 23:23:47,891 - INFO - [PT] Processando Q3/4 | Cap: 1. Analog and Digital

[DEBUG] Enviando para API: seed=42, temp=0.0

2026-05-20 23:23:48,517 - INFO - HTTP Request: POST https://api.deepseek.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-20 23:24:02,080 - INFO - [PT] Processando Q4/4 | Cap: 1. Analog and Digital

[DEBUG] Enviando para API: seed=42, temp=0.0

2026-05-20 23:24:02,688 - INFO - HTTP Request: POST https://api.deepseek.com/v1/chat/completions "HTTP/1.1 200 OK"
2026-05-20 23:24:46,184 - INFO - Benchmark concluído com sucesso! Salvo em: resultados_brutos/geracao_bruto_deepseek-reasoner_pergunta_pt.csv

In [9]:
import pandas as pd

caminho_dataset1 = "resultados_brutos/geracao_bruto_deepseek-reasoner_pergunta_pt_V1.csv"
caminho_dataset2 = "resultados_brutos/geracao_bruto_deepseek-reasoner_pergunta_pt_V2.csv"
#caminho_dataset3 = "resultados_brutos/geracao_tutor_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_V3_NoCache.csv"

# Deixar o pandas detectar automaticamente o delimitador
df_1_bruto_comercial = pd.read_csv(caminho_dataset1)
df_2_bruto_comercial = pd.read_csv(caminho_dataset2)
#df_3_tutor_local_no_cache = pd.read_csv(caminho_dataset3)

In [10]:
df_1_bruto_comercial.head()

,Idioma,Interferencia_Tutor,Capitulo,Num_Questao,Pergunta,Modelo,Resposta_Gerada,Latencia_Total_s,TTFT_s,ITL_s,Throughput_tps,Tokens_In,Tokens_Out,Tokens_Total
0,PT,NÃO,1. Analog and Digital,1.0,Ambos em tempo contínuo $x(t)$ e o tempo discr...,deepseek-reasoner,"a) Para o sinal de tempo contínuo \(x(t)\), de...",16.2974,14.4901,0.0010,993.77,138,1797,1935
1,PT,NÃO,1. Analog and Digital,2.0,Um ADC usa $b=8$ bits por amostra e frequência...,deepseek-reasoner,a) A taxa de bits é dada pelo produto da frequ...,11.1576,9.1887,0.0017,589.68,100,1162,1262
2,PT,NÃO,1. Analog and Digital,5.0,O sinal analógico $x(t)=2t$ ~V é digitalizado ...,deepseek-reasoner,**a)** As amostras sem quantização são obtidas...,17.0478,14.6923,0.0011,881.75,165,2078,2243
3,PT,NÃO,1. Analog and Digital,13.0,Um sinal analógico $x(t)$ foi amostrado period...,deepseek-reasoner,**a)** A expressão analítica de \(x(t)\) é a r...,30.5766,28.4928,0.0006,1627.39,173,3392,3565

In [12]:
df_1_bruto_comercial.iloc[[0, 1, 2, 3], 6]

0    a) Para o sinal de tempo contínuo \(x(t)\), de...
1    a) A taxa de bits é dada pelo produto da frequ...
2    **a)** As amostras sem quantização são obtidas...
3    **a)** A expressão analítica de \(x(t)\) é a r...
Name: Resposta_Gerada, dtype: object

In [13]:
df_2_bruto_comercial.iloc[[0, 1, 2, 3], 6]

0    a) Para o sinal de tempo contínuo \(x(t)\), qu...
1    a) A taxa de bits é dada pelo produto do númer...
2    a) As quatro primeiras amostras sem quantizaçã...
3    a) O período de amostragem é \(T_s = 2\) s. O ...
Name: Resposta_Gerada, dtype: object

In [11]:
df_1_bruto_comercial.iloc[[0, 1, 2, 3], 6] == df_2_bruto_comercial.iloc[[0, 1, 2, 3], 6]

0    False
1    False
2    False
3    False
Name: Resposta_Gerada, dtype: bool

## **1.6 - Modelo Tutor Comercial (DeepSeek)**

In [17]:
# Célula 2: Configuração interativa
# Permite escolher configurações diretamente no notebook

# 1. Tipo de teste: "bruto" ou "tutor"
TIPO_TESTE_CHOICE = "tutor"

# 2. Modelo a ser usado
MODELO_CHOICE = "deepseek-reasoner"

# 3. Configuração das colunas a processar (NOVO!)
# Escolha UMA das opções abaixo:

# Opção A: Apenas Português
COLUNAS_CHOICE = [("PT", "pergunta_pt")]

# Opção B: Apenas Inglês
# COLUNAS_CHOICE = [("EN", "pergunta_en")]

# Opção C: Ambos (Português e Inglês)
# COLUNAS_CHOICE = [("PT", "pergunta_pt"), ("EN", "pergunta_en")]

# Opção D: Coluna customizada (altere conforme necessidade)
# COLUNAS_CHOICE = [("ES", "pergunta_es")]  # Exemplo para espanhol

In [18]:
# Sobrescrever as configurações do módulo
gerador_respostas_2.TIPO_TESTE = TIPO_TESTE_CHOICE
gerador_respostas_2.MODELO_ATIVO = MODELO_CHOICE
gerador_respostas_2.COLUNAS_PROCESSAR = COLUNAS_CHOICE

print(f"✅ Configuração definida:")
print(f"   - Tipo de teste: {TIPO_TESTE_CHOICE}")
print(f"   - Modelo: {MODELO_CHOICE}")
print(f"   - Colunas a processar: {COLUNAS_CHOICE}")

# Opcional: Verificar colunas disponíveis no dataset
print("\n📋 Verificando colunas disponíveis no dataset...")
try:
    gerador_respostas_2.listar_colunas_disponiveis()

    # Método 1: Ver o código fonte do método _build_streaming_kwargs
    source = inspect.getsource(gerador_respostas_2.BenchmarkRunner._build_streaming_kwargs)
    print("\nCódigo do método _build_streaming_kwargs:")
    print(source)

except:
    print("   Não foi possível listar colunas (arquivo pode não existir ainda)")

✅ Configuração definida:
   - Tipo de teste: tutor
   - Modelo: deepseek-reasoner
   - Colunas a processar: [('PT', 'pergunta_pt')]

📋 Verificando colunas disponíveis no dataset...
Colunas disponíveis no dataset:
  - material
  - capitulo
  - paginas
  - numero_questao
  - pergunta_en
  - qtd_caracteres_en
  - pergunta_pt
  - qtd_caracteres_pt

Código do método _build_streaming_kwargs:
    def _build_streaming_kwargs(self, prompt: str) -> Dict[str, Any]:
        kwargs = {
            "model": self.model_name,
            "messages": [{"role": "user", "content": prompt}],
            "seed": 42,
            "stream": True,
            "stream_options": {"include_usage": True}
        }
        model_lower = self.model_name.lower()

        # Lista de modelos que NÃO suportam temperature
        modelos_sem_temperature = ["o1", "o3", "gpt-5"]

        if not any(modelo in model_lower for modelo in modelos_sem_temperature):
            kwargs["temperature"] = 0.0
            print(f"[DEBUG] Enviando para API: seed={kwargs.get('seed')}, temp={kwargs.get('temperature')}")
        else:
            print(f"[DEBUG] Enviando para API: seed={kwargs.get('seed')}, temp=NÃO ENVIADO (modelo não suporta)")

        return kwargs

In [19]:
# Célula 3: Executar o benchmark (cuidado: pode demorar!)
print("\n🚀 Iniciando benchmark...")
print("⚠️  Isso pode levar vários minutos/horas dependendo da quantidade de perguntas...")
process_dataset()  # Descomente para executar

2026-05-20 23:38:11,232 - INFO - TESTE: TUTOR | MODELO: deepseek-reasoner
2026-05-20 23:38:11,232 - INFO - COLUNAS A PROCESSAR: [('PT', 'pergunta_pt')]
2026-05-20 23:38:11,234 - INFO - Aquecendo o Tutor Inteligente...

🚀 Iniciando benchmark...
⚠️  Isso pode levar vários minutos/horas dependendo da quantidade de perguntas...

2026-05-20 23:38:20,186 - INFO - Aquecimento do Tutor concluído.
2026-05-20 23:38:20,189 - INFO - === INICIANDO BLOCO: PT (Coluna: pergunta_pt) ===
2026-05-20 23:38:20,190 - INFO - [PT] Processando Q1/4 | Cap: 1. Analog and Digital
2026-05-20 23:38:36,374 - INFO - [PT] Processando Q2/4 | Cap: 1. Analog and Digital
2026-05-20 23:38:52,761 - INFO - [PT] Processando Q3/4 | Cap: 1. Analog and Digital
2026-05-20 23:39:21,327 - INFO - [PT] Processando Q4/4 | Cap: 1. Analog and Digital
2026-05-20 23:39:45,502 - INFO - Benchmark concluído com sucesso! Salvo em: resultados_brutos/geracao_tutor_deepseek-reasoner_pergunta_pt.csv

In [20]:
df_1_bruto_comercial.head()

,Idioma,Interferencia_Tutor,Capitulo,Num_Questao,Pergunta,Modelo,Resposta_Gerada,Latencia_Total_s,TTFT_s,ITL_s,Throughput_tps,Tokens_In,Tokens_Out,Tokens_Total
0,PT,NÃO,1. Analog and Digital,1.0,Ambos em tempo contínuo $x(t)$ e o tempo discr...,deepseek-reasoner,"a) Para o sinal de tempo contínuo \(x(t)\), de...",16.2974,14.4901,0.0010,993.77,138,1797,1935
1,PT,NÃO,1. Analog and Digital,2.0,Um ADC usa $b=8$ bits por amostra e frequência...,deepseek-reasoner,a) A taxa de bits é dada pelo produto da frequ...,11.1576,9.1887,0.0017,589.68,100,1162,1262
2,PT,NÃO,1. Analog and Digital,5.0,O sinal analógico $x(t)=2t$ ~V é digitalizado ...,deepseek-reasoner,**a)** As amostras sem quantização são obtidas...,17.0478,14.6923,0.0011,881.75,165,2078,2243
3,PT,NÃO,1. Analog and Digital,13.0,Um sinal analógico $x(t)$ foi amostrado period...,deepseek-reasoner,**a)** A expressão analítica de \(x(t)\) é a r...,30.5766,28.4928,0.0006,1627.39,173,3392,3565

In [ ]:
#df_1_bruto_comercial.iloc[[0, 1, 2, 3], 6] == df_2_bruto_comercial.iloc[[0, 1, 2, 3], 6]

# **Avaliação dos Resultados Experimentais**

## **1 - Importação dos Datasets**

### **1.1 - `geracao_bruto_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt`**

In [10]:
import pandas as pd

df_tutor_Ministral8b = "resultados_brutos/geracao_tutor_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_pergunta_en_COMPLETO.csv"

# Deixar o pandas detectar automaticamente o delimitador
df_tutor_Ministral8b = pd.read_csv(df_tutor_Ministral8b)

df_tutor_Ministral8b.tail(60)

,Idioma,Interferencia_Tutor,Capitulo,Num_Questao,Pergunta,Modelo,Resposta_Gerada,Latencia_Total_s,TTFT_s,ITL_s,Throughput_tps,Tokens_In,Tokens_Out,Tokens_Total
60,EN,SIM,1. Analog and Digital,1.0,Both continuous-time $x(t)$ and the discrete-t...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n### Part (a...,14.4131,3.647227,10.765829,51.46,88,554,642
61,EN,SIM,1. Analog and Digital,2.0,An ADC uses $b=8$ bits per sample and sampling...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n**a) B...,11.4502,3.628144,7.822038,42.06,72,329,401
62,EN,SIM,1. Analog and Digital,5.0,The analog signal $x(t)=2t$~V is digitized usi...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...,23.4734,3.363369,20.110013,39.18,112,788,900
63,EN,SIM,1. Analog and Digital,13.0,An analog signal $x(t)$ was periodically sampl...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...,18.9140,4.946962,13.967088,54.63,109,763,872
64,EN,SIM,1. Analog and Digital,15.0,An $b=8$-bits ADC uses two's complement to out...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nBelow is a ...,27.8101,3.769225,24.040881,47.88,128,1151,1279
65,EN,SIM,1. Analog and Digital,16.0,A sinusoid $x[n]=\sin((\pi/3)n)$ was quantized...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...,37.5384,4.935651,32.602799,36.75,142,1198,1340
66,EN,SIM,1. Analog and Digital,17.0,The goal is to design a uniform scalar quantiz...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...,34.7019,4.494385,30.207532,45.98,106,1389,1495
67,EN,SIM,1. Analog and Digital,20.0,Consider you want to quantize a sinusoid with ...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n### Quantiz...,22.0446,3.602871,18.441742,39.20,108,723,831
68,EN,SIM,1. Analog and Digital,22.0,A data acquisition system uses an ADC of 12 bi...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe expecte...,10.6113,3.745415,6.865934,56.80,107,390,497
69,EN,SIM,1. Analog and Digital,23.0,An eight-bits ADC uses two's complement and th...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...,52.6249,3.378704,49.246160,46.91,125,2310,2435
70,EN,SIM,1. Analog and Digital,28.0,"You do not know much about a signal $x[n]$, bu...",cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"The answer to your question is: No, the signal...",5.8976,3.289447,2.608179,50.61,27,132,159
71,EN,SIM,1. Analog and Digital,29.0,"For the following signals, calculate the energ...",cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...,22.5706,6.636159,15.934434,53.41,56,851,907
72,EN,SIM,1. Analog and Digital,30.0,What can be said about the total energy and av...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nFor any per...,7.5538,3.176621,4.377216,58.94,20,258,278
73,EN,SIM,1. Analog and Digital,31.0,"a) The set $\calM = \{-7,-5,-3,-1,1,3,5,7\}$ d...",cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n**a)...,15.8226,3.576976,12.245597,49.90,132,611,743
74,EN,SIM,1. Analog and Digital,32.0,"For each of the following signals, determine w...",cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...,30.4498,4.250898,26.198852,48.25,65,1264,1329
75,EN,SIM,2. Transforms and Signal Representation,1.0,"Given two vectors $[4, 3]$ and $[-5, 2]$, find...",cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nGiven the v...,10.5126,4.109492,6.403070,45.76,24,293,317
76,EN,SIM,2. Transforms and Signal Representation,2.0,"Given two vectors $\bx=[4, 0]$ and $\by=[-5, 2...",cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...,17.9192,3.128181,14.791066,41.65,39,616,655
77,EN,SIM,2. Transforms and Signal Representation,3.0,Is the matrix $\bA =\n \begin{bmatrix}\n ...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo determin...,28.2127,4.849054,23.363680,42.12,60,984,1044
78,EN,SIM,2. Transforms and Signal Representation,4.0,Assume a 2-d vector space has non orthogonal b...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...,10.5994,3.312245,7.287154,58.46,67,426,493
79,EN,SIM,2. Transforms and Signal Representation,5.0,Use the Gram-Schmidt procedure to find an orth...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nBelow is a ...,18.5466,3.379529,15.167030,60.13,70,912,982
80,EN,SIM,2. Transforms and Signal Representation,10.0,What are the forward $\bA$ and inverse $\bA^H$...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe forward...,10.6218,3.812477,6.809336,48.32,21,329,350
81,EN,SIM,2. Transforms and Signal Representation,12.0,"Given that $\bX=[8,0,0,0]$ was obtained with a...",cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nGiven the 4...,13.5281,3.569815,9.958297,44.49,50,443,493
82,EN,SIM,2. Transforms and Signal Representation,14.0,Using the orthogonality condition of the basis...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo derive t...,22.3059,3.839607,18.466263,47.93,66,885,951
83,EN,SIM,2. Transforms and Signal Representation,15.0,What are the Fourier series coefficients for t...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...,18.6788,3.656481,15.022296,38.01,35,571,606
84,EN,SIM,2. Transforms and Signal Representation,16.0,The bilateral Fourier series of a signal $x(t)...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...,12.8716,3.869228,9.002354,41.10,50,370,420
85,EN,SIM,2. Transforms and Signal Representation,17.0,What is the Fourier transform of: a) $x(t) = \...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe Fourier...,15.6918,4.194219,11.497627,55.14,28,634,662
86,EN,SIM,2. Transforms and Signal Representation,18.0,What is the Fourier transform of: a) $x(t) = \...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...,16.9266,4.291923,12.634699,48.75,28,616,644
87,EN,SIM,2. Transforms and Signal Representation,19.0,Prove the expressions: a) for the DTFT of $x[n...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...,14.6798,4.514412,10.165415,39.35,30,400,430
88,EN,SIM,2. Transforms and Signal Representation,19.0,Prove the expressions: a) for the DTFT of $x[n...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...,14.6794,4.513497,10.165928,39.35,30,400,430
89,EN,SIM,2. Transforms and Signal Representation,20.0,"Considering the range $\dw \in \left[-\pi,\pi\...",cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...,16.9091,4.285024,12.624087,44.99,61,568,629
90,EN,SIM,2. Transforms and Signal Representation,21.0,Prove that $X(e^{j \dw})=\sum_{k=-\infty}^{\in...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo prove th...,14.1692,4.008754,10.160401,52.66,44,535,579
91,EN,SIM,2. Transforms and Signal Representation,24.0,A right-sided signal has Laplace transform $X(...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...,12.1778,3.440282,8.737514,44.18,58,386,444
92,EN,SIM,2. Transforms and Signal Representation,25.0,A signal $x(t)$ has Laplace transform $X(s)=(3...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...,16.8627,3.354389,13.508286,44.42,25,600,625
93,EN,SIM,2. Transforms and Signal Representation,26.0,A signal $x[n]$ has Z transform $X(z)=(5z^2+4z...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...,17.3968,3.436520,13.960304,42.19,25,589,614
94,EN,SIM,2. Transforms and Signal Representation,27.0,Find the Z transform and associated ROC of the...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...,14.7721,3.307138,11.464937,50.33,26,577,603
95,EN,SIM,2. Transforms and Signal Representation,28.0,What is the Z transform $X(z)$ of the signal $...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...,20.3950,6.190010,14.204950,42.24,57,600,657
96,EN,SIM,3. Analog and Digital Systems,1.0,When the input $x_1[n]=\delta[n] + \delta[n-1]...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo solve th...,11.4177,3.809086,7.608590,43.24,61,329,390
97,EN,SIM,3. Analog and Digital Systems,2.0,When the input $x_1[n]=\delta[n]$ is applied t...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nGiven the i...,10.3701,2.995670,7.374454,42.58,51,314,365
98,EN,SIM,3. Analog and Digital Systems,3.0,When the input $x_1[n]=\delta[n]$ is applied t...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is: To determine i...,29.0698,3.597508,25.472315,46.80,64,1192,1256
99,EN,SIM,3. Analog and Digital Systems,4.0,A time-invariant system has output $y_1(t) = \...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nGiven that ...,7.1666,3.110982,4.055577,53.01,49,215,264
100,EN,SIM,3. Analog and Digital Systems,5.0,The input-output relations that describe three...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nBelow is th...,29.2773,3.416261,25.861080,54.02,74,1397,1471
101,EN,SIM,3. Analog and Digital Systems,6.0,A discrete-time LTI is characterized by the di...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo determin...,30.6988,3.010182,27.688609,61.29,55,1697,1752
102,EN,SIM,3. Analog and Digital Systems,8.0,Four continuous-time signals: $x_1(t)=e^{j4t}$...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe problem...,40.5347,4.221603,36.313082,32.99,60,1198,1258
103,EN,SIM,3. Analog and Digital Systems,9.0,"Four discrete-time signals: $x_1[n]=5e^{j2n}$,...",cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo determin...,21.6450,4.698430,16.946592,41.66,65,706,771
104,EN,SIM,3. Analog and Digital Systems,12.0,A band-limited signal $x(t)$ was sampled obeyi...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe sampled...,10.0017,3.810023,6.191629,46.03,68,285,353
105,EN,SIM,3. Analog and Digital Systems,16.0,A non-causal analog lowpass filter has an idea...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo solve th...,20.3101,3.618429,16.691702,53.86,72,899,971
106,EN,SIM,3. Analog and Digital Systems,17.0,\item A FIR filter with linear phase has an im...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe system ...,8.3845,4.464731,3.919736,45.67,41,179,220
107,EN,SIM,3. Analog and Digital Systems,23.0,A filter $H(s) = \frac{125}{s^3+10s^2+50s+125}...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo obtain t...,22.9655,4.428775,18.536727,41.75,61,774,835
108,EN,SIM,3. Analog and Digital Systems,25.0,Given a filter $H(s)=(0.1s^2+71)/(s^2+11s+71)$...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find $H(...,22.1206,3.408886,18.711692,33.24,28,622,650
109,EN,SIM,3. Analog and Digital Systems,27.0,The filter $H_s(s)=(0.1s^2+71)/(s^2+11s+71)$ s...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...,33.6079,4.645968,28.961965,43.40,122,1257,1379
110,EN,SIM,3. Analog and Digital Systems,12.0,Study the advantages and disadvantages when co...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThe compari...,17.9491,3.726978,14.222152,73.48,24,1045,1069
111,EN,SIM,4. Spectral Estimation Techniques,2.0,A cosine $x[n]=A \cos(\dw_1 n)$ is multiplied ...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo solve th...,43.0347,4.686782,38.347889,39.82,112,1527,1639
112,EN,SIM,4. Spectral Estimation Techniques,3.0,Given the signal $x(t)= 12 \sinc(6 t)$ in volt...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo solve th...,21.7515,3.332532,18.419011,50.93,35,938,973
113,EN,SIM,4. Spectral Estimation Techniques,4.0,What is the MS spectrum $\hat S_{\textrm{ms}}[...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...,19.1443,4.459532,14.684738,43.58,48,640,688
114,EN,SIM,4. Spectral Estimation Techniques,5.0,Assume $X[k]$ is the $N$-point FFT of a period...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n---\n\n### ...,19.6213,3.425413,16.195884,35.69,90,578,668
115,EN,SIM,4. Spectral Estimation Techniques,6.0,"Assume $X=[8,8,8,8]$ is the $4$-point FFT of a...",cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nGiven the 4...,27.2898,6.313863,20.975944,45.62,75,957,1032
116,EN,SIM,4. Spectral Estimation Techniques,7.0,a) What is the PSD $S(e^{j \dw})$ of a complex...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\n### Part (a...,23.8537,4.538551,19.315128,51.31,78,991,1069
117,EN,SIM,4. Spectral Estimation Techniques,8.0,The periodogram of a sinusoid immersed in AWGN...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nThis proble...,16.1427,3.932638,12.210030,51.02,95,623,718
118,EN,SIM,4. Spectral Estimation Techniques,13.0,The unilateral PSD of a continuous-time white ...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nTo find the...,71.0354,4.741042,66.294353,48.90,128,3242,3370
119,EN,SIM,4. Spectral Estimation Techniques,2.0,Can a discrete-time random process $\calX[n]$ ...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The answer to your question is:\n\nA discrete-...,16.6784,3.311674,13.366678,68.75,35,919,954

In [11]:
df_tutor_Ministral8b.iloc[69, 6]

"The answer to your question is:\n\n---\n\n### a) Expected mean and variance of the quantization error\nThe quantization error is modeled as a uniformly distributed random variable with zero mean and variance given by the formula for the quantization noise power in the linear model:\n\n$$\n\\sigma^2_{eq} = \\frac{\\Delta^2}{12}\n$$\n\nwhere $\\Delta$ is the step size of the quantizer. For the **Q2.5** format, the step size $\\Delta$ is calculated as follows:\n\nThe dynamic range is $[-3, 3]$ V, which corresponds to $6$ V. The number of quantization levels is $2^b$, where $b$ is the number of bits in the fractional part plus the integer part. For **Q2.5**, the format has $2$ integer bits and $5$ fractional bits, totaling $7$ bits for the range (since the sign bit is implicit in two's complement). However, the **total number of bits** is $8$ (including the sign bit), but the **number of distinct levels** is $2^7 = 128$ (since the sign bit is implicit in two's complement and the remaining $7$ bits define the magnitude).\n\nThe step size $\\Delta$ is given by:\n\n$$\n\\Delta = \\frac{\\text{Dynamic Range}}{2^b_{\\text{fractional}} + 1}\n$$\n\nFor **Q2.5**, the fractional bits are $5$, and the integer bits are $2$. The total number of levels is $2^5 = 32$ (since the integer bits are already accounted for in the range). However, the correct formula for the step size in a **Qm.n** format is:\n\n$$\n\\Delta = \\frac{\\text{Dynamic Range}}{2^{n}}\n$$\n\nwhere $n$ is the number of fractional bits. For **Q2.5**, $n = 5$:\n\n$$\n\\Delta = \\frac{6}{2^5} = \\frac{6}{32} = 0.1875 \\text{ V}\n$$\n\nNow, the variance of the quantization error is:\n\n$$\n\\sigma^2_{eq} = \\frac{\\Delta^2}{12} = \\frac{(0.1875)^2}{12} = \\frac{0.03515625}{12} \\approx 0.00293 \\text{ V}^2\n$$\n\nThe **mean** of the quantization error is $0$ (as per the linear model).\n\n---\n\n### b) Estimated Signal-to-Quantization Noise Ratio (SQNR)\nThe SQNR is given by:\n\n$$\n\\text{SQNR} = \\frac{P_s}{P_n}\n$$\n\nwhere $P_s$ is the signal power and $P_n$ is the noise power (variance of the quantization error). For a uniform quantizer with a signal that spans the full range, the signal power $P_s$ is:\n\n$$\nP_s = \\frac{(\\text{Dynamic Range})^2}{12} = \\frac{6^2}{12} = \\frac{36}{12} = 3 \\text{ V}^2\n$$\n\nThe noise power is $\\sigma^2_{eq} \\approx 0.00293$ V$^2$ (from part a). Thus:\n\n$$\n\\text{SQNR} = \\frac{3}{0.00293} \\approx 1023.55\n$$\n\nTo express this in decibels (dB):\n\n$$\n\\text{SQNR (dB)} = 10 \\log_{10}(1023.55) \\approx 30.1 \\text{ dB}\n$$\n\n---\n\n### c) New SNR with Q3.4 and advantages\nFor the **Q3.4** format, the number of fractional bits is $4$. The step size $\\Delta$ is now:\n\n$$\n\\Delta = \\frac{6}{2^4} = \\frac{6}{16} = 0.375 \\text{ V}\n$$\n\nThe variance of the quantization error is:\n\n$$\n\\sigma^2_{eq} = \\frac{(0.375)^2}{12} = \\frac{0.140625}{12} \\approx 0.01172 \\text{ V}^2\n$$\n\nThe signal power remains the same ($P_s = 3$ V$^2$), so the new SQNR is:\n\n$$\n\\text{SQNR} = \\frac{3}{0.01172} \\approx 255.9\n$$\n\nIn decibels:\n\n$$\n\\text{SQNR (dB)} = 10 \\log_{10}(255.9) \\approx 24.1 \\text{ dB}\n$$\n\n**Wait, this seems incorrect!** Let's re-evaluate the calculation for **Q3.4** properly.\n\nFor **Q3.4**, the number of fractional bits is $4$, but the **total number of bits** is $8$ (including the sign bit). The **Q3.4** format means $3$ integer bits and $4$ fractional bits, so the total number of levels is $2^4 = 16$ (for the fractional part) and the step size is:\n\n$$\n\\Delta = \\frac{\\text{Dynamic Range}}{2^4} = \\frac{6}{16} = 0.375 \\text{ V}\n$$\n\nBut the **signal power** is not recalculated here because the dynamic range remains the same. The **SQNR** is recalculated using the new step size:\n\nThe **correct approach** is to use the formula for the **SQNR** in terms of the number of bits. The **Qm.n** format has a step size $\\Delta$ given by:\n\n$$\n\\Delta = \\frac{\\text{Dynamic Range}}{2^n}\n$$\n\nwhere $n$ is the number of fractional bits. The **SQNR** for a uniform quantizer is given by:\n\n$$\n\\text{SQNR (dB)} = 6.02 \\times b + 1.76 \\text{ dB}\n$$\n\nwhere $b$ is the **total number of bits** (including the sign bit). However, this formula is an approximation for the **total number of bits** in the ADC.\n\nFor **Q2.5**, the **total number of bits** is $8$ (including the sign bit), but the **effective number of bits** is $7$ (since the sign bit is implicit in two's complement). The **SQNR** is better calculated using the **linear model** as shown above.\n\nFor **Q3.4**, the **total number of bits** is still $8$, but the **fractional bits** are $4$. The **SQNR** is recalculated using the **new step size**:\n\nThe **SQNR** is given by:\n\n$$\n\\text{SQNR (dB)} = 10 \\log_{10} \\left( \\frac{P_s}{\\sigma^2_{eq}} \\right)\n$$\n\nwhere $\\sigma^2_{eq} = \\frac{\\Delta^2}{12}$ and $\\Delta = \\frac{6}{2^4} = 0.375$ V.\n\nThus:\n\n$$\n\\sigma^2_{eq} = \\frac{(0.375)^2}{12} = \\frac{0.140625}{12} \\approx 0.01172 \\text{ V}^2\n$$\n\nThe **SQNR** is:\n\n$$\n\\text{SQNR} = \\frac{3}{0.01172} \\approx 255.9\n$$\n\nIn decibels:\n\n$$\n\\text{SQNR (dB)} = 10 \\log_{10}(255.9) \\approx 24.1 \\text{ dB}\n$$\n\n**This is incorrect!** The **SQNR** should be higher for **Q3.4** than for **Q2.5** because the step size is smaller. Let's re-examine the **Q2.5** case.\n\nFor **Q2.5**, the **fractional bits** are $5$, so:\n\n$$\n\\Delta = \\frac{6}{2^5} = \\frac{6}{32} = 0.1875 \\text{ V}\n$$\n\nThe **SQNR** is:\n\n$$\n\\sigma^2_{eq} = \\frac{(0.1875)^2}{12} = \\frac{0.03515625}{12} \\approx 0.00293 \\text{ V}^2\n$$\n\nThe **SQNR** is:\n\n$$\n\\text{SQNR} = \\frac{3}{0.00293} \\approx 1023.55\n$$\n\nIn decibels:\n\n$$\n\\text{SQNR (dB)} = 10 \\log_{10}(1023.55) \\approx 30.1 \\text{ dB}\n$$\n\n**This is inconsistent with the expected result.** The **SQNR** should be higher for **Q2.5** than for **Q3.4** because **Q2.5** has more fractional bits, resulting in a smaller step size.\n\n**Correction:** The **Q2.5** format has **5 fractional bits**, while **Q3.4** has **4 fractional bits**. Therefore, **Q2.5** has a smaller step size and higher SQNR.\n\nFor **Q3.4**, the **step size** is:\n\n$$\n\\Delta = \\frac{6}{2^4} = 0.375 \\text{ V}\n$$\n\nThe **variance** is:\n\n$$\n\\sigma^2_{eq} = \\frac{(0.375)^2}{12} = \\frac{0.140625}{12} \\approx 0.01172 \\text{ V}^2\n$$\n\nThe **SQNR** is:\n\n$$\n\\text{SQNR} = \\frac{3}{0.01172} \\approx 255.9\n$$\n\nIn decibels:\n\n$$\n\\text{SQNR (dB)} = 10 \\log_{10}(255.9) \\approx 24.1 \\text{ dB}\n$$\n\n**This is still inconsistent.** The **SQNR** should be higher for **Q2.5** than for **Q3.4** because **Q2.5** has a smaller step size.\n\n**The correct approach is to use the formula for the SQNR in terms of the number of bits.** The **SQNR** for a uniform quantizer is given by:\n\n$$\n\\text{SQNR (dB)} = 6.02 \\times b + 1.76 \\text{ dB}\n$$\n\nwhere $b$ is the **total number of bits** (including the sign bit). However, this formula is an approximation for the **total number of bits** in the ADC.\n\nFor **Q2.5**, the **total number of bits** is $8$ (including the sign bit), but the **effective number of bits** is $7$ (since the sign bit is implicit in two's complement). The **SQNR** is better calculated using the **linear model** as shown above.\n\n**The correct SQNR for Q2.5** is:\n\n$$\n\\text{SQNR (dB)} = 10 \\log_{10} \\left( \\frac{3}{0.00293} \\right) \\approx 30.1 \\text{ dB}\n$$\n\n**The correct SQNR for Q3.4** is:\n\n$$\n\\text{SQNR (dB)} = 10 \\log_{10} \\left( \\frac{3}{0.01172} \\right) \\approx 24.1 \\text{ dB}\n$$\n\n**This is incorrect!** The **SQNR** should be higher for **Q2.5** than for **Q3.4** because **Q2.5** has a smaller step size.\n\n**The correct approach is to use the formula for the SQNR in terms of the number of bits.** The **SQNR** for a uniform quantizer is given by:\n\n$$\n\\text{SQNR (dB)} = 6.02 \\times b_{\\text{eff}} + 1.76 \\text{ dB}\n$$\n\nwhere $b_{\\text{eff}}$ is the **effective number of bits** (including the sign bit).\n\nFor **Q2.5**, the **effective number of bits** is $7$ (since the sign bit is implicit in two's complement and the remaining $7$ bits define the magnitude). For **Q3.4**, the **effective number of bits** is $7$ as well (since the sign bit is implicit and the remaining $7$ bits define the magnitude).\n\n**The correct SQNR** is calculated using the **linear model** as shown above.\n\n---\n\n### **Advantage of Q3.4 over Q2.5**\nThe **Q3.4** format has a **larger step size** than **Q2.5**, which means it has **lower resolution**. However, **Q3.4** has a **larger dynamic range** for the integer part, which can be useful if the signal has a **larger range of values** in the integer part.\n\nFor example, if the signal has a **larger range of values** in the integer part, **Q3.4** can represent it more accurately than **Q2.5**. However, if the signal has **small variations**, **Q2.5** is better because it has a **smaller step size** and thus **higher resolution**.\n\n---\n\n### References:\nFor more details, consult the following reference:\n**Book:** *Akkermans, D. J., & Bakkaloglu, B. (2017). Digital Signal Processing: A Practical Approach for Engineers and Scientists*\n**Chapter:** *Analog and Digital Signals*\n**Section:** *Advanced: A Linear Model for Quantization*\n**Page:** *1.63-1.64*\n\n---\nTo solve this problem, you can use the **linear model for quantization** and the **SQNR** formula provided in the book. The key is to calculate the **step size** and **variance of the quantization error** correctly for each format. For more details, refer to the section mentioned above."

### **1.2 - `geracao_tutor_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt`**

In [5]:
import pandas as pd

df_bruto_Ministral8b = "resultados_brutos/geracao_bruto_cyankiwi_Ministral-3-8B-Instruct-2512-AWQ-8bit_pergunta_pt_pergunta_en_COMPLETO.csv"

# Deixar o pandas detectar automaticamente o delimitador
df_bruto_Ministral8b = pd.read_csv(df_bruto_Ministral8b)

df_bruto_Ministral8b.tail(60)

,Idioma,Interferencia_Tutor,Capitulo,Num_Questao,Pergunta,Modelo,Resposta_Gerada,Latencia_Total_s,TTFT_s,ITL_s,Throughput_tps,Tokens_In,Tokens_Out,Tokens_Total
60,EN,NÃO,1. Analog and Digital,1.0,Both continuous-time $x(t)$ and the discrete-t...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze the problem step by step.\n\n###...,13.7465,0.042142,13.704331,69.03,118,946,1064
61,EN,NÃO,1. Analog and Digital,2.0,An ADC uses $b=8$ bits per sample and sampling...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's break down the problem step by step.\n\n...,9.1690,0.038941,9.130019,69.22,80,632,712
62,EN,NÃO,1. Analog and Digital,5.0,The analog signal $x(t)=2t$~V is digitized usi...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Part a: Sampling without Quantization\n\n*...,23.7833,0.054820,23.728499,68.48,144,1625,1769
63,EN,NÃO,1. Analog and Digital,13.0,An analog signal $x(t)$ was periodically sampl...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Part a) Finding the Analytic Expression of...,22.6457,0.054283,22.591372,68.52,144,1548,1692
64,EN,NÃO,1. Analog and Digital,15.0,An $b=8$-bits ADC uses two's complement to out...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Part a) Two's Complement Quantization\n\n*...,58.0592,0.055785,58.003384,67.05,165,3889,4054
65,EN,NÃO,1. Analog and Digital,16.0,A sinusoid $x[n]=\sin((\pi/3)n)$ was quantized...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's break down the problem step-by-step to f...,34.8170,0.055309,34.761738,67.95,164,2362,2526
66,EN,NÃO,1. Analog and Digital,17.0,The goal is to design a uniform scalar quantiz...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Part a) Design of a 3-bit Uniform Scalar Q...,33.7077,0.040847,33.666888,68.08,100,2292,2392
67,EN,NÃO,1. Analog and Digital,20.0,Consider you want to quantize a sinusoid with ...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### **Problem Breakdown and Solution**\n\nWe a...,19.6351,0.041198,19.593904,68.69,107,1346,1453
68,EN,NÃO,1. Analog and Digital,22.0,A data acquisition system uses an ADC of 12 bi...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To determine the improvement in the quantizati...,7.0563,0.041032,7.015306,69.28,101,486,587
69,EN,NÃO,1. Analog and Digital,23.0,An eight-bits ADC uses two's complement and th...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### **Part a) Expected Mean and Variance of th...,525.6699,0.040672,525.629199,56.83,127,29873,30000
70,EN,NÃO,1. Analog and Digital,28.0,"You do not know much about a signal $x[n]$, bu...",cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To determine whether the signal \( x[n] \) can...,3.2018,0.024418,3.177362,69.55,40,221,261
71,EN,NÃO,1. Analog and Digital,29.0,"For the following signals, calculate the energ...",cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze each signal one by one to determ...,18.5590,0.039174,18.519858,68.79,84,1274,1358
72,EN,NÃO,1. Analog and Digital,30.0,What can be said about the total energy and av...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To analyze the total energy and average power ...,7.0752,0.023462,7.051703,69.34,19,489,508
73,EN,NÃO,1. Analog and Digital,31.0,"a) The set $\calM = \{-7,-5,-3,-1,1,3,5,7\}$ d...",cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Part a) Average Energy in Joules\n\n**Unde...,32.1345,0.055820,32.078685,68.11,153,2185,2338
74,EN,NÃO,1. Analog and Digital,32.0,"For each of the following signals, determine w...",cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze each signal one by one to determ...,525.9684,0.040990,525.927381,56.83,109,29891,30000
75,EN,NÃO,2. Transforms and Signal Representation,1.0,"Given two vectors $[4, 3]$ and $[-5, 2]$, find...",cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze the problem step-by-step.\n\nWe ...,8.4838,0.023942,8.459899,69.27,32,586,618
76,EN,NÃO,2. Transforms and Signal Representation,2.0,"Given two vectors $\bx=[4, 0]$ and $\by=[-5, 2...",cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"To find the projections and error vectors, we'...",13.5564,0.026018,13.530374,69.10,55,935,990
77,EN,NÃO,2. Transforms and Signal Representation,3.0,Is the matrix $\bA =\n \begin{bmatrix}\n ...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"### Understanding the Problem\n\nFirst, I need...",44.1807,0.038845,44.141887,67.67,79,2987,3066
78,EN,NÃO,2. Transforms and Signal Representation,4.0,Assume a 2-d vector space has non orthogonal b...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the coefficients \(\alpha\) and \(\bet...,4.0427,0.038646,4.004057,69.43,78,278,356
79,EN,NÃO,2. Transforms and Signal Representation,5.0,Use the Gram-Schmidt procedure to find an orth...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"### Understanding the Problem\n\nFirst, I need...",36.5296,0.041683,36.487915,67.94,106,2479,2585
80,EN,NÃO,2. Transforms and Signal Representation,10.0,What are the forward $\bA$ and inverse $\bA^H$...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,The **3-point Discrete Fourier Transform (DFT)...,8.9036,0.023583,8.880060,69.26,29,615,644
81,EN,NÃO,2. Transforms and Signal Representation,12.0,"Given that $\bX=[8,0,0,0]$ was obtained with a...",cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Step-by-Step Solution:\n\n#### Part 1: Fin...,19.4428,0.026942,19.415886,68.76,62,1335,1397
82,EN,NÃO,2. Transforms and Signal Representation,14.0,Using the orthogonality condition of the basis...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To derive the pair of Fourier series equations...,21.1508,0.026158,21.124652,68.69,52,1451,1503
83,EN,NÃO,2. Transforms and Signal Representation,15.0,What are the Fourier series coefficients for t...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the Fourier series coefficients for th...,12.2478,0.038316,12.209458,69.13,66,844,910
84,EN,NÃO,2. Transforms and Signal Representation,16.0,The bilateral Fourier series of a signal $x(t)...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the expression for the signal \( x(t) ...,14.1482,0.039694,14.108515,69.04,86,974,1060
85,EN,NÃO,2. Transforms and Signal Representation,17.0,What is the Fourier transform of: a) $x(t) = \...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the Fourier transform of the given fun...,14.7298,0.026326,14.703472,69.03,57,1015,1072
86,EN,NÃO,2. Transforms and Signal Representation,18.0,What is the Fourier transform of: a) $x(t) = \...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the Fourier transform of the given fun...,14.2589,0.026250,14.232653,69.07,58,983,1041
87,EN,NÃO,2. Transforms and Signal Representation,19.0,Prove the expressions: a) for the DTFT of $x[n...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Part a) DTFT of \( x[n] = 0.9^n u[n] + 0.8...,14.1675,0.024550,14.142932,69.08,47,977,1024
88,EN,NÃO,2. Transforms and Signal Representation,19.0,Prove the expressions: a) for the DTFT of $x[n...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Part a) DTFT of \( x[n] = 0.9^n u[n] + 0.8...,14.1675,0.024369,14.143094,69.08,47,977,1024
89,EN,NÃO,2. Transforms and Signal Representation,20.0,"Considering the range $\dw \in \left[-\pi,\pi\...",cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the inverse Discrete-Time Fourier Tran...,14.1629,0.039640,14.123309,69.03,84,975,1059
90,EN,NÃO,2. Transforms and Signal Representation,21.0,Prove that $X(e^{j \dw})=\sum_{k=-\infty}^{\in...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To prove that the Discrete-Time Fourier Transf...,10.5627,0.038736,10.523946,69.18,71,728,799
91,EN,NÃO,2. Transforms and Signal Representation,24.0,A right-sided signal has Laplace transform $X(...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze the problem step-by-step.\n\n---...,13.3289,0.039294,13.289616,69.08,87,918,1005
92,EN,NÃO,2. Transforms and Signal Representation,25.0,A signal $x(t)$ has Laplace transform $X(s)=(3...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the inverse Laplace transform \( x(t) ...,11.5631,0.024654,11.538486,69.16,44,798,842
93,EN,NÃO,2. Transforms and Signal Representation,26.0,A signal $x[n]$ has Z transform $X(z)=(5z^2+4z...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the inverse Z-transform of the given s...,12.5697,0.026452,12.543217,69.12,57,867,924
94,EN,NÃO,2. Transforms and Signal Representation,27.0,Find the Z transform and associated ROC of the...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Step 1: Understanding the Signal\nThe give...,12.3184,0.024368,12.293988,69.14,35,850,885
95,EN,NÃO,2. Transforms and Signal Representation,28.0,What is the Z transform $X(z)$ of the signal $...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze the problem step-by-step.\n\n---...,22.8248,0.039666,22.785093,68.55,96,1562,1658
96,EN,NÃO,3. Analog and Digital Systems,1.0,When the input $x_1[n]=\delta[n] + \delta[n-1]...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"To solve this problem, we need to understand t...",6.6215,0.039566,6.581965,69.28,93,456,549
97,EN,NÃO,3. Analog and Digital Systems,2.0,When the input $x_1[n]=\delta[n]$ is applied t...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"To solve this problem, we need to determine th...",13.4910,0.039299,13.451709,69.06,86,929,1015
98,EN,NÃO,3. Analog and Digital Systems,3.0,When the input $x_1[n]=\delta[n]$ is applied t...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To determine if the system is Linear Time-Inva...,15.3930,0.040796,15.352162,68.92,108,1058,1166
99,EN,NÃO,3. Analog and Digital Systems,4.0,A time-invariant system has output $y_1(t) = \...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To determine the output \( y_2(t) \) of the ti...,5.2430,0.038624,5.204343,69.37,72,361,433
100,EN,NÃO,3. Analog and Digital Systems,5.0,The input-output relations that describe three...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze each of the three systems one by...,27.5089,0.042904,27.466001,68.38,117,1878,1995
101,EN,NÃO,3. Analog and Digital Systems,6.0,A discrete-time LTI is characterized by the di...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To determine a value for \( n_0 \) that makes ...,32.6974,0.038531,32.658912,68.16,72,2226,2298
102,EN,NÃO,3. Analog and Digital Systems,8.0,Four continuous-time signals: $x_1(t)=e^{j4t}$...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"To find the outputs \( y_1(t), y_2(t), y_3(t),...",41.7406,0.040446,41.700116,67.72,99,2824,2923
103,EN,NÃO,3. Analog and Digital Systems,9.0,"Four discrete-time signals: $x_1[n]=5e^{j2n}$,...",cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"To find the outputs \( y_1[n], y_2[n], y_3[n],...",27.3126,0.041112,27.271520,68.39,111,1865,1976
104,EN,NÃO,3. Analog and Digital Systems,12.0,A band-limited signal $x(t)$ was sampled obeyi...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the exact expression of the original b...,526.1566,0.039536,526.117093,56.85,89,29911,30000
105,EN,NÃO,3. Analog and Digital Systems,16.0,A non-causal analog lowpass filter has an idea...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Understanding the Problem\n\nWe are given ...,19.2152,0.040301,19.174909,68.74,89,1318,1407
106,EN,NÃO,3. Analog and Digital Systems,17.0,\item A FIR filter with linear phase has an im...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the system function \( H(z) \) of the ...,9.9248,0.026838,9.897982,69.21,56,685,741
107,EN,NÃO,3. Analog and Digital Systems,23.0,A filter $H(s) = \frac{125}{s^3+10s^2+50s+125}...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To obtain the filter \( G(s) \) that is a freq...,29.0410,0.040300,29.000736,68.34,96,1982,2078
108,EN,NÃO,3. Analog and Digital Systems,25.0,Given a filter $H(s)=(0.1s^2+71)/(s^2+11s+71)$...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,To find the discrete-time transfer function \(...,21.8899,0.026705,21.863209,68.65,53,1501,1554
109,EN,NÃO,3. Analog and Digital Systems,27.0,The filter $H_s(s)=(0.1s^2+71)/(s^2+11s+71)$ s...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Part a) Finding the Sampling Frequency \( ...,32.9071,0.056833,32.850272,68.04,175,2235,2410
110,EN,NÃO,3. Analog and Digital Systems,12.0,Study the advantages and disadvantages when co...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"When comparing **Butterworth**, **Chebyshev**,...",22.0098,0.023766,21.986031,68.68,21,1510,1531
111,EN,NÃO,4. Spectral Estimation Techniques,2.0,A cosine $x[n]=A \cos(\dw_1 n)$ is multiplied ...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze the problem step-by-step.\n\n---...,43.3094,0.055613,43.253805,67.62,155,2925,3080
112,EN,NÃO,4. Spectral Estimation Techniques,3.0,Given the signal $x(t)= 12 \sinc(6 t)$ in volt...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze the problem step-by-step.\n\nWe ...,15.8877,0.026492,15.861198,68.97,51,1094,1145
113,EN,NÃO,4. Spectral Estimation Techniques,4.0,What is the MS spectrum $\hat S_{\textrm{ms}}[...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Understanding the Problem\n\nWe are given ...,16.2591,0.038979,16.220163,68.93,72,1118,1190
114,EN,NÃO,4. Spectral Estimation Techniques,5.0,Assume $X[k]$ is the $N$-point FFT of a period...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's break down the problem step by step.\n\n...,18.5202,0.054557,18.465671,68.72,144,1269,1413
115,EN,NÃO,4. Spectral Estimation Techniques,6.0,"Assume $X=[8,8,8,8]$ is the $4$-point FFT of a...",cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze each part of the question step-b...,15.8750,0.041204,15.833813,68.90,109,1091,1200
116,EN,NÃO,4. Spectral Estimation Techniques,7.0,a) What is the PSD $S(e^{j \dw})$ of a complex...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,### Part a) Power Spectral Density (PSD) of th...,43.3075,0.041842,43.265667,67.67,108,2928,3036
117,EN,NÃO,4. Spectral Estimation Techniques,8.0,The periodogram of a sinusoid immersed in AWGN...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's analyze the problem step-by-step.\n\n---...,10.0446,0.040801,10.003837,69.17,121,692,813
118,EN,NÃO,4. Spectral Estimation Techniques,13.0,The unilateral PSD of a continuous-time white ...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,Let's break down the problem step-by-step to f...,19.9131,0.055392,19.857686,68.64,151,1363,1514
119,EN,NÃO,4. Spectral Estimation Techniques,2.0,Can a discrete-time random process $\calX[n]$ ...,cyankiwi/Ministral-3-8B-Instruct-2512-AWQ-8bit,"### Understanding the Problem\n\nFirst, let's ...",28.9350,0.024652,28.910348,68.42,33,1978,2011

In [9]:
df_bruto_Ministral8b.iloc[69, 6]

"### **Part a) Expected Mean and Variance of the Quantization Error**\n\n**Given:**\n- **ADC Resolution:** 8 bits\n- **Quantization Format:** Two's complement with **Q2.5** (fractional bits: 2 integer, 5 fractional)\n- **Input Range:** \\([-3, 3]\\) V (uniform quantization)\n- **Quantization Method:** Rounding (midrise quantization)\n\n**Step 1: Determine the Quantization Step Size (\\( \\Delta \\))**\nThe total number of quantization levels in an 8-bit two's complement ADC is \\( 2^8 = 256 \\), but the range is \\([-3, 3]\\) V, which spans \\( 6 \\) V.\n\nHowever, in **Q2.5**, the ADC represents numbers as:\n\\[\nV = \\text{sign} \\times (b_1 b_0 . b_{-1} b_{-2} b_{-3} b_{-4} b_{-5}) \\times \\Delta\n\\]\nwhere:\n- \\( b_1, b_0 \\) are the 2 integer bits.\n- \\( b_{-1} \\) to \\( b_{-5} \\) are the 5 fractional bits.\n- The total number of distinct levels is \\( 2^8 = 256 \\), but the range is \\([-3, 3]\\) V.\n\nThe **step size (\\( \\Delta \\))** is calculated as:\n\\[\n\\Delta = \\frac{\\text{Full Scale Range}}{2^N} = \\frac{6 \\text{ V}}{256} = \\frac{6}{256} = \\frac{3}{128} \\text{ V} \\approx 0.0234375 \\text{ V}\n\\]\n\n**Step 2: Quantization Error Model (Linear Model)**\nFor a uniform quantizer with rounding, the quantization error \\( e \\) is assumed to be uniformly distributed over \\([- \\Delta/2, \\Delta/2]\\).\n\n- **Mean of Quantization Error (\\( E[e] \\)):**\n  \\[\n  E[e] = 0 \\quad \\text{(since rounding is symmetric)}\n  \\]\n\n- **Variance of Quantization Error (\\( \\text{Var}(e) \\)):**\n  For uniform distribution over \\([- \\Delta/2, \\Delta/2]\\), the variance is:\n  \\[\n  \\text{Var}(e) = \\frac{\\Delta^2}{12}\n  \\]\n  Substituting \\( \\Delta = \\frac{3}{128} \\):\n  \\[\n  \\text{Var}(e) = \\frac{\\left(\\frac{3}{128}\\right)^2}{12} = \\frac{9}{128^2 \\times 12} = \\frac{9}{2048 \\times 12} = \\frac{9}{24576} \\approx 0.0003662 \\text{ V}^2\n  \\]\n\n**Final Answer for (a):**\n- **Mean of quantization error:** \\( \\boxed{0} \\)\n- **Variance of quantization error:** \\( \\boxed{\\dfrac{9}{24576} \\text{ V}^2} \\) (or approximately \\( 0.0003662 \\text{ V}^2 \\))\n\n---\n\n### **Part b) Estimated Signal-to-Quantization Noise Ratio (SQNR)**\n\n**Given:**\n- **Signal Range:** \\([-3, 3]\\) V → **RMS Signal (\\( V_{\\text{rms}} \\)):**\n  \\[\n  V_{\\text{rms}} = \\frac{3}{\\sqrt{3}} = \\sqrt{3} \\text{ V} \\quad \\text{(since RMS of uniform signal over }[-3, 3]\\text{ is } \\frac{\\text{peak}}{\\sqrt{3}})\n  \\]\n  However, for a **uniformly distributed signal** over \\([-3, 3]\\), the RMS is:\n  \\[\n  V_{\\text{rms}} = \\sqrt{\\frac{1}{6} \\int_{-3}^{3} x^2 \\, dx} = \\sqrt{\\frac{1}{6} \\left[ \\frac{x^3}{3} \\right]_{-3}^{3}} = \\sqrt{\\frac{1}{6} \\left( \\frac{27}{3} - \\frac{-27}{3} \\right)} = \\sqrt{\\frac{1}{6} \\times 18} = \\sqrt{3} \\text{ V}\n  \\]\n\n- **Quantization Noise Power (\\( \\sigma_e^2 \\)):**\n  \\[\n  \\sigma_e^2 = \\frac{\\Delta^2}{12} = \\frac{9}{24576} \\text{ V}^2\n  \\]\n\n- **SQNR (in dB):**\n  \\[\n  \\text{SQNR} = 10 \\log_{10} \\left( \\frac{V_{\\text{rms}}^2}{\\sigma_e^2} \\right) = 10 \\log_{10} \\left( \\frac{3}{\\frac{9}{24576}} \\right) = 10 \\log_{10} \\left( \\frac{3 \\times 24576}{9} \\right)\n  \\]\n  \\[\n  = 10 \\log_{10} \\left( \\frac{73728}{9} \\right) = 10 \\log_{10} (8192) = 10 \\times 3.913 = 39.13 \\text{ dB}\n  \\]\n\n**Final Answer for (b):**\n- **SQNR:** \\( \\boxed{39.13 \\text{ dB}} \\)\n\n---\n\n### **Part c) New SNR with Q3.4 and Advantage Over Q2.5**\n\n**Given:**\n- **New Format:** **Q3.4** (3 integer bits, 4 fractional bits)\n- **Total Bits:** Still 8 bits (since \\( 3 + 4 = 7 \\) is incorrect; likely **Q3.4** means **3 integer + 4 fractional**, but total bits must be 8, so this is ambiguous. Assuming **Q3.4** means **3 integer + 4 fractional**, but 8-bit ADC implies \\( 2^8 = 256 \\) levels, but the range is still \\([-3, 3]\\) V.\n\n**Clarification:**\nIn **Q3.4**, the ADC represents numbers as:\n\\[\nV = \\text{sign} \\times (b_2 b_1 b_0 . b_{-1} b_{-2} b_{-3} b_{-4}) \\times \\Delta\n\\]\nBut the **total number of levels** is still \\( 2^8 = 256 \\), but the **step size** changes because the **fractional bits** are fewer.\n\nHowever, the **range** is still \\([-3, 3]\\) V, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut **Q3.4** implies that the **fractional resolution** is higher (more bits), but the **total levels** remain the same.\n\n**Reinterpretation:**\nIf **Q3.4** means **3 integer + 4 fractional bits**, but the **total bits** are still 8 (since \\( 3 + 4 = 7 \\) is insufficient), this is likely a misstatement. Instead, **Q3.4** probably means **3 integer + 4 fractional bits**, but the **total bits** are **7**, which contradicts the 8-bit ADC.\n\n**Alternative Interpretation:**\nPerhaps **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is still 8-bit**, meaning the **sign bit** is included, and the **fractional bits** are 4, with **3 integer bits** (total \\( 1 + 3 + 4 = 8 \\) bits).\n\nBut the **step size** is still:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nThis is the same as **Q2.5**, which doesn't make sense.\n\n**Correct Interpretation:**\nThe **Q3.4** format likely means **3 integer + 4 fractional bits**, but the **total bits** are **7** (excluding sign), but the ADC is **8-bit**, so this is confusing.\n\n**Assuming Q3.4 means 3 integer + 4 fractional bits (total 7 bits + sign = 8 bits):**\nThe **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is incorrect.\n\n**Alternative Approach:**\nPerhaps **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not helpful.\n\n**Re-evaluating:**\nThe **Q3.4** format likely means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Conclusion:**\nThe **Q3.4** format likely means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not possible.\n\n**Correct Interpretation:**\nThe **Q3.4** format likely means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Clarification:**\nThe **Q3.4** format likely means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not possible.\n\n**Alternative Solution:**\nPerhaps **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Correct Approach:**\nThe **Q3.4** format likely means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not possible.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Alternative Interpretation:**\nPerhaps **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Conclusion:**\nThe **Q3.4** format likely means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Correct Interpretation:**\nThe **Q3.4** format likely means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Alternative Approach:**\nPerhaps **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Conclusion:**\nThe **Q3.4** format likely means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assume **Q3.4** means **3 integer + 4 fractional bits**, but the **ADC is 8-bit**, so the **step size** is:\n\\[\n\\Delta = \\frac{6 \\text{ V}}{256} = \\frac{3}{128} \\text{ V}\n\\]\nBut this is the same as **Q2.5**, which is not correct.\n\n**Final Answer:**\nGiven the confusion, let's assum

In [12]:
import pandas as pd

df_bruto_gpt_5 = "resultados_brutos/geracao_bruto_gpt-5_pergunta_pt_pergunta_en_COMPLETO.csv"

# Deixar o pandas detectar automaticamente o delimitador
df_bruto_gpt_5 = pd.read_csv(df_bruto_gpt_5)

df_bruto_gpt_5.tail(60)

,Idioma,Interferencia_Tutor,Capitulo,Num_Questao,Pergunta,Modelo,Resposta_Gerada,Latencia_Total_s,TTFT_s,ITL_s,Throughput_tps,Tokens_In,Tokens_Out,Tokens_Total
60,EN,NÃO,1. Analog and Digital,1.0,Both continuous-time $x(t)$ and the discrete-t...,gpt-5,a) Continuous-time pulse:\n- x(1.5) = 3\n- x(3...,8.1147,7.453807,0.660845,1201.49,124,794,918
61,EN,NÃO,1. Analog and Digital,2.0,An ADC uses $b=8$ bits per sample and sampling...,gpt-5,a) Bit rate Rb = b × fs = 8 × 100×10^6 = 8×10^...,19.9859,18.972540,1.013368,1157.53,80,1173,1253
62,EN,NÃO,1. Analog and Digital,5.0,The analog signal $x(t)=2t$~V is digitized usi...,gpt-5,a) Sampling at fs = 100 Hz gives t_n = n/100 s...,15.7243,13.802757,1.921544,838.91,149,1612,1761
63,EN,NÃO,1. Analog and Digital,13.0,An analog signal $x(t)$ was periodically sampl...,gpt-5,"a) For uniform impulse sampling, xs(t) = Σk x(...",48.9344,45.133824,3.800534,1090.11,148,4143,4291
64,EN,NÃO,1. Analog and Digital,15.0,An $b=8$-bits ADC uses two's complement to out...,gpt-5,Given Δ = 10 mV = 0.01 V.\n\nUse a mid‑tread u...,45.2318,39.165987,6.065825,608.82,164,3693,3857
65,EN,NÃO,1. Analog and Digital,16.0,A sinusoid $x[n]=\sin((\pi/3)n)$ was quantized...,gpt-5,"- x[n] over one period (n = 0…5): [0, √3/2, √3...",68.7411,66.736672,2.004476,3319.07,173,6653,6826
66,EN,NÃO,1. Analog and Digital,17.0,The goal is to design a uniform scalar quantiz...,gpt-5,a) 3-bit uniform quantizer (L = 8 levels) matc...,53.4474,48.561005,4.886391,1028.78,105,5027,5132
67,EN,NÃO,1. Analog and Digital,20.0,Consider you want to quantize a sinusoid with ...,gpt-5,Assume a uniform b-bit quantizer whose full-sc...,42.4364,34.994308,7.442115,525.93,111,3914,4025
68,EN,NÃO,1. Analog and Digital,22.0,A data acquisition system uses an ADC of 12 bi...,gpt-5,About 24 dB.\n\nReason: Each extra bit improve...,18.1410,17.661824,0.479201,2172.37,102,1041,1143
69,EN,NÃO,1. Analog and Digital,23.0,An eight-bits ADC uses two's complement and th...,gpt-5,"a) For a uniform rounding quantizer, under the...",107.3768,103.632349,3.744468,2526.66,134,9461,9595
70,EN,NÃO,1. Analog and Digital,28.0,"You do not know much about a signal $x[n]$, bu...",gpt-5,"No. For an odd signal, x[-n] = -x[n] for all n...",4.7848,4.336645,0.448141,743.07,44,333,377
71,EN,NÃO,1. Analog and Digital,29.0,"For the following signals, calculate the energ...",gpt-5,Definitions\n- Energy: E∞ = ∫_{-∞}^{∞} |x(t)|^...,14.4940,10.743203,3.750753,364.73,88,1368,1456
72,EN,NÃO,1. Analog and Digital,30.0,What can be said about the total energy and av...,gpt-5,- Total energy: Infinite for any nonzero perio...,21.4586,19.479828,1.978723,821.24,22,1625,1647
73,EN,NÃO,1. Analog and Digital,31.0,"a) The set $\calM = \{-7,-5,-3,-1,1,3,5,7\}$ d...",gpt-5,a) Average energy:\n- Mean-square of the level...,19.4983,17.014849,2.483404,762.66,156,1894,2050
74,EN,NÃO,1. Analog and Digital,32.0,"For each of the following signals, determine w...",gpt-5,a) x[n] = u[n] + u[-n-1]\n- Since u[n]=1 for n...,21.9025,20.089798,1.812656,1252.31,110,2270,2380
75,EN,NÃO,2. Transforms and Signal Representation,1.0,"Given two vectors $[4, 3]$ and $[-5, 2]$, find...",gpt-5,"- Norms:\n - ||[4, 3]|| = sqrt(4^2 + 3^2) = 5...",19.0826,18.145105,0.937446,1674.76,37,1570,1607
76,EN,NÃO,2. Transforms and Signal Representation,2.0,"Given two vectors $\bx=[4, 0]$ and $\by=[-5, 2...",gpt-5,- Projection of y onto x: p_yx = ((y·x)/(x·x))...,9.6581,8.472791,1.185331,678.29,60,804,864
77,EN,NÃO,2. Transforms and Signal Representation,3.0,Is the matrix $\bA =\n \begin{bmatrix}\n ...,gpt-5,No. A is not unitary because its columns are n...,18.9802,17.566251,1.413976,1117.42,91,1580,1671
78,EN,NÃO,2. Transforms and Signal Representation,4.0,Assume a 2-d vector space has non orthogonal b...,gpt-5,"We want α and β such that:\n[4, 1] = α[2, 1] +...",7.1872,6.261343,0.925829,397.48,89,368,457
79,EN,NÃO,2. Transforms and Signal Representation,5.0,Use the Gram-Schmidt procedure to find an orth...,gpt-5,Let the inner product be the usual dot product...,20.0219,15.481568,4.540342,462.30,111,2099,2210
80,EN,NÃO,2. Transforms and Signal Representation,10.0,What are the forward $\bA$ and inverse $\bA^H$...,gpt-5,Let ω = e^(−j 2π/3) = −1/2 − j√3/2 and ω^2 = e...,29.6700,26.573044,3.096965,977.73,34,3028,3062
81,EN,NÃO,2. Transforms and Signal Representation,12.0,"Given that $\bX=[8,0,0,0]$ was obtained with a...",gpt-5,- Inverse (time-domain) sequence:\n Since the...,18.0498,16.351604,1.698217,1023.43,66,1738,1804
82,EN,NÃO,2. Transforms and Signal Representation,14.0,Using the orthogonality condition of the basis...,gpt-5,Let x(t) be T-periodic with fundamental ω0 = 2...,22.3910,18.371509,4.019449,574.21,56,2308,2364
83,EN,NÃO,2. Transforms and Signal Representation,15.0,What are the Fourier series coefficients for t...,gpt-5,"Fundamental frequency: f0 = 50 Hz, ω0 = 2πf0 =...",20.3838,18.520878,1.862900,1093.99,64,2038,2102
84,EN,NÃO,2. Transforms and Signal Representation,16.0,The bilateral Fourier series of a signal $x(t)...,gpt-5,x(t) = 3 + 4 cos(200π t − 4) + 10 cos(800π t)\...,14.6676,13.930652,0.736926,1608.03,91,1185,1276
85,EN,NÃO,2. Transforms and Signal Representation,17.0,What is the Fourier transform of: a) $x(t) = \...,gpt-5,Assume the continuous-time Fourier transform X...,33.1010,29.807952,3.293069,663.51,61,2185,2246
86,EN,NÃO,2. Transforms and Signal Representation,18.0,What is the Fourier transform of: a) $x(t) = \...,gpt-5,Assume the Fourier transform X(f) = ∫ x(t) e^{...,21.9382,20.454795,1.483452,1490.44,62,2211,2273
87,EN,NÃO,2. Transforms and Signal Representation,19.0,Prove the expressions: a) for the DTFT of $x[n...,gpt-5,"Let x[n] = 0.9^n u[n] + 0.8^n u[n], with u[n] ...",18.9359,15.546566,3.389368,622.24,53,2109,2162
88,EN,NÃO,2. Transforms and Signal Representation,19.0,Prove the expressions: a) for the DTFT of $x[n...,gpt-5,Let u[n] be the unit-step sequence. Use linear...,18.7821,15.145645,3.636449,538.71,53,1959,2012
89,EN,NÃO,2. Transforms and Signal Representation,20.0,"Considering the range $\dw \in \left[-\pi,\pi\...",gpt-5,Let H(e^{jω}) be the ideal low-pass response o...,21.0655,16.907909,4.157553,508.95,91,2116,2207
90,EN,NÃO,2. Transforms and Signal Representation,21.0,Prove that $X(e^{j \dw})=\sum_{k=-\infty}^{\in...,gpt-5,Let ω denote the frequency variable (your dw)....,41.4433,37.433086,4.010244,993.46,79,3984,4063
91,EN,NÃO,2. Transforms and Signal Representation,24.0,A right-sided signal has Laplace transform $X(...,gpt-5,"Given X(s) = 5/(s^2 + 2s + 10), poles at s = -...",20.2394,18.445669,1.793772,1008.49,93,1809,1902
92,EN,NÃO,2. Transforms and Signal Representation,25.0,A signal $x(t)$ has Laplace transform $X(s)=(3...,gpt-5,Poles at s=1 and s=3. With ROC Re(s) < 1 (to t...,36.4689,34.657074,1.811826,1176.16,50,2131,2181
93,EN,NÃO,2. Transforms and Signal Representation,26.0,A signal $x[n]$ has Z transform $X(z)=(5z^2+4z...,gpt-5,"Given ROC |z| > 0.8 (right-sided), do partial ...",87.8283,87.174965,0.653347,13282.37,63,8678,8741
94,EN,NÃO,2. Transforms and Signal Representation,27.0,Find the Z transform and associated ROC of the...,gpt-5,x[n] = -3^n u[-n-1] is nonzero for n ≤ -1.\n\n...,35.8483,34.275934,1.572410,2472.00,38,3887,3925
95,EN,NÃO,2. Transforms and Signal Representation,28.0,What is the Z transform $X(z)$ of the signal $...,gpt-5,- Z-transform:\n X(z) = 4 + 5 z^{-11}\n ROC:...,23.2092,21.384103,1.825093,1185.69,101,2164,2265
96,EN,NÃO,3. Analog and Digital Systems,1.0,When the input $x_1[n]=\delta[n] + \delta[n-1]...,gpt-5,Because the system is linear and x2[n] = 3 x1[...,6.4992,5.069425,1.429774,230.81,102,330,432
97,EN,NÃO,3. Analog and Digital Systems,2.0,When the input $x_1[n]=\delta[n]$ is applied t...,gpt-5,h[n] = y1[n] = 3δ[n] + 2δ[n−1] + δ[n−2]. \nFo...,5.1466,4.464850,0.681733,819.97,96,559,655
98,EN,NÃO,3. Analog and Digital Systems,3.0,When the input $x_1[n]=\delta[n]$ is applied t...,gpt-5,"No. For an LTI system, the response to δ[n] is...",11.0765,9.234297,1.842189,614.49,118,1132,1250
99,EN,NÃO,3. Analog and Digital Systems,4.0,A time-invariant system has output $y_1(t) = \...,gpt-5,y2(t) = y1(t − 3) = δ(t − 4) − δ(t − 7)\n\nRea...,6.4701,5.944288,0.525823,1114.44,78,586,664
100,EN,NÃO,3. Analog and Digital Systems,5.0,The input-output relations that describe three...,gpt-5,"System 1: y[n] = C (x[n])^2, C = 2e^{jπ/2}\n- ...",14.4219,12.143598,2.278288,617.13,122,1406,1528
101,EN,NÃO,3. Analog and Digital Systems,6.0,A discrete-time LTI is characterized by the di...,gpt-5,n0 ≤ 2. \n\nReason: Rewrite with k = n+2 → y[k...,8.5415,7.722394,0.819119,1146.35,77,939,1016
102,EN,NÃO,3. Analog and Digital Systems,8.0,Four continuous-time signals: $x_1(t)=e^{j4t}$...,gpt-5,For the causal LTI system H(s) = 1/(s+10) with...,35.8198,33.191829,2.628008,1548.32,107,4069,4176
103,EN,NÃO,3. Analog and Digital Systems,9.0,"Four discrete-time signals: $x_1[n]=5e^{j2n}$,...",gpt-5,Key fact: For a causal LTI system with H(z) = ...,77.4482,67.545886,9.902330,606.93,118,6010,6128
104,EN,NÃO,3. Analog and Digital Systems,12.0,A band-limited signal $x(t)$ was sampled obeyi...,gpt-5,x(t) = 4 sinc(10 t) + 3 sinc(10 t − 1) − 2 sin...,33.3097,32.172078,1.137671,1386.16,94,1577,1671
105,EN,NÃO,3. Analog and Digital Systems,16.0,A non-causal analog lowpass filter has an idea...,gpt-5,Passband is |ω| ≤ 5 rad/s with H(jω) = e^{-j8ω...,20.9612,19.096178,1.865039,853.60,99,1592,1691
106,EN,NÃO,3. Analog and Digital Systems,17.0,\item A FIR filter with linear phase has an im...,gpt-5,H(z) is the Z-transform of h[n]:\nH(z) = 3 − 5...,47.4135,45.379201,2.034329,1369.98,65,2787,2852
107,EN,NÃO,3. Analog and Digital Systems,23.0,A filter $H(s) = \frac{125}{s^3+10s^2+50s+125}...,gpt-5,"Frequency-scale H(s) by a = ω_old/ω_new = 5/3,...",69.8146,67.733676,2.080952,1989.47,92,4140,4232
108,EN,NÃO,3. Analog and Digital Systems,25.0,Given a filter $H(s)=(0.1s^2+71)/(s^2+11s+71)$...,gpt-5,Use the bilinear transform s = (2/T) (1 − z⁻¹)...,75.6562,71.640853,4.015324,1399.64,53,5620,5673
109,EN,NÃO,3. Analog and Digital Systems,27.0,The filter $H_s(s)=(0.1s^2+71)/(s^2+11s+71)$ s...,gpt-5,Given the bilinear mapping Ω = 2 Fs tan(ω/2):\...,94.7462,88.483305,6.262928,868.76,178,5441,5619
110,EN,NÃO,3. Analog and Digital Systems,12.0,Study the advantages and disadvantages when co...,gpt-5,"Here’s a concise, practical comparison of the ...",33.2258,21.848186,11.377647,202.50,24,2304,2328
111,EN,NÃO,4. Spectral Estimation Techniques,2.0,A cosine $x[n]=A \cos(\dw_1 n)$ is multiplied ...,gpt-5,Assume the N-point DFT definition X[k] = Σ_{n=...,144.3353,140.047566,4.287781,2678.31,161,11484,11645
112,EN,NÃO,4. Spectral Estimation Techniques,3.0,Given the signal $x(t)= 12 \sinc(6 t)$ in volt...,gpt-5,Answer assumes sinc(u) = sin(πu)/(πu) and Four...,27.5486,25.859333,1.689244,1607.23,53,2715,2768
113,EN,NÃO,4. Spectral Estimation Techniques,4.0,What is the MS spectrum $\hat S_{\textrm{ms}}[...,gpt-5,- Period N0 = 8 because ω0 = π/4 and N0 = 2π/ω...,41.2050,38.855616,2.349396,1232.23,80,2895,2975
114,EN,NÃO,4. Spectral Estimation Techniques,5.0,Assume $X[k]$ is the $N$-point FFT of a period...,gpt-5,"a) For a periodic signal, the MS (mean-square/...",35.2785,32.188977,3.089529,1240.97,158,3834,3992
115,EN,NÃO,4. Spectral Estimation Techniques,6.0,"Assume $X=[8,8,8,8]$ is the $4$-point FFT of a...",gpt-5,"Given X = [8, 8, 8, 8] as the 4-point FFT (N=4...",76.0149,70.830646,5.184260,1282.15,120,6647,6767
116,EN,NÃO,4. Spectral Estimation Techniques,7.0,a) What is the PSD $S(e^{j \dw})$ of a complex...,gpt-5,"a) Let y[n] = x[n] w[n], with w[n] = 1 for n=0...",72.7660,69.225169,3.540847,1843.34,114,6527,6641
117,EN,NÃO,4. Spectral Estimation Techniques,8.0,The periodogram of a sinusoid immersed in AWGN...,gpt-5,"Given N=8 and fs=500 Hz, the bin width is Δf =...",22.2148,20.540896,1.673879,1227.69,125,2055,2180
118,EN,NÃO,4. Spectral Estimation Techniques,13.0,The unilateral PSD of a continuous-time white ...,gpt-5,P = g^2 × N0 × B = 3^2 × 4 W/Hz × 200 Hz = 720...,22.4739,20.970669,1.503263,1208.04,155,1816,1971
119,EN,NÃO,4. Spectral Estimation Techniques,2.0,Can a discrete-time random process $\calX[n]$ ...,gpt-5,Yes.\n\nHow “power” is defined\n- For a WSS di...,40.6808,33.818354,6.862447,467.91,37,3211,3248

In [2]:
import pandas as pd

df_tutor_gpt_5 = "resultados_brutos/geracao_tutor_gpt-5_pergunta_pt_pergunta_en_COMPLETO.csv"

# Deixar o pandas detectar automaticamente o delimitador
df_tutor_gpt_5 = pd.read_csv(df_tutor_gpt_5)

df_tutor_gpt_5.head(60)

,Idioma,Interferencia_Tutor,Capitulo,Num_Questao,Pergunta,Modelo,Resposta_Gerada,Latencia_Total_s,TTFT_s,ITL_s,Throughput_tps,Tokens_In,Tokens_Out,Tokens_Total
0,PT,SIM,1. Analog and Digital,1.0,Ambos em tempo contínuo $x(t)$ e o tempo discr...,gpt-5,A resposta para sua pergunta é:\na) Para o sin...,79.6917,76.127386,3.564296,150.10,89,535,624
1,PT,SIM,1. Analog and Digital,2.0,Um ADC usa $b=8$ bits por amostra e frequência...,gpt-5,A resposta para sua pergunta é:\na) A taxa de ...,37.9359,35.643701,2.292161,97.72,80,224,304
2,PT,SIM,1. Analog and Digital,5.0,O sinal analógico $x(t)=2t$ ~V é digitalizado ...,gpt-5,A resposta para sua pergunta é:\na) Amostragem...,112.0745,83.441677,28.632867,27.07,120,775,895
3,PT,SIM,1. Analog and Digital,13.0,Um sinal analógico $x(t)$ foi amostrado period...,gpt-5,A resposta para sua pergunta é:\na) Pelo model...,110.7683,104.949503,5.818771,76.99,114,448,562
4,PT,SIM,1. Analog and Digital,15.0,Um $b=8$ -bits ADC usa complemento de dois par...,gpt-5,A resposta para sua pergunta é:\nVamos assumir...,119.5431,90.169227,29.373887,55.29,139,1624,1763
5,PT,SIM,1. Analog and Digital,16.0,Uma sinusóide $x[n]=\sin((\pi/3)n)$ foi quanti...,gpt-5,A resposta para sua pergunta é:\n- Período fun...,106.8034,92.552084,14.251348,69.33,153,988,1141
6,PT,SIM,1. Analog and Digital,17.0,O objetivo é projetar um quantizador escalar u...,gpt-5,A resposta para sua pergunta é:\na) Projeto do...,101.0500,81.314963,19.735066,77.32,108,1526,1634
7,PT,SIM,1. Analog and Digital,20.0,Considere que você deseja quantizar uma senóid...,gpt-5,A resposta para sua pergunta é:\nUsando o mode...,84.4775,69.119842,15.357640,61.99,113,952,1065
8,PT,SIM,1. Analog and Digital,22.0,Um sistema de aquisição de dados usa um ADC de...,gpt-5,A resposta para sua pergunta é: aproximadament...,58.4579,50.128401,8.329549,72.87,112,607,719
9,PT,SIM,1. Analog and Digital,23.0,Um ADC de oito bits usa complemento de dois e ...,gpt-5,A resposta para sua pergunta é:\na) Pelo model...,155.1014,149.364273,5.737145,91.68,133,526,659
10,PT,SIM,1. Analog and Digital,28.0,"Você não sabe muito sobre um sinal $x[n]$, mas...",gpt-5,"ERRO: HTTPConnectionPool(host='127.0.0.1', por...",0.0000,0.000000,0.000000,0.00,0,0,0
11,PT,SIM,1. Analog and Digital,29.0,"Para os seguintes sinais, calcule a energia $E...",gpt-5,A resposta para sua pergunta é:\n- a) Para $x(...,79.6454,62.937985,16.707445,82.36,54,1376,1430
12,PT,SIM,1. Analog and Digital,30.0,O que pode ser dito sobre a energia total e a ...,gpt-5,A resposta para sua pergunta é: todo sinal per...,39.4615,36.809618,2.651865,110.49,22,293,315
13,PT,SIM,1. Analog and Digital,31.0,"a) O conjunto $\calM = \{-7,-5,-3,-1,1,3,5,7\}...",gpt-5,A resposta para sua pergunta é:\na) Como todos...,73.7518,69.364629,4.387208,79.32,143,348,491
14,PT,SIM,1. Analog and Digital,32.0,"Para cada um dos seguintes sinais, determine s...",gpt-5,A resposta para sua pergunta é:\n- a) Não peri...,91.8253,76.276025,15.549249,72.99,62,1135,1197
15,PT,SIM,2. Transforms and Signal Representation,1.0,"Dados dois vetores $[4, 3]$ e $[-5, 2]$, encon...",gpt-5,A resposta para sua pergunta é:\n- Normas (L2)...,34.4341,32.305679,2.128393,116.99,24,249,273
16,PT,SIM,2. Transforms and Signal Representation,2.0,"Dados dois vetores $\bx=[4, 0]$ e $\by=[-5, 2]...",gpt-5,A resposta para sua pergunta é:\n- Produto int...,80.5891,69.661403,10.927718,66.07,38,722,760
17,PT,SIM,2. Transforms and Signal Representation,3.0,É a matriz $\bA =\n \begin{bmatrix}\n 1 ...,gpt-5,A resposta para sua pergunta é:\n- Como verifi...,62.4309,56.009356,6.421498,86.58,60,556,616
18,PT,SIM,2. Transforms and Signal Representation,4.0,Suponha que um espaço vetorial 2-d tenha uma b...,gpt-5,A resposta para sua pergunta é:\nComo a base é...,56.0340,50.834400,5.199599,94.24,69,490,559
19,PT,SIM,2. Transforms and Signal Representation,5.0,Use o procedimento de Gram-Schmidt para encont...,gpt-5,A resposta para sua pergunta é:\nAplicando Gra...,61.4387,47.205144,14.233557,84.03,76,1196,1272
20,PT,SIM,2. Transforms and Signal Representation,10.0,Quais são os avançados $\bA$ e inverso $\bA^H$...,gpt-5,A resposta para sua pergunta é:\nPara a DFT or...,58.5080,55.977150,2.530807,96.41,23,244,267
21,PT,SIM,2. Transforms and Signal Representation,12.0,"Dado que $\bX=[8,0,0,0]$ foi obtido com uma DF...",gpt-5,A resposta para sua pergunta é:\n- Inverso da ...,46.8438,44.310749,2.533011,103.83,52,263,315
22,PT,SIM,2. Transforms and Signal Representation,14.0,Usando a condição de ortogonalidade das funçõe...,gpt-5,A resposta para sua pergunta é:\nDerivação usa...,58.8745,41.996623,16.877833,92.96,67,1569,1636
23,PT,SIM,2. Transforms and Signal Representation,15.0,Quais são os coeficientes da série de Fourier ...,gpt-5,A resposta para sua pergunta é:\nComo o proble...,74.6206,63.029828,11.590733,72.73,35,843,878
24,PT,SIM,2. Transforms and Signal Representation,16.0,A série bilateral de Fourier de um sinal $x(t)...,gpt-5,A resposta para sua pergunta é:\nA expressão $...,79.8133,70.648879,9.164444,66.78,52,612,664
25,PT,SIM,2. Transforms and Signal Representation,17.0,Qual é a transformada de Fourier de: a) $x(t) ...,gpt-5,"A resposta para sua pergunta é:\nComo método, ...",92.4319,82.260869,10.171037,69.90,28,711,739
26,PT,SIM,2. Transforms and Signal Representation,18.0,Qual é a transformada de Fourier de: a) $x(t) ...,gpt-5,A resposta para sua pergunta é:\nComo este é e...,94.0630,81.329859,12.733145,74.22,28,945,973
27,PT,SIM,2. Transforms and Signal Representation,19.0,Prove as expressões: a) para a DTFT de $x[n]=0...,gpt-5,A resposta para sua pergunta é:\n\na) DTFT de ...,68.6558,62.076678,6.579139,61.86,28,407,435
28,PT,SIM,2. Transforms and Signal Representation,19.0,Prove as expressões: a) para a DTFT de $x[n]=0...,gpt-5,A resposta para sua pergunta é:\na) DTFT de x[...,76.9419,67.663913,9.277958,51.95,28,482,510
29,PT,SIM,2. Transforms and Signal Representation,20.0,"Considerando o intervalo $\dw \in \left[-\pi,\...",gpt-5,A resposta para sua pergunta é:\nVamos determi...,71.2547,57.312518,13.942157,73.09,66,1019,1085
30,PT,SIM,2. Transforms and Signal Representation,21.0,Prove isso $X(e^{j \dw})=\sum_{k=-\infty}^{\in...,gpt-5,A resposta para sua pergunta é:\nProva usando ...,100.3149,86.055332,14.259542,67.18,46,958,1004
31,PT,SIM,2. Transforms and Signal Representation,24.0,Um sinal do lado direito tem transformada de L...,gpt-5,A resposta para sua pergunta é:\n- a) Avaliand...,64.6179,55.940868,8.677009,71.34,61,619,680
32,PT,SIM,2. Transforms and Signal Representation,25.0,Um sinal $x(t)$ tem transformada de Laplace $X...,gpt-5,A resposta para sua pergunta é:\nComo os polos...,59.8813,49.262484,10.618786,76.28,27,810,837
33,PT,SIM,2. Transforms and Signal Representation,26.0,Um sinal $x[n]$ tem transformadaZ $X(z)=(5z^2+...,gpt-5,A resposta para sua pergunta é:\nComo a ROC é ...,96.1795,88.532179,7.647347,87.61,27,670,697
34,PT,SIM,2. Transforms and Signal Representation,27.0,Encontre a transformada Z e o ROC associado do...,gpt-5,A resposta para sua pergunta é:\n- Transformad...,57.6845,55.014601,2.669937,84.27,23,225,248
35,PT,SIM,2. Transforms and Signal Representation,28.0,Qual é a transformadaZ $X(z)$ do sinal $x[n]=4...,gpt-5,A resposta para sua pergunta é:\n- Pela defini...,71.1653,64.253767,6.911557,81.17,55,561,616
36,PT,SIM,3. Analog and Digital Systems,1.0,Quando a entrada $x_1[n]=\delta[n] + \delta[n-...,gpt-5,A resposta para sua pergunta é:\nComo o sistem...,60.3588,54.258890,6.099955,75.41,58,460,518
37,PT,SIM,3. Analog and Digital Systems,2.0,Quando a entrada $x_1[n]=\delta[n]$ é aplicado...,gpt-5,A resposta para sua pergunta é:\nComo o sistem...,45.0723,39.267490,5.804851,74.08,50,430,480
38,PT,SIM,3. Analog and Digital Systems,3.0,Quando a entrada $x_1[n]=\delta[n]$ é aplicado...,gpt-5,A resposta para sua pergunta é: Não. Esse sist...,59.6710,49.254147,10.416830,83.42,62,869,931
39,PT,SIM,3. Analog and Digital Systems,4.0,Um sistema invariante no tempo tem saída $y_1(...,gpt-5,A resposta para sua pergunta é:\nComo o sistem...,43.2152,38.233229,4.981941,88.92,48,443,491
40,PT,SIM,3. Analog and Digital Systems,5.0,As relações de entrada-saída que descrevem trê...,gpt-5,A resposta para sua pergunta é:\nClassificação...,82.1392,75.061435,7.077772,64.99,77,460,537
41,PT,SIM,3. Analog and Digital Systems,6.0,Um LTI de tempo discreto é caracterizado pela ...,gpt-5,"A resposta para sua pergunta é: escolha, por e...",75.7796,70.567377,5.212179,92.28,56,481,537
42,PT,SIM,3. Analog and Digital Systems,8.0,Quatro sinais de tempo contínuo: $x_1(t)=e^{j4...,gpt-5,A resposta para sua pergunta é:\nComo se trata...,79.5607,70.275434,9.285278,78.94,63,733,796
43,PT,SIM,3. Analog and Digital Systems,9.0,Quatro sinais de tempo discreto: $x_1[n]=5e^{j...,gpt-5,A resposta para sua pergunta é:\nComo cada um ...,70.6500,57.426299,13.223729,67.98,67,899,966
44,PT,SIM,3. Analog and Digital Systems,12.0,Um sinal de banda limitada $x(t)$ foi amostrad...,gpt-5,A resposta para sua pergunta é:\nComo $\fs=10$...,48.9331,46.714215,2.218879,108.16,73,240,313
45,PT,SIM,3. Analog and Digital Systems,16.0,Um filtro passa-baixa analógico não causal tem...,gpt-5,A resposta para sua pergunta é:\nMétodo para o...,70.3089,62.644686,7.664186,64.59,73,495,568
46,PT,SIM,3. Analog and Digital Systems,17.0,\item Um filtro FIR com fase linear tem uma re...,gpt-5,A resposta para sua pergunta é:\nComo se trata...,70.4893,68.823618,1.665698,102.06,42,170,212
47,PT,SIM,3. Analog and Digital Systems,23.0,Um filtro $H(s) = \frac{125}{s^3+10s^2+50s+125...,gpt-5,A resposta para sua pergunta é:\n- Para mudar ...,151.1303,135.022116,16.108203,67.48,64,1087,1151
48,PT,SIM,3. Analog and Digital Systems,25.0,Dado um filtro $H(s)=(0.1s^2+71)/(s^2+11s+71)$...,gpt-5,A resposta para sua pergunta é:\nUsando a tran...,128.5801,117.782131,10.797927,77.42,30,836,866
49,PT,SIM,3. Analog and Digital Systems,27.0,O filtro $H_s(s)=(0.1s^2+71)/(s^2+11s+71)$ dev...,gpt-5,A resposta para sua pergunta é:\n- a) Escolhen...,149.3070,126.901441,22.405569,64.31,122,1441,1563
50,PT,SIM,3. Analog and Digital Systems,12.0,Estude as vantagens e desvantagens ao comparar...,gpt-5,A resposta para sua pergunta é:\n- Bessel\n -...,58.6157,51.584994,7.030658,96.29,23,677,700
51,PT,SIM,4. Spectral Estimation Techniques,2.0,Um cosseno $x[n]=A \cos(\dw_1 n)$ é multiplica...,gpt-5,A resposta para sua pergunta é:\n- Usando o DT...,164.5669,144.687145,19.879735,53.07,117,1055,1172
52,PT,SIM,4. Spectral Estimation Techniques,3.0,"Dado o sinal $x(t)= 12 \sinc(6 t)$ em volts, q...",gpt-5,A resposta para sua pergunta é:\nComo foco no ...,97.6056,87.086815,10.518751,78.34,34,824,858
53,PT,SIM,4. Spectral Estimation Techniques,4.0,Qual é o espectro MS $\hat S_{\textrm{ms}}[k]$...,gpt-5,A resposta para sua pergunta é:\n- Passo 1 (pe...,79.0091,74.301643,4.707495,86.03,47,405,452
54,PT,SIM,4. Spectral Estimation Techniques,5.0,Assumir $X[k]$ éo $N$-ponto FFT de um sinal pe...,gpt-5,A resposta para sua pergunta é:\n- a) Usando a...,101.8007,85.127151,16.673594,60.57,93,1010,1103
55,PT,SIM,4. Spectral Estimation Techniques,6.0,"Assumir $X=[8,8,8,8]$ éo $4$-ponto FFT de um s...",gpt-5,A resposta para sua pergunta é:\nComo você for...,103.2267,91.152147,12.074540,97.81,74,1181,1255
56,PT,SIM,4. Spectral Estimation Techniques,7.0,a) O que é o PSD $S(e^{j \dw})$ de uma exponen...,gpt-5,A resposta para sua pergunta é:\n\na) Após mul...,110.2373,95.864863,14.372455,75.07,77,1079,1156
57,PT,SIM,4. Spectral Estimation Techniques,8.0,O periodograma de uma sinusóide imersa em AWGN...,gpt-5,A resposta para sua pergunta é:\nComo se trata...,84.7018,61.689249,23.012502,39.72,97,914,1011
58,PT,SIM,4. Spectral Estimation Techniques,13.0,O PSD unilateral de um sinal de ruído branco e...,gpt-5,A resposta para sua pergunta é:\na) Como o ruí...,101.7382,87.641403,14.096751,56.75,134,800,934
59,PT,SIM,4. Spectral Estimation Techniques,2.0,Um processo aleatório em tempo discreto pode $...,gpt-5,"A resposta para sua pergunta é:\n- Sim, um pro...",68.0572,61.144866,6.912296,82.32,37,569,606

In [6]:
import pandas as pd

df_tutor_deepseek_v4_pro = "resultados_brutos/geracao_tutor_deepseek-v4-pro_pergunta_pt_pergunta_en_COMPLETO.csv"

# Deixar o pandas detectar automaticamente o delimitador
df_tutor_deepseek_v4_pro = pd.read_csv(df_tutor_deepseek_v4_pro)

df_tutor_deepseek_v4_pro.tail(60)

,Idioma,Interferencia_Tutor,Capitulo,Num_Questao,Pergunta,Modelo,Resposta_Gerada,Latencia_Total_s,TTFT_s,ITL_s,Throughput_tps,Tokens_In,Tokens_Out,Tokens_Total
60,EN,SIM,1. Analog and Digital,1.0,Both continuous-time $x(t)$ and the discrete-t...,deepseek-v4-pro,The answer to your question is: This is exerci...,63.0219,51.427202,11.594655,43.04,88,499,587
61,EN,SIM,1. Analog and Digital,2.0,An ADC uses $b=8$ bits per sample and sampling...,deepseek-v4-pro,The answer to your question is:\n\n**a) Bit ra...,43.3582,37.219056,6.139164,42.35,72,260,332
62,EN,SIM,1. Analog and Digital,5.0,The analog signal $x(t)=2t$~V is digitized usi...,deepseek-v4-pro,A resposta para sua pergunta é:\n\n**a) Primei...,95.2467,71.121924,24.124767,32.00,112,772,884
63,EN,SIM,1. Analog and Digital,13.0,An analog signal $x(t)$ was periodically sampl...,deepseek-v4-pro,A resposta para sua pergunta é:\n\n**a)** Dado...,81.1213,65.319459,15.801864,32.91,109,520,629
64,EN,SIM,1. Analog and Digital,15.0,An $b=8$-bits ADC uses two's complement to out...,deepseek-v4-pro,A resposta para sua pergunta é:\n\nAbaixo é fo...,106.9594,65.328503,41.630899,33.41,128,1391,1519
65,EN,SIM,1. Analog and Digital,16.0,A sinusoid $x[n]=\sin((\pi/3)n)$ was quantized...,deepseek-v4-pro,NaN,134.1160,0.000000,0.000000,0.01,142,1,143
66,EN,SIM,1. Analog and Digital,17.0,The goal is to design a uniform scalar quantiz...,deepseek-v4-pro,A resposta para sua pergunta é:\n\n### a) Proj...,136.1856,121.945377,14.240208,33.43,106,476,582
67,EN,SIM,1. Analog and Digital,20.0,Consider you want to quantize a sinusoid with ...,deepseek-v4-pro,The answer to your question is:\n\nFor a full-...,87.6479,75.420918,12.227005,40.24,108,492,600
68,EN,SIM,1. Analog and Digital,22.0,A data acquisition system uses an ADC of 12 bi...,deepseek-v4-pro,The answer to your question is: The adoption o...,36.7835,32.449371,4.334142,47.76,107,207,314
69,EN,SIM,1. Analog and Digital,23.0,An eight-bits ADC uses two's complement and th...,deepseek-v4-pro,NaN,111.6160,0.000000,0.000000,0.01,125,1,126
70,EN,SIM,1. Analog and Digital,28.0,"You do not know much about a signal $x[n]$, bu...",deepseek-v4-pro,"A resposta para sua pergunta é: **Não, o sinal...",31.7253,26.317231,5.408074,43.27,27,234,261
71,EN,SIM,1. Analog and Digital,29.0,"For the following signals, calculate the energ...",deepseek-v4-pro,The answer to your question is:\n\nFor the con...,106.5390,83.837498,22.701515,42.33,56,961,1017
72,EN,SIM,1. Analog and Digital,30.0,What can be said about the total energy and av...,deepseek-v4-pro,The answer to your question is: for any period...,27.3577,23.361739,3.995921,52.80,20,211,231
73,EN,SIM,1. Analog and Digital,31.0,"a) The set $\calM = \{-7,-5,-3,-1,1,3,5,7\}$ d...",deepseek-v4-pro,The answer to your question is:\n\na) The set ...,68.3893,59.266185,9.123118,42.53,132,388,520
74,EN,SIM,1. Analog and Digital,32.0,"For each of the following signals, determine w...",deepseek-v4-pro,A resposta para sua pergunta é:\n\nVamos anali...,92.4748,75.126674,17.348146,39.49,65,685,750
75,EN,SIM,2. Transforms and Signal Representation,1.0,"Given two vectors $[4, 3]$ and $[-5, 2]$, find...",deepseek-v4-pro,"The answer to your question is:\n\nFirst, let ...",36.7120,30.395128,6.316889,49.39,24,312,336
76,EN,SIM,2. Transforms and Signal Representation,2.0,"Given two vectors $\bx=[4, 0]$ and $\by=[-5, 2...",deepseek-v4-pro,A resposta para sua pergunta é:\n\nPara encont...,51.2637,37.616133,13.647528,52.02,39,710,749
77,EN,SIM,2. Transforms and Signal Representation,3.0,Is the matrix $\bA =\n \begin{bmatrix}\n ...,deepseek-v4-pro,"The answer to your question is:\n\n**No,** the...",66.6233,57.761629,8.861686,46.83,60,415,475
78,EN,SIM,2. Transforms and Signal Representation,4.0,Assume a 2-d vector space has non orthogonal b...,deepseek-v4-pro,A resposta para sua pergunta é: os coeficiente...,43.0904,37.851510,5.238857,49.06,67,257,324
79,EN,SIM,2. Transforms and Signal Representation,5.0,Use the Gram-Schmidt procedure to find an orth...,deepseek-v4-pro,A resposta para sua pergunta é: o contexto rec...,51.2923,29.447652,21.844667,40.56,70,886,956
80,EN,SIM,2. Transforms and Signal Representation,10.0,What are the forward $\bA$ and inverse $\bA^H$...,deepseek-v4-pro,The answer to your question is: For a 3-point ...,38.4519,27.112287,11.339584,39.15,21,444,465
81,EN,SIM,2. Transforms and Signal Representation,12.0,"Given that $\bX=[8,0,0,0]$ was obtained with a...",deepseek-v4-pro,A resposta para sua pergunta é:\n\nO sinal ori...,54.7914,40.969178,13.822258,34.65,50,479,529
82,EN,SIM,2. Transforms and Signal Representation,14.0,Using the orthogonality condition of the basis...,deepseek-v4-pro,A resposta para sua pergunta é:\n\nTo derive t...,40.0891,20.898459,19.190619,46.69,66,896,962
83,EN,SIM,2. Transforms and Signal Representation,15.0,What are the Fourier series coefficients for t...,deepseek-v4-pro,A resposta para sua pergunta é:\n\nPara obter ...,65.6821,49.920289,15.761787,38.32,35,604,639
84,EN,SIM,2. Transforms and Signal Representation,16.0,The bilateral Fourier series of a signal $x(t)...,deepseek-v4-pro,The answer to your question is: using the Four...,35.2323,28.900076,6.332193,41.06,50,260,310
85,EN,SIM,2. Transforms and Signal Representation,17.0,What is the Fourier transform of: a) $x(t) = \...,deepseek-v4-pro,The answer to your question is: \nTo find the...,49.0792,35.156049,13.923171,45.75,28,637,665
86,EN,SIM,2. Transforms and Signal Representation,18.0,What is the Fourier transform of: a) $x(t) = \...,deepseek-v4-pro,A resposta para sua pergunta é: para determina...,103.8990,87.847126,16.051906,41.18,28,661,689
87,EN,SIM,2. Transforms and Signal Representation,19.0,Prove the expressions: a) for the DTFT of $x[n...,deepseek-v4-pro,A resposta para sua pergunta é:\n\nPara o sina...,58.3646,42.450192,15.914396,39.08,30,622,652
88,EN,SIM,2. Transforms and Signal Representation,19.0,Prove the expressions: a) for the DTFT of $x[n...,deepseek-v4-pro,A resposta para sua pergunta é:\n\n**a) Transf...,44.2293,27.126725,17.102579,36.90,30,631,661
89,EN,SIM,2. Transforms and Signal Representation,20.0,"Considering the range $\dw \in \left[-\pi,\pi\...",deepseek-v4-pro,The answer to your question is:\n\nThe inverse...,50.7640,42.218975,8.544979,49.97,61,427,488
90,EN,SIM,2. Transforms and Signal Representation,21.0,Prove that $X(e^{j \dw})=\sum_{k=-\infty}^{\in...,deepseek-v4-pro,A resposta para sua pergunta é:\n\nPara provar...,73.1522,56.962841,16.189395,40.95,44,663,707
91,EN,SIM,2. Transforms and Signal Representation,24.0,A right-sided signal has Laplace transform $X(...,deepseek-v4-pro,The answer to your question is:\n\nWe are give...,58.2662,48.780168,9.486007,46.70,58,443,501
92,EN,SIM,2. Transforms and Signal Representation,25.0,A signal $x(t)$ has Laplace transform $X(s)=(3...,deepseek-v4-pro,The answer to your question is:\n\nGiven \( X(...,40.7218,32.542131,8.179675,40.34,25,330,355
93,EN,SIM,2. Transforms and Signal Representation,26.0,A signal $x[n]$ has Z transform $X(z)=(5z^2+4z...,deepseek-v4-pro,A resposta para sua pergunta é:\n\nPara encont...,90.0515,78.789277,11.262201,33.39,25,376,401
94,EN,SIM,2. Transforms and Signal Representation,27.0,Find the Z transform and associated ROC of the...,deepseek-v4-pro,The answer to your question is:\n\nThe Z‑trans...,55.2155,50.474493,4.740964,50.62,26,240,266
95,EN,SIM,2. Transforms and Signal Representation,28.0,What is the Z transform $X(z)$ of the signal $...,deepseek-v4-pro,The answer to your question is:\n\nThe Z trans...,43.4972,32.684204,10.813026,45.04,57,487,544
96,EN,SIM,3. Analog and Digital Systems,1.0,When the input $x_1[n]=\delta[n] + \delta[n-1]...,deepseek-v4-pro,"The answer to your question is: $y_2[n] = 12\,...",35.6489,32.309700,3.339183,49.71,61,166,227
97,EN,SIM,3. Analog and Digital Systems,2.0,When the input $x_1[n]=\delta[n]$ is applied t...,deepseek-v4-pro,The answer to your question is: the output $y_...,53.7530,46.062994,7.690019,45.90,51,353,404
98,EN,SIM,3. Analog and Digital Systems,3.0,When the input $x_1[n]=\delta[n]$ is applied t...,deepseek-v4-pro,"The answer to your question is: No, this syste...",58.5828,50.961583,7.621210,48.16,64,367,431
99,EN,SIM,3. Analog and Digital Systems,4.0,A time-invariant system has output $y_1(t) = \...,deepseek-v4-pro,A resposta para sua pergunta é: \nO sistema é...,68.0300,64.237561,3.792438,44.56,49,169,218
100,EN,SIM,3. Analog and Digital Systems,5.0,The input-output relations that describe three...,deepseek-v4-pro,The answer to your question is:\n\n**System 1:...,91.8674,79.948388,11.918990,53.61,74,639,713
101,EN,SIM,3. Analog and Digital Systems,6.0,A discrete-time LTI is characterized by the di...,deepseek-v4-pro,The answer to your question is: **\(n_0 = 0\)*...,57.8597,50.220466,7.639220,44.64,55,341,396
102,EN,SIM,3. Analog and Digital Systems,8.0,Four continuous-time signals: $x_1(t)=e^{j4t}$...,deepseek-v4-pro,The answer to your question is:\n\nThe system ...,74.3688,57.772648,16.596140,38.86,60,645,705
103,EN,SIM,3. Analog and Digital Systems,9.0,"Four discrete-time signals: $x_1[n]=5e^{j2n}$,...",deepseek-v4-pro,The answer to your question is:\n\nFor the cau...,99.3219,86.855327,12.466561,38.90,65,485,550
104,EN,SIM,3. Analog and Digital Systems,12.0,A band-limited signal $x(t)$ was sampled obeyi...,deepseek-v4-pro,The answer to your question is:\n\nGiven the s...,37.6255,29.607287,8.018175,45.40,68,364,432
105,EN,SIM,3. Analog and Digital Systems,16.0,A non-causal analog lowpass filter has an idea...,deepseek-v4-pro,The answer to your question is: The filter has...,61.6267,56.588269,5.038465,44.26,72,223,295
106,EN,SIM,3. Analog and Digital Systems,17.0,\item A FIR filter with linear phase has an im...,deepseek-v4-pro,The answer to your question is: \nThe system ...,25.6850,22.231075,3.453887,51.25,41,177,218
107,EN,SIM,3. Analog and Digital Systems,23.0,A filter $H(s) = \frac{125}{s^3+10s^2+50s+125}...,deepseek-v4-pro,A resposta para sua pergunta é:\n\nTo obtain \...,60.8014,48.586934,12.214446,43.80,61,535,596
108,EN,SIM,3. Analog and Digital Systems,25.0,Given a filter $H(s)=(0.1s^2+71)/(s^2+11s+71)$...,deepseek-v4-pro,A resposta para sua pergunta é:\n\nPara obter ...,66.0802,50.675902,15.404291,38.89,28,599,627
109,EN,SIM,3. Analog and Digital Systems,27.0,The filter $H_s(s)=(0.1s^2+71)/(s^2+11s+71)$ s...,deepseek-v4-pro,The answer to your question is:\n\n**a)** To d...,72.5799,59.140061,13.439857,45.02,122,605,727
110,EN,SIM,3. Analog and Digital Systems,12.0,Study the advantages and disadvantages when co...,deepseek-v4-pro,The answer to your question is:\n\nWhen design...,38.3548,29.171890,9.182947,48.46,24,445,469
111,EN,SIM,4. Spectral Estimation Techniques,2.0,A cosine $x[n]=A \cos(\dw_1 n)$ is multiplied ...,deepseek-v4-pro,NaN,119.1137,0.000000,0.000000,0.01,112,1,113
112,EN,SIM,4. Spectral Estimation Techniques,3.0,Given the signal $x(t)= 12 \sinc(6 t)$ in volt...,deepseek-v4-pro,The answer to your question is:\n\nTo determin...,92.2707,75.488206,16.782511,44.45,35,746,781
113,EN,SIM,4. Spectral Estimation Techniques,4.0,What is the MS spectrum $\hat S_{\textrm{ms}}[...,deepseek-v4-pro,The answer to your question is: the MS spectru...,38.6251,31.349633,7.275422,48.93,48,356,404
114,EN,SIM,4. Spectral Estimation Techniques,5.0,Assume $X[k]$ is the $N$-point FFT of a period...,deepseek-v4-pro,The answer to your question is:\n\na) The esti...,98.3979,90.948176,7.449704,37.05,90,276,366
115,EN,SIM,4. Spectral Estimation Techniques,6.0,"Assume $X=[8,8,8,8]$ is the $4$-point FFT of a...",deepseek-v4-pro,The answer to your question is:\n\nGiven $X[k]...,98.6928,92.637078,6.055717,39.14,75,237,312
116,EN,SIM,4. Spectral Estimation Techniques,7.0,a) What is the PSD $S(e^{j \dw})$ of a complex...,deepseek-v4-pro,The answer to your question is provided as a s...,90.0401,57.701565,32.338487,43.94,78,1421,1499
117,EN,SIM,4. Spectral Estimation Techniques,8.0,The periodogram of a sinusoid immersed in AWGN...,deepseek-v4-pro,The answer to your question is:\n\na) **Sinuso...,88.6368,78.765518,9.871293,39.71,95,392,487
118,EN,SIM,4. Spectral Estimation Techniques,13.0,The unilateral PSD of a continuous-time white ...,deepseek-v4-pro,A resposta para sua pergunta é: $\mathcal{P} =...,58.5170,46.340638,12.176364,41.88,128,510,638
119,EN,SIM,4. Spectral Estimation Techniques,2.0,Can a discrete-time random process $\calX[n]$ ...,deepseek-v4-pro,"The answer to your question is: **Yes**, a dis...",69.7236,60.272835,9.450780,48.57,35,459,494